# Generated by Django 5.2.14 on 2026-05-22 19:48

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "client_event_id",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("usage", "Usage"),
                            ("error", "Error"),
                            ("performance", "Performance"),
                            ("security", "Security"),
                            ("fraud_signal", "Fraud signal"),
                            ("audit", "Audit"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("name", models.CharField(db_index=True, max_length=120)),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("debug", "Debug"),
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("error", "Error"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="info",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("frontend", "Frontend"),
                            ("backend", "Backend"),
                            ("print_agent", "Print agent"),
                            ("integration", "Integration"),
                        ],
                        db_index=True,
                        default="frontend",
                        max_length=32,
                    ),
                ),
                ("occurred_at", models.DateTimeField(db_index=True)),
                (
                    "session_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                (
                    "device_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                (
                    "installation_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                ("app_version", models.CharField(blank=True, max_length=40)),
                ("platform", models.CharField(blank=True, max_length=48)),
                ("request_path", models.CharField(blank=True, max_length=256)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True)),
                (
                    "trace_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                (
                    "received_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="analytics_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "occurred_at"],
                        name="analytics_a_event_t_69a889_idx",
                    ),
                    models.Index(
                        fields=["name", "occurred_at"],
                        name="analytics_a_name_119f75_idx",
                    ),
                    models.Index(
                        fields=["source", "occurred_at"],
                        name="analytics_a_source_06a74b_idx",
                    ),
                    models.Index(
                        fields=["received_by", "occurred_at"],
                        name="analytics_a_receive_8ee9bf_idx",
                    ),
                    models.Index(
                        fields=["entity_type", "entity_id"],
                        name="analytics_a_entity__c2ba36_idx",
                    ),
                    models.Index(
                        fields=["risk_score", "occurred_at"],
                        name="analytics_a_risk_sc_d025c7_idx",
                    ),
                ],
            },
        ),
    ]
