# Generated by Django 5.2.14 on 2026-09-25 20:27

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("customers", "0012_paymentcard_cardholder_name"),
        ("payments", "0016_payment_method_account_credit"),
        ("purchasing", "0035_supplierpayment_money_account_and_more"),
        ("sales", "0039_order_sale_type_account_entry"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerBalanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("number", models.CharField(blank=True, max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("adjustment", "Balance adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("they_owe_us", "They owe us"),
                            ("we_owe_them", "We owe them"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("effective_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="balances.customerbalanceentry",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_entries",
                        to="customers.customer",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_entry",
                        to="sales.order",
                    ),
                ),
                (
                    "cash_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="customer_balance_entry",
                        to="sales.registercashmovement",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="balances.customerbalanceentry",
                    ),
                ),
            ],
            options={
                "verbose_name": "customer balance entry",
                "verbose_name_plural": "customer balance entries",
                "ordering": ["-effective_date", "-id"],
                "permissions": [
                    (
                        "cancel_customerbalanceentry",
                        "Cancel an opening balance or adjustment on a customer's account",
                    )
                ],
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CustomerCreditApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="applications",
                        to="balances.customerbalanceentry",
                    ),
                ),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_application",
                        to="payments.payment",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="SupplierBalanceEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("number", models.CharField(blank=True, max_length=32, unique=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("opening", "Opening balance"),
                            ("adjustment", "Balance adjustment"),
                            ("refund", "Refund"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "direction",
                    models.CharField(
                        choices=[
                            ("they_owe_us", "They owe us"),
                            ("we_owe_them", "We owe them"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("effective_date", models.DateField()),
                ("note", models.TextField(blank=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="balances.supplierbalanceentry",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="balances.supplierbalanceentry",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="balance_entries",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "cash_movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="supplier_balance_entry",
                        to="sales.registercashmovement",
                    ),
                ),
            ],
            options={
                "verbose_name": "supplier balance entry",
                "verbose_name_plural": "supplier balance entries",
                "ordering": ["-effective_date", "-id"],
                "permissions": [
                    (
                        "cancel_supplierbalanceentry",
                        "Cancel an opening balance or adjustment on a supplier's account",
                    )
                ],
                "abstract": False,
            },
        ),
        migrations.AddIndex(
            model_name="customerbalanceentry",
            index=models.Index(
                fields=["customer", "direction", "doc_status"],
                name="balances_customer_open_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierbalanceentry",
            index=models.Index(
                fields=["supplier", "direction", "doc_status"],
                name="balances_supplier_open_idx",
            ),
        ),
    ]
