# Generated by Django 6.0.2 on 2026-10-08 22:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0002_employee_balance_entries"),
        ("treasury", "0005_card_settlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="customerbalanceentry",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="employeebalanceentry",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="supplierbalanceentry",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="+",
                to="treasury.moneyaccount",
            ),
        ),
    ]
