# Generated by Django 6.0.2 on 2026-05-17 14:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_tax_rate"),
        ("inventory", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="quantity_committed",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="quantity_expected",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="StockMovement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "movement_type",
                    models.CharField(
                        choices=[
                            ("receive", "Receive stock"),
                            ("issue", "Issue stock"),
                            ("adjustment_in", "Adjustment in"),
                            ("adjustment_out", "Adjustment out"),
                            ("commit", "Commit stock"),
                            ("release_commitment", "Release commitment"),
                            ("expect", "Expect stock"),
                            ("receive_expected", "Receive expected stock"),
                            ("cancel_expected", "Cancel expected stock"),
                        ],
                        max_length=32,
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                ("note", models.CharField(blank=True, max_length=240)),
                ("on_hand_before", models.IntegerField()),
                ("on_hand_after", models.IntegerField()),
                ("committed_before", models.IntegerField()),
                ("committed_after", models.IntegerField()),
                ("expected_before", models.IntegerField()),
                ("expected_after", models.IntegerField()),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_movements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stock_movements",
                        to="catalog.product",
                    ),
                ),
                (
                    "stock_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="movements",
                        to="inventory.stockitem",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
