# Generated by Django 6.0.2 on 2026-05-17 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_stockitem_quantity_committed_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("increase", "Increase stock"),
                    ("decrease", "Decrease stock"),
                    ("damaged", "Damaged stock"),
                ],
                max_length=32,
            ),
        ),
    ]
