# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("increase", "Increase stock"),
                    ("decrease", "Decrease stock"),
                    ("damaged", "Damaged stock"),
                    ("expected", "Expected stock"),
                    ("receive_expected", "Receive expected stock"),
                    ("receive_damaged", "Receive damaged expected stock"),
                    ("cancel_expected", "Cancel expected stock"),
                ],
                max_length=32,
            ),
        ),
    ]
