# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


def default_variant_for(product_variant_model, product_id):
    return (
        product_variant_model.objects.filter(product_id=product_id)
        .order_by("-is_default", "id")
        .first()
    )


def backfill_stock_variants(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    StockItem = apps.get_model("inventory", "StockItem")
    StockMovement = apps.get_model("inventory", "StockMovement")

    for stock_item in StockItem.objects.all().order_by("id"):
        variant = default_variant_for(ProductVariant, stock_item.product_id)
        if variant is not None:
            stock_item.variant_id = variant.pk
            stock_item.save(update_fields=["variant"])

    for movement in StockMovement.objects.all().order_by("id"):
        variant = default_variant_for(ProductVariant, movement.product_id)
        if variant is not None:
            movement.variant_id = variant.pk
            movement.save(update_fields=["variant"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_variants"),
        ("inventory", "0004_expand_stock_movement_types"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockitem",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="catalog.product",
            ),
        ),
        migrations.AddField(
            model_name="stockitem",
            name="variant",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="catalog.productvariant",
            ),
        ),
        migrations.RunPython(backfill_stock_variants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="stockitem",
            name="variant",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_movements",
                to="catalog.productvariant",
            ),
        ),
    ]
