# Generated by Codex on 2026-05-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_variant_stock"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockitem",
            options={"ordering": ["variant__product__name", "variant__name"]},
        ),
    ]
