# Generated by Django 5.2.14 on 2026-06-12 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0008_stockbatch"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockbatch",
            name="received_quantity",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="remaining_quantity",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity_committed",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity_expected",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="quantity_on_hand",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="committed_after",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="committed_before",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="expected_after",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="expected_before",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="on_hand_after",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="on_hand_before",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="quantity",
            field=models.DecimalField(decimal_places=3, max_digits=12),
        ),
    ]
