# Generated by Django 5.2.14 on 2026-06-15 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_archived_at_product_archived_by"),
        ("inventory", "0009_alter_stockbatch_received_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("owner_key", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("in_progress", "In progress"),
                            ("applied", "Applied"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="in_progress",
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("full", "Full shop"),
                            ("category", "Single category"),
                        ],
                        default="full",
                        max_length=16,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("expected_line_count", models.PositiveIntegerField(default=0)),
                ("applied_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "applied_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applied_stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_counts",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_counts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("apply_stockcount", "Can apply stock count adjustments")
                ],
            },
        ),
        migrations.CreateModel(
            name="StockCountLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "counted_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                (
                    "expected_quantity",
                    models.DecimalField(decimal_places=3, max_digits=12),
                ),
                ("counted_at", models.DateTimeField()),
                ("needs_review", models.BooleanField(default=False)),
                ("applied", models.BooleanField(default=False)),
                ("stale_at_apply", models.BooleanField(default=False)),
                (
                    "on_hand_at_apply",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                (
                    "counted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_count_lines",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="stock_count_lines",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "stock_count",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stockcount",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_count_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["variant__product__name", "variant__name", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="stockcount",
            index=models.Index(
                fields=["status", "-created_at"], name="inventory_s_status_d09991_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "in_progress")),
                fields=("owner_key",),
                name="unique_in_progress_stock_count_per_owner",
            ),
        ),
        migrations.AddIndex(
            model_name="stockcountline",
            index=models.Index(
                fields=["stock_count", "needs_review"],
                name="inventory_s_stock_c_9d7c24_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockcountline",
            constraint=models.UniqueConstraint(
                fields=("stock_count", "variant"), name="unique_variant_per_stock_count"
            ),
        ),
    ]
