# Generated by Django 5.2.14 on 2026-06-15 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0011_stockcountline_movement_acknowledged_at_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockcountline",
            name="movement_acknowledged_at",
        ),
        migrations.RemoveField(
            model_name="stockcountline",
            name="movement_acknowledged_by",
        ),
    ]
