# Generated by Django 5.2.14 on 2026-08-26 03:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_search_trigram_upper_indexes"),
        ("inventory", "0013_alter_stockbatch_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Warehouse",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("is_default", models.BooleanField(db_index=True, default=False)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["-is_default", "name", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockValuationBin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "valuation_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "stock_value",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("state", models.JSONField(blank=True, default=list)),
                ("method", models.CharField(default="moving_average", max_length=20)),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="valuation_bins",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="valuation_bins",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("variant", "warehouse"),
                        name="stock_valuation_bin_unique",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="StockLedgerEntry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("posting_at", models.DateTimeField(db_index=True)),
                (
                    "quantity_change",
                    models.DecimalField(decimal_places=3, max_digits=14),
                ),
                (
                    "valuation_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "value_change",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "balance_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=14),
                ),
                (
                    "balance_value",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("state", models.JSONField(blank=True, default=list)),
                ("method", models.CharField(default="moving_average", max_length=20)),
                (
                    "voucher_type",
                    models.CharField(
                        choices=[
                            ("sale", "Sale"),
                            ("sale_return", "Sale return"),
                            ("purchase_receipt", "Purchase receipt"),
                            ("purchase_return", "Purchase return"),
                            ("production", "Production"),
                            ("stock_count", "Stock count"),
                            ("adjustment", "Manual adjustment"),
                            ("opening", "Opening balance"),
                        ],
                        db_index=True,
                        default="adjustment",
                        max_length=24,
                    ),
                ),
                (
                    "voucher_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "movement",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entry",
                        to="inventory.stockmovement",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ledger_entries",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="ledger_entries",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["posting_at", "id"],
                "indexes": [
                    models.Index(
                        fields=["variant", "warehouse", "posting_at", "id"],
                        name="sle_variant_wh_posting_idx",
                    ),
                    models.Index(
                        fields=["voucher_type", "voucher_id"], name="sle_voucher_idx"
                    ),
                ],
            },
        ),
    ]
