# Generated by Django 5.2.14 on 2026-09-06 23:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_productalias_source"),
        ("inventory", "0017_backfill_stock_count_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockitem",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_items",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="allow_overselling",
            field=models.CharField(
                choices=[
                    ("shop_default", "Follow the shop setting"),
                    ("allow", "Allow selling below zero"),
                    ("refuse", "Refuse selling below zero"),
                ],
                db_default="shop_default",
                default="shop_default",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="warehouse",
            name="kind",
            field=models.CharField(
                choices=[
                    ("shop_floor", "Shop floor"),
                    ("store_room", "Store room"),
                    ("van", "Van"),
                    ("transit", "In transit"),
                ],
                db_default="shop_floor",
                default="shop_floor",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="stockitem",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="stock_items",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockitem",
            constraint=models.UniqueConstraint(
                fields=("variant", "warehouse"),
                name="stock_item_variant_warehouse_unique",
            ),
        ),
    ]
