# Generated by Django 5.2.14 on 2026-09-07 00:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0019_backfill_stock_item_warehouse"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockcount",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_counts",
                to="inventory.warehouse",
            ),
        ),
    ]
