# Generated by Django 5.2.14 on 2026-09-07 01:10

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_productalias_source"),
        ("inventory", "0021_stock_movement_warehouse"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockledgerentry",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("sale_return", "Sale return"),
                    ("purchase_receipt", "Purchase receipt"),
                    ("purchase_return", "Purchase return"),
                    ("production", "Production"),
                    ("stock_count", "Stock count"),
                    ("adjustment", "Manual adjustment"),
                    ("opening", "Opening balance"),
                    ("transfer", "Warehouse transfer"),
                    ("transfer_receipt", "Warehouse transfer receipt"),
                ],
                db_index=True,
                default="adjustment",
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="stockmovement",
            name="movement_type",
            field=models.CharField(
                choices=[
                    ("increase", "Increase stock"),
                    ("decrease", "Decrease stock"),
                    ("damaged", "Damaged stock"),
                    ("expected", "Expected stock"),
                    ("receive_expected", "Receive expected stock"),
                    ("receive_damaged", "Receive damaged expected stock"),
                    ("cancel_expected", "Cancel expected stock"),
                    ("transfer_out", "Sent to another warehouse"),
                    ("transfer_in", "Received from another warehouse"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                (
                    "transfer_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_transit", "In transit"),
                            ("partially_received", "Partially received"),
                            ("received", "Received"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                ("dispatched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="inventory.stocktransfer",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "destination",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_in",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfers_out",
                        to="inventory.warehouse",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("dispatch_stocktransfer", "Can send stock between warehouses"),
                    ("receive_stocktransfer", "Can receive transferred stock"),
                ],
            },
        ),
        migrations.CreateModel(
            name="StockTransferLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                ("unit", models.CharField(blank=True, default="", max_length=32)),
                (
                    "unit_factor",
                    models.DecimalField(
                        decimal_places=3, default=Decimal("1"), max_digits=12
                    ),
                ),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stocktransfer",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("note", models.CharField(blank=True, max_length=240)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="inventory.stocktransferreceipt",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="inventory.stocktransferreceipt",
                    ),
                ),
                (
                    "transfer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipts",
                        to="inventory.stocktransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.CreateModel(
            name="StockTransferReceiptLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "receipt",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lines",
                        to="inventory.stocktransferreceipt",
                    ),
                ),
                (
                    "transfer_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="receipt_lines",
                        to="inventory.stocktransferline",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="transfer_receipt_lines",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.AddIndex(
            model_name="stocktransfer",
            index=models.Index(
                fields=["status", "-created_at"], name="inventory_s_status_e03eb2_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("source", models.F("destination")), _negated=True),
                name="stock_transfer_source_is_not_destination",
            ),
        ),
    ]
