# Generated by Django 5.2.14 on 2026-09-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_identified_stock"),
        ("customers", "0012_paymentcard_cardholder_name"),
        ("inventory", "0024_seed_transfer_number_series"),
        ("purchasing", "0034_seed_order_number_series"),
        ("sales", "0033_seed_receipt_number_series"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockAllocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("in", "Received"), ("out", "Issued")], max_length=4
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "value_change",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("voucher_type", models.CharField(db_index=True, max_length=24)),
                (
                    "voucher_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("posting_at", models.DateTimeField(db_index=True)),
                ("note", models.CharField(blank=True, max_length=240)),
            ],
            options={
                "ordering": ["posting_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockBatchBalance",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "received_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "remaining_quantity",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                (
                    "incoming_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                ("first_received_at", models.DateTimeField(blank=True, null=True)),
                ("expiry_date", models.DateField(blank=True, null=True)),
                ("is_sellable", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["expiry_date", "first_received_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="StockUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=120)),
                (
                    "code_normalized",
                    models.CharField(db_index=True, editable=False, max_length=120),
                ),
                (
                    "identifier_kind",
                    models.CharField(
                        choices=[
                            ("imei", "IMEI"),
                            ("serial", "Serial number"),
                            ("vin", "VIN / chassis"),
                            ("plate", "Plate number"),
                            ("custom", "Custom identifier"),
                        ],
                        default="serial",
                        max_length=16,
                    ),
                ),
                ("secondary_code", models.CharField(blank=True, max_length=120)),
                (
                    "secondary_code_normalized",
                    models.CharField(
                        blank=True, db_index=True, editable=False, max_length=120
                    ),
                ),
                ("supplier_code", models.CharField(blank=True, max_length=120)),
                ("is_identified", models.BooleanField(db_index=True, default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("expected", "On order"),
                            ("in_stock", "In stock"),
                            ("reserved", "Reserved"),
                            ("in_transit", "In transit"),
                            ("sold", "Sold"),
                            ("returned", "Returned to supplier"),
                            ("damaged", "Damaged"),
                            ("written_off", "Written off"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="in_stock",
                        max_length=16,
                    ),
                ),
                (
                    "incoming_rate",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "refurb_cost",
                    models.DecimalField(decimal_places=6, default=0, max_digits=18),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("is_consignment", models.BooleanField(default=False)),
                (
                    "declared_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("in_stock_since", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_warranty_expires_on",
                    models.DateField(blank=True, null=True),
                ),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                ("warranty_expires_on", models.DateField(blank=True, null=True)),
                ("attributes", models.JSONField(blank=True, default=dict)),
                ("notes", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-in_stock_since", "-id"],
                "permissions": [
                    ("reprice_stockunit", "Can change an identified unit's price"),
                    ("write_off_stockunit", "Can write off an identified unit"),
                    ("view_stockunit_cost", "Can see what an identified unit cost"),
                ],
            },
        ),
        migrations.AlterModelOptions(
            name="stockbatch",
            options={
                "ordering": ["expiry_date", "created_at", "id"],
                "permissions": [
                    ("manage_batches", "Can create and edit lots"),
                    (
                        "adjust_batch_balance",
                        "Can adjust a lot's balance in a warehouse",
                    ),
                    ("quarantine_batch", "Can quarantine a lot and start a recall"),
                    ("override_expired_batch_sale", "Can sell an expired lot"),
                ],
            },
        ),
        migrations.RemoveConstraint(
            model_name="stockbatch",
            name="stock_batch_remaining_lte_received",
        ),
        migrations.RemoveIndex(
            model_name="stockbatch",
            name="stockbatch_variant_expiry_idx",
        ),
        migrations.RemoveIndex(
            model_name="stockbatch",
            name="stockbatch_exp_remain_idx",
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="attributes",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="barcode",
            field=models.CharField(blank=True, db_index=True, max_length=120),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="code",
            field=models.CharField(default="", max_length=120),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="code_is_generated",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="code_normalized",
            field=models.CharField(
                db_index=True, default="", editable=False, max_length=120
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="gtin",
            field=models.CharField(blank=True, max_length=14),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="is_locked",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="manufactured_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="notes",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="parent_batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sub_batches",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("quarantined", "Quarantined"),
                    ("expired", "Expired"),
                ],
                db_index=True,
                default="active",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="stockbatch",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_batches",
                to="purchasing.supplier",
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="received_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="remaining_quantity",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=12, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="source_receipt_line",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_batch",
                to="purchasing.purchasereceiptline",
            ),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_batches",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(fields=["code_normalized"], name="stockbatch_code_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(fields=["barcode"], name="stockbatch_barcode_idx"),
        ),
        migrations.AddIndex(
            model_name="stockbatch",
            index=models.Index(
                fields=["variant", "expiry_date"], name="stockbatch_variant_expiry_idx"
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="ledger_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="inventory.stockledgerentry",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="movement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="allocations",
                to="inventory.stockmovement",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_allocations",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_allocations",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockbatchbalance",
            name="batch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="balances",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockbatchbalance",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_balances",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockbatchbalance",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="batch_balances",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="asset",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_units",
                to="customers.asset",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="batch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="inventory.stockbatch",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="consignment_units",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchased_stock_units",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="purchase_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_units",
                to="purchasing.purchaseline",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="sold_order_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_units",
                to="sales.orderline",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="source_receipt_line",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_units",
                to="purchasing.purchasereceiptline",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="stock_units",
                to="purchasing.supplier",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_units",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="warehouse",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_units",
                to="inventory.warehouse",
            ),
        ),
        migrations.AddField(
            model_name="stockallocation",
            name="unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="allocations",
                to="inventory.stockunit",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatchbalance",
            index=models.Index(
                fields=[
                    "variant",
                    "warehouse",
                    "is_sellable",
                    "expiry_date",
                    "remaining_quantity",
                ],
                name="batch_balance_fefo_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockbatchbalance",
            index=models.Index(
                fields=["batch", "remaining_quantity"], name="batch_balance_where_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatchbalance",
            constraint=models.UniqueConstraint(
                fields=("batch", "warehouse"), name="stock_batch_balance_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatchbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(("remaining_quantity__gte", 0)),
                name="batch_balance_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockbatchbalance",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("remaining_quantity__lte", models.F("received_quantity"))
                ),
                name="batch_balance_remaining_lte_received",
            ),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(fields=["code_normalized"], name="stockunit_code_idx"),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(
                fields=["secondary_code_normalized"], name="stockunit_code2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(
                fields=["variant", "status", "in_stock_since"],
                name="stockunit_picker_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(
                fields=["status", "warehouse", "variant"], name="stockunit_bin_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(fields=["batch", "status"], name="stockunit_batch_idx"),
        ),
        migrations.AddConstraint(
            model_name="stockunit",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("status__in", ["expected", "in_stock", "reserved", "in_transit"])
                ),
                fields=("code_normalized",),
                name="stock_unit_live_code_unique",
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["unit", "posting_at"], name="stockalloc_unit_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["batch", "posting_at"], name="stockalloc_batch_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="stockallocation",
            index=models.Index(
                fields=["voucher_type", "voucher_id"], name="stockalloc_voucher_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="stockallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit__isnull", False), ("batch__isnull", False), _connector="OR"
                ),
                name="stock_allocation_names_something",
            ),
        ),
        migrations.AddConstraint(
            model_name="stockallocation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("unit__isnull", True), ("quantity", 1), _connector="OR"
                ),
                name="stock_allocation_unit_quantity_is_one",
            ),
        ),
    ]
