"""The pre-split columns go, now that 0026 has moved what they held.

``source_receipt_line`` is **removed, not loosened**. Widening it from a
``OneToOneField`` to a ``ForeignKey`` was the obvious repair and it is the wrong
one for the same reason the bundle is wrong: a lot arriving in three deliveries
has three provenances, and a column that can hold one of them is a column that
will be read as though it held all three. Provenance is the ``in`` allocations,
which carry voucher, place, quantity and rate — and which 0026 wrote for every
row that used to point at a receipt line.

``stock_batch_code_unique_per_variant`` lands here rather than in 0025 because
it can only hold once every existing row has a code, which is 0026's job.
"""

# Generated by Django 5.2.14 on 2026-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_identified_stock"),
        ("inventory", "0026_split_batch_identity_and_balance"),
        ("purchasing", "0034_seed_order_number_series"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stockbatch",
            name="received_quantity",
        ),
        migrations.RemoveField(
            model_name="stockbatch",
            name="remaining_quantity",
        ),
        migrations.RemoveField(
            model_name="stockbatch",
            name="source_receipt_line",
        ),
        migrations.AddConstraint(
            model_name="stockbatch",
            constraint=models.UniqueConstraint(
                fields=("variant", "code_normalized"),
                name="stock_batch_code_unique_per_variant",
            ),
        ),
    ]
