# Generated by Django 5.2.14 on 2026-09-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0027_drop_legacy_batch_columns"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockbatch",
            name="code",
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name="stockbatch",
            name="code_normalized",
            field=models.CharField(db_index=True, editable=False, max_length=120),
        ),
    ]
