# Generated by Django 6.0.2 on 2026-09-18 07:35

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_identified_stock"),
        ("customers", "0012_paymentcard_cardholder_name"),
        ("inventory", "0029_stock_unit_attribute_indexes"),
        ("purchasing", "0034_seed_order_number_series"),
        ("sales", "0033_seed_receipt_number_series"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitAttributeDefinition",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("key", models.SlugField(max_length=48)),
                ("label", models.CharField(max_length=80)),
                (
                    "data_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("percent", "Percent"),
                            ("money", "Money"),
                            ("date", "Date"),
                            ("choice", "Choice"),
                            ("bool", "Yes / no"),
                        ],
                        default="text",
                        max_length=16,
                    ),
                ),
                ("choices", models.JSONField(blank=True, default=list)),
                ("suffix", models.CharField(blank=True, max_length=16)),
                ("is_required", models.BooleanField(default=False)),
                ("show_in_picker", models.BooleanField(default=True)),
                ("show_on_label", models.BooleanField(default=False)),
                ("show_on_receipt", models.BooleanField(default=False)),
                ("is_filterable", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "id"],
            },
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_commission_pct",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=5, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_payout_mode",
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_payout_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_reserve_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="stockledgerentry",
            name="voucher_type",
            field=models.CharField(
                choices=[
                    ("sale", "Sale"),
                    ("sale_return", "Sale return"),
                    ("purchase_receipt", "Purchase receipt"),
                    ("purchase_return", "Purchase return"),
                    ("production", "Production"),
                    ("stock_count", "Stock count"),
                    ("adjustment", "Manual adjustment"),
                    ("opening", "Opening balance"),
                    ("transfer", "Warehouse transfer"),
                    ("transfer_receipt", "Warehouse transfer receipt"),
                    ("consignment_cost", "Consignment cost"),
                    ("consignment_intake", "Consignment intake"),
                    ("consignment_return", "Consignment returned to owner"),
                ],
                db_index=True,
                default="adjustment",
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="ConsignmentAgreement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("number", models.CharField(blank=True, max_length=32, unique=True)),
                ("signed_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("expires_on", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "payout_mode",
                    models.CharField(
                        choices=[
                            ("fixed", "Fixed payout"),
                            ("commission", "Commission percentage"),
                        ],
                        default="fixed",
                        max_length=16,
                    ),
                ),
                (
                    "payout_rate",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "commission_pct",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "reserve_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "liability_policy",
                    models.CharField(
                        choices=[
                            ("owner_risk", "الأمانة على مسؤولية صاحبها"),
                            (
                                "shop_liable_except_fm",
                                "المحل ضامن ما عدا الظروف القاهرة",
                            ),
                            ("shop_liable", "المحل ضامن"),
                        ],
                        default="owner_risk",
                        max_length=24,
                    ),
                ),
                (
                    "liability_cap",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("liability_clause", models.TextField(blank=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="inventory.consignmentagreement",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "consignor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignment_agreements",
                        to="customers.customer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignment_agreements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="inventory.consignmentagreement",
                    ),
                ),
            ],
            options={
                "ordering": ["-signed_at", "-id"],
                "permissions": [
                    (
                        "manage_consignmentagreement",
                        "Can write consignment agreements and their payout terms",
                    ),
                    (
                        "disburse_consignment_payout",
                        "Can pay a consignor what a sold consignment owes them",
                    ),
                    (
                        "view_consignment_liability",
                        "Can see consignment payables and open claims",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="stockunit",
            name="agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="units",
                to="inventory.consignmentagreement",
            ),
        ),
        migrations.CreateModel(
            name="ConsignorPayout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                ("number", models.CharField(blank=True, max_length=32, unique=True)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("cash", "Cash from the register"),
                            ("bank", "Bank transfer"),
                        ],
                        default="cash",
                        max_length=16,
                    ),
                ),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("reference", models.CharField(blank=True, max_length=120)),
                ("notes", models.TextField(blank=True)),
                (
                    "amended_from",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_amendments",
                        to="inventory.consignorpayout",
                    ),
                ),
                (
                    "cancelled_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_cancelled",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "cash_movement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignor_payouts",
                        to="sales.registercashmovement",
                    ),
                ),
                (
                    "consignor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignment_payouts",
                        to="customers.customer",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="consignor_payouts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="consignor_payouts",
                        to="sales.registersession",
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_submitted",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "superseded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(app_label)s_%(class)s_supersedes",
                        to="inventory.consignorpayout",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="stockunit",
            name="consignor_payout",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="units",
                to="inventory.consignorpayout",
            ),
        ),
        migrations.AddIndex(
            model_name="stockunit",
            index=models.Index(
                fields=["is_consignment", "status", "consignor_paid_at"],
                name="stockunit_payable_idx",
            ),
        ),
        migrations.AddField(
            model_name="unitattributedefinition",
            name="asset_type",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="unit_attributes",
                to="customers.assettype",
            ),
        ),
        migrations.AddIndex(
            model_name="consignmentagreement",
            index=models.Index(
                fields=["consignor", "-signed_at"], name="consign_party_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consignmentagreement",
            index=models.Index(
                fields=["doc_status", "-signed_at"], name="consign_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consignorpayout",
            index=models.Index(
                fields=["consignor", "-paid_at"], name="payout_party_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="consignorpayout",
            index=models.Index(
                fields=["doc_status", "-paid_at"], name="payout_status_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="unitattributedefinition",
            constraint=models.UniqueConstraint(
                fields=("asset_type", "key"), name="unit_attribute_key_unique"
            ),
        ),
    ]
