# Generated by Django 6.0.2 on 2026-09-18 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0031_seed_unit_attributes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="unitattributedefinition",
            options={
                "ordering": ["display_order", "id"],
                "permissions": [
                    (
                        "manage_unitattributedefinition",
                        "Can define which facts a kind of article records",
                    )
                ],
            },
        ),
    ]
