# Generated by Django 5.2.14 on 2026-10-05 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0040_consignment_payout_reminders"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="stockunit",
            options={
                "ordering": ["-in_stock_since", "-id"],
                "permissions": [
                    ("reprice_stockunit", "Can change an identified unit's price"),
                    ("write_off_stockunit", "Can write off an identified unit"),
                    ("view_stockunit_cost", "Can see what an identified unit cost"),
                    (
                        "manage_stockunit_photos",
                        "Can add, remove and choose the cover of a unit's photos",
                    ),
                    (
                        "change_stockunit_warranty",
                        "Can change the warranty an identified unit is sold with",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="stockunit",
            name="warranty_override_expires_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stockunitevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("repriced", "تغيير السعر"),
                    ("advance_opened", "تحويل مستحق إلى دفعة مقدّمة"),
                    ("advance_settled", "تسوية دفعة مقدّمة"),
                    ("identified", "إدخال المعرّف"),
                    ("identifier_corrected", "تصحيح المعرّف"),
                    ("attributes_edited", "تعديل الخصائص"),
                    ("refurb_cost", "تكلفة تجديد"),
                    ("written_off", "شطب"),
                    ("note", "ملاحظة"),
                    ("incident", "حادث عهدة"),
                    ("counted", "جرد"),
                    ("relocated", "نقل مكان"),
                    ("warranty_changed", "تعديل الضمان"),
                    ("photo_added", "إضافة صورة"),
                    ("photo_removed", "حذف صورة"),
                ],
                max_length=24,
            ),
        ),
    ]
