# Generated by Django 5.2.14 on 2026-10-05 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0041_unit_warranty_override_and_photo_events"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stockunitevent",
            name="kind",
            field=models.CharField(
                choices=[
                    ("repriced", "تغيير السعر"),
                    ("advance_opened", "تحويل مستحق إلى دفعة مقدّمة"),
                    ("advance_settled", "تسوية دفعة مقدّمة"),
                    ("identified", "إدخال المعرّف"),
                    ("identifier_corrected", "تصحيح المعرّف"),
                    ("attributes_edited", "تعديل الخصائص"),
                    ("refurb_cost", "تكلفة تجديد"),
                    ("written_off", "شطب"),
                    ("note", "ملاحظة"),
                    ("incident", "حادث عهدة"),
                    ("counted", "جرد"),
                    ("relocated", "نقل مكان"),
                    ("warranty_changed", "تعديل الضمان"),
                    ("photo_added", "إضافة صورة"),
                    ("photo_removed", "حذف صورة"),
                    ("lot_assigned", "إسناد دفعة"),
                ],
                max_length=24,
            ),
        ),
    ]
