# Generated by Django 5.2.14 on 2026-05-20 15:04

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0002_remove_product_tax_rate"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("customers", "0001_initial"),
        ("purchasing", "0009_purchase_order_workflow_audit_permissions"),
    ]

    operations = [
        migrations.CreateModel(
            name="AppliedDiscount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("rule_name", models.CharField(max_length=160)),
                ("coupon_code", models.CharField(blank=True, max_length=64)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("coupon_code", "Coupon code"),
                        ],
                        default="automatic",
                        max_length=16,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchasing", "Purchasing"),
                            ("both", "Both"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("document", "Document"), ("line", "Line")],
                        max_length=16,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed amount"),
                            ("fixed_unit_amount", "Fixed unit amount"),
                            ("fixed_price", "Fixed price"),
                        ],
                        max_length=24,
                    ),
                ),
                ("value", models.DecimalField(decimal_places=4, max_digits=10)),
                ("priority", models.PositiveIntegerField(default=100)),
                ("exclusive", models.BooleanField(default=False)),
                (
                    "source_subtotal",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "document_object_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "line_object_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                ("allocations", models.JSONField(blank=True, default=list)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "document_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "line_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=160)),
                ("description", models.TextField(blank=True)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchasing", "Purchasing"),
                            ("both", "Both"),
                        ],
                        default="sales",
                        max_length=16,
                    ),
                ),
                (
                    "application_type",
                    models.CharField(
                        choices=[
                            ("automatic", "Automatic"),
                            ("coupon_code", "Coupon code"),
                        ],
                        default="automatic",
                        max_length=16,
                    ),
                ),
                (
                    "coupon_code",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "scope",
                    models.CharField(
                        choices=[("document", "Document"), ("line", "Line")],
                        default="document",
                        max_length=16,
                    ),
                ),
                (
                    "value_type",
                    models.CharField(
                        choices=[
                            ("percentage", "Percentage"),
                            ("fixed_amount", "Fixed amount"),
                            ("fixed_unit_amount", "Fixed unit amount"),
                            ("fixed_price", "Fixed price"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.0001"))
                        ],
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "min_order_subtotal",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "min_line_quantity",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("priority", models.PositiveIntegerField(db_index=True, default=100)),
                ("exclusive", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("starts_at", models.DateTimeField(blank=True, null=True)),
                ("ends_at", models.DateTimeField(blank=True, null=True)),
                ("usage_limit", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "per_customer_usage_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "per_supplier_usage_limit",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discount_rules",
                        to="customers.customer",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True, related_name="discount_rules", to="catalog.product"
                    ),
                ),
                (
                    "suppliers",
                    models.ManyToManyField(
                        blank=True,
                        related_name="discount_rules",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "id"],
            },
        ),
        migrations.CreateModel(
            name="DiscountRedemption",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("coupon_code", models.CharField(blank=True, max_length=64)),
                (
                    "channel",
                    models.CharField(
                        choices=[
                            ("sales", "Sales"),
                            ("purchasing", "Purchasing"),
                            ("both", "Both"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "document_object_id",
                    models.PositiveBigIntegerField(
                        blank=True, db_index=True, null=True
                    ),
                ),
                (
                    "applied_discount",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemption",
                        to="discounts.applieddiscount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_redemptions",
                        to="customers.customer",
                    ),
                ),
                (
                    "document_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="discount_redemptions",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="redemptions",
                        to="discounts.discountrule",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="applieddiscount",
            name="rule",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="applied_discounts",
                to="discounts.discountrule",
            ),
        ),
        migrations.AddConstraint(
            model_name="discountrule",
            constraint=models.UniqueConstraint(
                condition=models.Q(("coupon_code", ""), _negated=True),
                fields=("coupon_code",),
                name="unique_non_blank_discount_coupon_code",
            ),
        ),
        migrations.AddIndex(
            model_name="discountredemption",
            index=models.Index(
                fields=["rule", "customer"], name="discounts_d_rule_id_6a2ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="discountredemption",
            index=models.Index(
                fields=["rule", "supplier"], name="discounts_d_rule_id_494557_idx"
            ),
        ),
    ]
