# Generated by Django 6.0.2 on 2026-05-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_productcategory_product_categories_and_more"),
        ("discounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="product_categories",
            field=models.ManyToManyField(
                blank=True, related_name="discount_rules", to="catalog.productcategory"
            ),
        ),
    ]
