# Generated by Django 5.2.14 on 2026-06-27 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0006_alter_applieddiscount_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="customer_ranks",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
