# Generated by Django 5.2.14 on 2026-06-30 11:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("discounts", "0007_discountrule_customer_ranks"),
    ]

    operations = [
        migrations.AddField(
            model_name="discountrule",
            name="buy_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="get_quantity",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="group_size",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="discountrule",
            name="reward_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("free", "Free"),
                    ("percentage", "Percentage off"),
                    ("fixed_price", "Fixed unit price"),
                ],
                default="",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="applieddiscount",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_amount", "Fixed amount"),
                    ("fixed_unit_amount", "Fixed unit amount"),
                    ("fixed_price", "Fixed price"),
                    ("multi_buy", "Multi-buy (N for price)"),
                    ("tiered", "Tiered unit price"),
                    ("buy_x_get_y", "Buy X get Y"),
                ],
                max_length=24,
            ),
        ),
        migrations.AlterField(
            model_name="discountrule",
            name="value_type",
            field=models.CharField(
                choices=[
                    ("percentage", "Percentage"),
                    ("fixed_amount", "Fixed amount"),
                    ("fixed_unit_amount", "Fixed unit amount"),
                    ("fixed_price", "Fixed price"),
                    ("multi_buy", "Multi-buy (N for price)"),
                    ("tiered", "Tiered unit price"),
                    ("buy_x_get_y", "Buy X get Y"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="DiscountTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "min_quantity",
                    models.PositiveIntegerField(
                        validators=[django.core.validators.MinValueValidator(1)]
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=4,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "rule",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiers",
                        to="discounts.discountrule",
                    ),
                ),
            ],
            options={
                "ordering": ["min_quantity", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("rule", "min_quantity"),
                        name="unique_discount_tier_min_quantity",
                    )
                ],
            },
        ),
    ]
