# Generated by Django 5.2.14 on 2026-09-04 02:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments", "0003_alter_attachment_created_at_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("sales", "0025_alter_order_options_orderexchange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CompanionCaptureRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("till_key", models.CharField(db_index=True, max_length=64)),
                ("prompt", models.CharField(blank=True, max_length=200)),
                (
                    "owner_object_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("role", models.CharField(blank=True, max_length=64)),
                ("is_primary", models.BooleanField(default=False)),
                ("allow_multiple", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("fulfilled", "Fulfilled"),
                            ("cancelled", "Cancelled"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=12,
                    ),
                ),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_capture_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "owner_content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_capture_requests",
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanionDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("till_key", models.CharField(db_index=True, max_length=64)),
                ("token_hash", models.CharField(max_length=64, unique=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("user_agent", models.CharField(blank=True, max_length=255)),
                ("address", models.CharField(blank=True, max_length=64)),
                (
                    "last_seen_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                ("is_paused", models.BooleanField(default=False)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "revoked_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("manual", "Unpaired by staff"),
                            ("session_closed", "Register session closed"),
                            ("idle", "Idle too long"),
                            ("replaced", "Re-paired from the same phone"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "paired_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_devices",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companion_devices",
                        to="sales.registersession",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CompanionEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("till_key", models.CharField(db_index=True, max_length=64)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("scan", "Barcode or QR scan"),
                            ("capture", "Photo"),
                            ("device_state", "Device connected, paused or left"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "attachment",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="companion_events",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "capture_request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="companion.companioncapturerequest",
                    ),
                ),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="companion.companiondevice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="CompanionPairing",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code_hash", models.CharField(max_length=64, unique=True)),
                ("till_key", models.CharField(db_index=True, max_length=64)),
                ("till_label", models.CharField(blank=True, max_length=120)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "claimed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="claimed_pairings",
                        to="companion.companiondevice",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="companion_pairings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="companioncapturerequest",
            index=models.Index(
                fields=["till_key", "status", "-created_at"],
                name="companion_c_till_ke_d352e6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="companiondevice",
            index=models.Index(
                fields=["till_key", "revoked_at"], name="companion_c_till_ke_d4f766_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="companionevent",
            index=models.Index(
                fields=["till_key", "id"], name="companion_c_till_ke_0fe45f_idx"
            ),
        ),
    ]
