# Generated by Django 5.2.14 on 2026-10-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("companion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="companioncapturerequest",
            name="accept_documents",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
