#!/usr/bin/env python3
"""Bakes every country flag into the client: assets/flags/<code>.png + bundled_flags.dart.

    python3 tool/bake_flags.py [path/to/ops/catalog/flags]

The source is the operator's prepared set (ops/catalog/flags, 192x128, built by
ops/catalog/tools/build_flags.py from the relay's own country table). Each flag is
shrunk to 96x64: the largest chip the till draws is 36x24, so this stays sharp up
to a 2.5x screen while keeping the whole set small. Re-run after the set changes.
"""
import os
import sys

from PIL import Image

FRONTEND = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEFAULT_SOURCE = os.path.join(os.path.dirname(FRONTEND), "ops", "catalog", "flags")
OUT = os.path.join(FRONTEND, "assets", "flags")
DART = os.path.join(FRONTEND, "lib", "src", "shared", "flags", "bundled_flags.dart")
W, H = 96, 64


def main(source):
    codes = sorted(
        name[:-4]
        for name in os.listdir(source)
        if name.endswith(".png") and len(name) == 6 and not name.startswith(".")
    )
    if not codes:
        sys.exit(f"no flags in {source}")
    os.makedirs(OUT, exist_ok=True)
    for stale in os.listdir(OUT):
        if stale.endswith(".png") and stale[:-4] not in codes:
            os.remove(os.path.join(OUT, stale))
    for code in codes:
        flag = Image.open(os.path.join(source, code + ".png")).convert("RGBA")
        flag.resize((W, H), Image.LANCZOS).save(os.path.join(OUT, code + ".png"), optimize=True)

    listed = "\n".join(f"  '{code.upper()}'," for code in codes)
    os.makedirs(os.path.dirname(DART), exist_ok=True)
    with open(DART, "w", encoding="utf-8") as out:
        out.write(
            "// GENERATED by tool/bake_flags.py - do not edit by hand.\n\n"
            "/// The ISO codes (plus EU and WW, a card that redeems anywhere) whose flag\n"
            "/// ships inside the app as `assets/flags/<code>.png`.\n"
            f"const Set<String> bundledFlagCodes = {{\n{listed}\n}};\n\n"
            "/// The asset a [bundledFlagCodes] entry is drawn from.\n"
            "String bundledFlagAsset(String code) =>\n"
            "    'assets/flags/${code.toLowerCase()}.png';\n"
        )
    print(f"baked {len(codes)} flags into {os.path.relpath(OUT, FRONTEND)}")


if __name__ == "__main__":
    main(sys.argv[1] if len(sys.argv) > 1 else DEFAULT_SOURCE)
