# Generated by Django 5.2.14 on 2026-06-13 01:32

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        (
            "employees",
            "0005_alter_payrolladjustment_adjustment_type_employeeloan_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BioTimeConnection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("base_url", models.URLField(blank=True)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("is_enabled", models.BooleanField(default=False)),
                ("workdays", models.CharField(default="6,0,1,2,3", max_length=32)),
                ("shift_start", models.TimeField(default="09:00")),
                ("shift_end", models.TimeField(default="17:00")),
                (
                    "grace_minutes",
                    models.PositiveSmallIntegerField(
                        default=15,
                        validators=[django.core.validators.MaxValueValidator(240)],
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "last_sync_status",
                    models.CharField(
                        choices=[
                            ("never", "Never synced"),
                            ("ok", "Last sync succeeded"),
                            ("error", "Last sync failed"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_sync_error", models.TextField(blank=True)),
                ("last_punch_cursor", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "BioTime connection",
            },
        ),
        migrations.CreateModel(
            name="AttendanceDay",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("date", models.DateField(db_index=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("present", "Present"),
                            ("late", "Late"),
                            ("partial", "Missing punch"),
                            ("day_off", "Day off"),
                        ],
                        max_length=16,
                    ),
                ),
                ("first_in", models.DateTimeField(blank=True, null=True)),
                ("last_out", models.DateTimeField(blank=True, null=True)),
                ("punch_count", models.PositiveSmallIntegerField(default=0)),
                ("worked_minutes", models.PositiveIntegerField(default=0)),
                ("late_minutes", models.PositiveIntegerField(default=0)),
                ("early_leave_minutes", models.PositiveIntegerField(default=0)),
                ("overtime_minutes", models.PositiveIntegerField(default=0)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_days",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-date", "employee__full_name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "date"),
                        name="unique_attendance_day_per_employee",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendanceProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("biotime_emp_code", models.CharField(blank=True, max_length=32)),
                ("biotime_full_name", models.CharField(blank=True, max_length=255)),
                ("is_tracked", models.BooleanField(default=True)),
                ("shift_start", models.TimeField(blank=True, null=True)),
                ("shift_end", models.TimeField(blank=True, null=True)),
                ("workdays", models.CharField(blank=True, max_length=32)),
                (
                    "grace_minutes",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[django.core.validators.MaxValueValidator(240)],
                    ),
                ),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_profile",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__full_name", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("biotime_emp_code", ""), _negated=True),
                        fields=("biotime_emp_code",),
                        name="unique_biotime_emp_code",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="AttendancePunch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "biotime_id",
                    models.BigIntegerField(blank=True, null=True, unique=True),
                ),
                ("emp_code", models.CharField(db_index=True, max_length=32)),
                ("punch_time", models.DateTimeField(db_index=True)),
                ("punch_state", models.CharField(blank=True, max_length=16)),
                ("terminal", models.CharField(blank=True, max_length=120)),
                (
                    "source",
                    models.CharField(
                        choices=[("biotime", "BioTime"), ("manual", "Manual")],
                        default="biotime",
                        max_length=16,
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_punches",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["punch_time", "id"],
                "indexes": [
                    models.Index(
                        fields=["employee", "punch_time"],
                        name="attendance__employe_d7dad5_idx",
                    )
                ],
            },
        ),
    ]
