# Generated by Django 5.2.14 on 2026-09-01 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_alter_attendanceday_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biotimeconnection",
            name="first_punch_cursor",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biotimeconnection",
            name="sync_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
