# Generated by Django 5.2.14 on 2026-09-01 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0003_biotimeconnection_first_punch_cursor_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="biotimeconnection",
            name="sync_heartbeat_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="biotimeconnection",
            name="sync_progress_punches",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="biotimeconnection",
            name="sync_started_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="biotimeconnection",
            name="last_sync_status",
            field=models.CharField(
                choices=[
                    ("never", "Never synced"),
                    ("ok", "Last sync succeeded"),
                    ("error", "Last sync failed"),
                    ("running", "Sync in progress"),
                ],
                default="never",
                max_length=16,
            ),
        ),
    ]
