# Generated by Django 5.2.14 on 2026-09-07 04:57

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Recorder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("auto", "Detect automatically"),
                            ("hikvision", "Hikvision"),
                            ("dahua", "Dahua"),
                        ],
                        default="auto",
                        max_length=16,
                    ),
                ),
                ("detected_brand", models.CharField(blank=True, max_length=16)),
                ("host", models.CharField(max_length=120)),
                (
                    "port",
                    models.PositiveIntegerField(
                        default=80,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                (
                    "rtsp_port",
                    models.PositiveIntegerField(
                        default=554,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(65535),
                        ],
                    ),
                ),
                ("username", models.CharField(blank=True, max_length=120)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("use_https", models.BooleanField(default=False)),
                ("is_enabled", models.BooleanField(default=True)),
                ("model_name", models.CharField(blank=True, max_length=120)),
                ("firmware", models.CharField(blank=True, max_length=120)),
                ("serial_number", models.CharField(blank=True, max_length=120)),
                ("channel_count", models.PositiveSmallIntegerField(default=0)),
                ("clock_offset_minutes", models.SmallIntegerField(default=0)),
                ("clock_offset_is_measured", models.BooleanField(default=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("never", "Never connected"),
                            ("ok", "Connected"),
                            ("error", "Last attempt failed"),
                        ],
                        default="never",
                        max_length=16,
                    ),
                ),
                ("last_error", models.TextField(blank=True)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name", "host"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("host", "port"), name="unique_recorder_endpoint"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Camera",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.PositiveSmallIntegerField()),
                ("name", models.CharField(blank=True, max_length=120)),
                ("device_name", models.CharField(blank=True, max_length=120)),
                ("is_enabled", models.BooleanField(default=True)),
                ("display_order", models.PositiveSmallIntegerField(default=0)),
                ("covers_checkout", models.BooleanField(default=False)),
                (
                    "live_quality",
                    models.CharField(
                        choices=[("main", "main"), ("sub", "sub")],
                        default="sub",
                        max_length=8,
                    ),
                ),
                (
                    "playback_quality",
                    models.CharField(
                        choices=[("main", "main"), ("sub", "sub")],
                        default="main",
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("unknown", "Not checked"),
                            ("online", "Online"),
                            ("offline", "Offline"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_frame_at", models.DateTimeField(blank=True, null=True)),
                (
                    "recorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cameras",
                        to="surveillance.recorder",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "channel", "id"],
                "permissions": [
                    ("view_live", "Can watch live camera streams"),
                    ("view_playback", "Can watch recorded footage"),
                    ("export_footage", "Can export video clips"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("recorder", "channel"),
                        name="unique_camera_channel_per_recorder",
                    )
                ],
            },
        ),
    ]
