# Generated by Django 5.2.14 on 2026-09-08 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="recorder",
            name="onvif_service_path",
            field=models.CharField(blank=True, db_default="", max_length=120),
        ),
        migrations.AddField(
            model_name="recorder",
            name="rtsp_path_template",
            field=models.CharField(blank=True, db_default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="recorder",
            name="brand",
            field=models.CharField(
                choices=[
                    ("auto", "Detect automatically"),
                    ("hikvision", "Hikvision"),
                    ("dahua", "Dahua"),
                    ("xiongmai", "Xiongmai / XMEye"),
                    ("onvif", "ONVIF (other brands)"),
                    ("generic_rtsp", "Direct RTSP (live view only)"),
                ],
                default="auto",
                max_length=16,
            ),
        ),
    ]
