# Generated by Django 6.0.2 on 2026-09-16 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0002_recorder_onvif_xiongmai_and_direct_rtsp"),
    ]

    operations = [
        migrations.AddField(
            model_name="recorder",
            name="max_concurrent_streams",
            field=models.PositiveSmallIntegerField(
                blank=True, db_default=None, null=True
            ),
        ),
    ]
