# Generated by Django 5.2.14 on 2026-09-27 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("surveillance", "0004_camera_audio"),
    ]

    operations = [
        migrations.CreateModel(
            name="FootageClip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[("video", "Video"), ("picture", "Picture")],
                        max_length=8,
                    ),
                ),
                ("start", models.DateTimeField()),
                ("end", models.DateTimeField()),
                ("path", models.CharField(max_length=512, unique=True)),
                ("size_bytes", models.BigIntegerField(default=0)),
            ],
            options={
                "ordering": ["start", "id"],
            },
        ),
        migrations.CreateModel(
            name="FootageUpload",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=1024)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("video", "Video"),
                            ("picture", "Picture"),
                            ("other", "Other"),
                        ],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Waiting for its decision time"),
                            ("claimed", "Being processed"),
                        ],
                        default="pending",
                        max_length=8,
                    ),
                ),
                ("complete", models.BooleanField(default=True)),
                ("size_bytes", models.BigIntegerField(default=0)),
                ("received_at", models.DateTimeField()),
                ("transfer_seconds", models.FloatField(default=0)),
                ("peer", models.CharField(blank=True, max_length=64)),
                ("source_key", models.CharField(blank=True, max_length=160)),
                ("source_label", models.CharField(blank=True, max_length=120)),
                ("channel", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("wall_start", models.DateTimeField(blank=True, null=True)),
                ("wall_end", models.DateTimeField(blank=True, null=True)),
                ("decide_after", models.DateTimeField()),
                ("claim_token", models.CharField(blank=True, max_length=32)),
                ("claimed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("error", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="FtpAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("username", models.CharField(max_length=32, unique=True)),
                ("password", models.CharField(max_length=64)),
                ("advertised_host", models.CharField(blank=True, max_length=64)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("last_login_peer", models.CharField(blank=True, max_length=64)),
                ("last_upload_at", models.DateTimeField(blank=True, null=True)),
                ("last_upload_peer", models.CharField(blank=True, max_length=64)),
                ("last_upload_name", models.CharField(blank=True, max_length=255)),
                ("failed_login_count", models.PositiveIntegerField(default=0)),
                ("failed_login_at", models.DateTimeField(blank=True, null=True)),
                ("failed_login_peer", models.CharField(blank=True, max_length=64)),
                ("files_received", models.BigIntegerField(default=0)),
                ("bytes_received", models.BigIntegerField(default=0)),
                ("files_kept", models.BigIntegerField(default=0)),
                ("files_discarded", models.BigIntegerField(default=0)),
                ("files_unreadable", models.BigIntegerField(default=0)),
                ("last_ingest_error", models.TextField(blank=True)),
                ("last_ingest_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "clock_lower_minutes",
                    models.SmallIntegerField(blank=True, null=True),
                ),
                ("clock_lower_since", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveConstraint(
            model_name="recorder",
            name="unique_recorder_endpoint",
        ),
        migrations.AddField(
            model_name="camera",
            name="source_key",
            field=models.CharField(blank=True, db_default="", max_length=160),
        ),
        migrations.AddField(
            model_name="recorder",
            name="connection",
            field=models.CharField(
                choices=[("direct", "Direct connection"), ("ftp", "FTP upload")],
                db_default="direct",
                default="direct",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="recorder",
            name="host",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddConstraint(
            model_name="camera",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_key", ""), _negated=True),
                fields=("recorder", "source_key"),
                name="unique_camera_source_per_recorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="recorder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("connection", "direct")),
                fields=("host", "port"),
                name="unique_recorder_endpoint",
            ),
        ),
        migrations.AddField(
            model_name="footageclip",
            name="camera",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footage_clips",
                to="surveillance.camera",
            ),
        ),
        migrations.AddField(
            model_name="footageupload",
            name="recorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="footage_uploads",
                to="surveillance.recorder",
            ),
        ),
        migrations.AddField(
            model_name="ftpaccount",
            name="recorder",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ftp_account",
                to="surveillance.recorder",
            ),
        ),
        migrations.AddIndex(
            model_name="footageclip",
            index=models.Index(
                fields=["camera", "start"], name="surv_clip_camera_start_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="footageclip",
            index=models.Index(fields=["end"], name="surv_clip_end_idx"),
        ),
        migrations.AddIndex(
            model_name="footageupload",
            index=models.Index(
                fields=["status", "decide_after"], name="surv_upload_due_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="footageupload",
            constraint=models.UniqueConstraint(
                fields=("recorder", "path"), name="unique_footage_upload_path"
            ),
        ),
    ]
