# Generated by Django 5.2.14 on 2026-06-01 15:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BusinessNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(db_index=True, max_length=80)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("inventory", "Inventory"),
                            ("purchasing", "Purchasing"),
                            ("printing", "Printing"),
                            ("sales", "Sales"),
                            ("discounts", "Discounts"),
                            ("operations", "Operations"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("resolved", "Resolved")],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                ("fingerprint", models.CharField(max_length=180, unique=True)),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                ("payload", models.JSONField(blank=True, default=dict)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["status", "-last_seen_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity", "last_seen_at"],
                        name="notificatio_status_294629_idx",
                    ),
                    models.Index(
                        fields=["category", "status"],
                        name="notificatio_categor_d6a7f5_idx",
                    ),
                    models.Index(
                        fields=["code", "status"], name="notificatio_code_dbcb0f_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BusinessNotificationUserState",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("snoozed_until", models.DateTimeField(blank=True, null=True)),
                (
                    "notification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_states",
                        to="notifications.businessnotification",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="business_notification_states",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user", "acknowledged_at"],
                        name="notificatio_user_id_b552ab_idx",
                    ),
                    models.Index(
                        fields=["user", "snoozed_until"],
                        name="notificatio_user_id_04c338_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("notification", "user"),
                        name="unique_business_notification_user_state",
                    )
                ],
            },
        ),
    ]
