# Generated by Django 5.2.14 on 2026-06-05 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessnotification",
            name="category",
            field=models.CharField(
                choices=[
                    ("inventory", "Inventory"),
                    ("purchasing", "Purchasing"),
                    ("printing", "Printing"),
                    ("sales", "Sales"),
                    ("fraud", "Fraud"),
                    ("discounts", "Discounts"),
                    ("operations", "Operations"),
                ],
                db_index=True,
                max_length=32,
            ),
        ),
    ]
