# Generated by Django 6.0.2 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0002_alter_businessnotification_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="businessnotification",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="businessnotificationuserstate",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
