# Generated by Django 5.2.14 on 2026-06-16 15:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0012_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PriceCheckerDevice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("identifier", models.SlugField(max_length=80, unique=True)),
                ("name", models.CharField(max_length=120)),
                ("driver", models.CharField(max_length=64)),
                ("make", models.CharField(blank=True, max_length=80)),
                ("model", models.CharField(blank=True, max_length=80)),
                (
                    "transport",
                    models.CharField(
                        choices=[
                            ("http", "HTTP / web kiosk"),
                            ("tcp", "Raw TCP socket"),
                            ("udp", "UDP datagram"),
                        ],
                        default="http",
                        max_length=8,
                    ),
                ),
                ("address", models.GenericIPAddressField(blank=True, null=True)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "mac_address",
                    models.CharField(blank=True, db_index=True, max_length=17),
                ),
                ("display_rows", models.PositiveSmallIntegerField(default=5)),
                ("display_cols", models.PositiveSmallIntegerField(default=20)),
                (
                    "arabic_support",
                    models.CharField(
                        choices=[
                            ("none", "None (Latin fallback)"),
                            ("unicode", "Unicode (device shapes)"),
                            ("cp1256", "CP1256 (server reorders)"),
                            ("glyphs", "Pre-shaped glyphs (server shapes)"),
                        ],
                        default="unicode",
                        max_length=8,
                    ),
                ),
                ("encoding", models.CharField(default="utf-8", max_length=24)),
                ("location", models.CharField(blank=True, max_length=120)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("discovered", "Discovered"),
                            ("active", "Active"),
                            ("disabled", "Disabled"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=12,
                    ),
                ),
                (
                    "discovery_method",
                    models.CharField(
                        choices=[
                            ("manual", "Added manually"),
                            ("scan", "Found by network scan"),
                            ("self", "Self-registered on first contact"),
                        ],
                        default="manual",
                        max_length=8,
                    ),
                ),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("settings", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "ordering": ["name", "identifier"],
            },
        ),
        migrations.CreateModel(
            name="PriceCheckEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "device_identifier",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                ("barcode", models.CharField(db_index=True, max_length=64)),
                (
                    "result",
                    models.CharField(
                        choices=[
                            ("found", "Found"),
                            ("not_found", "Not found"),
                            ("error", "Error"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                ("product_name", models.CharField(blank=True, max_length=255)),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "final_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "discount_total",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("currency", models.CharField(blank=True, max_length=16)),
                ("response_text", models.TextField(blank=True)),
                ("source_address", models.CharField(blank=True, max_length=64)),
                ("latency_ms", models.PositiveIntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "device",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="events",
                        to="price_checker.pricecheckerdevice",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="price_check_events",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["result", "-created_at"],
                        name="price_check_result_09df68_idx",
                    ),
                    models.Index(
                        fields=["barcode", "-created_at"],
                        name="price_check_barcode_7c73c5_idx",
                    ),
                ],
            },
        ),
    ]
