# Generated by Django 5.2.14 on 2026-06-12 23:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0002_seed_default_workflows"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobmaterial",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
