# Generated by Django 5.2.14 on 2026-06-13 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_compensationplan_overtime_multiplier_and_more"),
        ("operations", "0003_alter_jobmaterial_quantity"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_jobs",
                to="employees.employee",
            ),
        ),
    ]
