# Generated by Django 5.2.14 on 2026-06-29 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_product_product_name_live_idx"),
        ("channels", "0003_alter_saleschannel_created_at"),
        (
            "customers",
            "0005_customer_rfm_calculated_at_customer_rfm_frequency_and_more",
        ),
        ("employees", "0009_alter_compensationplan_created_at_and_more"),
        ("operations", "0005_alter_job_created_at_alter_jobasset_created_at_and_more"),
        ("sales", "0025_alter_order_options_orderexchange"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="job",
            index=models.Index(
                fields=["status", "-created_at"], name="job_status_created_idx"
            ),
        ),
    ]
