# Generated by Django 6.0.2 on 2026-09-18 07:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0030_phase_c_consignment"),
        ("operations", "0007_job_settlement_custody_hold_and_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="capitalised_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="capitalised_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="job",
            name="stock_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="refurb_jobs",
                to="inventory.stockunit",
            ),
        ),
    ]
