# Generated by Django 5.2.14 on 2026-09-24 01:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("operations", "0009_job_material_names_its_article"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="cancel_note",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AddField(
            model_name="job",
            name="cancel_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("price", "Declined: price"),
                    ("declined", "Declined: another reason"),
                    ("cannot_repair", "Cannot be repaired"),
                    ("no_response", "Customer did not respond"),
                ],
                db_default="",
                default="",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="decline_fee",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
