# Generated by Django 5.2.14 on 2026-06-02 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_shopsettings_prevent_selling_at_loss"),
    ]

    operations = [
        migrations.CreateModel(
            name="RelayInstallation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("installation_id", models.CharField(max_length=80, unique=True)),
                ("shop_name", models.CharField(blank=True, max_length=120)),
                ("relay_public_api_url", models.URLField(max_length=500)),
                (
                    "relay_connector_address",
                    models.CharField(blank=True, max_length=255),
                ),
                ("connector_token", models.TextField()),
                ("access_token", models.TextField()),
                ("relay_enabled", models.BooleanField(default=False)),
                ("subscription_active", models.BooleanField(default=False)),
                ("ai_enabled", models.BooleanField(default=False)),
                ("subscription_ends_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                ("last_pairing_issued_at", models.DateTimeField(blank=True, null=True)),
                ("connector_last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("connector_version", models.CharField(blank=True, max_length=80)),
            ],
            options={
                "verbose_name": "relay installation",
                "verbose_name_plural": "relay installations",
            },
        ),
    ]
