# Generated by Django 5.2.14 on 2026-06-09 01:12

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0009_idempotencyrecord"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemBackupSchedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("enabled", models.BooleanField(default=False)),
                ("destination_path", models.CharField(blank=True, max_length=1024)),
                ("scheduled_time", models.TimeField(default=datetime.time(2, 0))),
                (
                    "retention_count",
                    models.PositiveSmallIntegerField(
                        default=7,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("last_scheduled_backup_date", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name": "system backup schedule",
                "verbose_name_plural": "system backup schedules",
            },
        ),
        migrations.CreateModel(
            name="SystemMaintenanceJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "operation",
                    models.CharField(
                        choices=[("backup", "Backup"), ("restore", "Restore")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("progress_message", models.CharField(blank=True, max_length=240)),
                ("destination_path", models.CharField(blank=True, max_length=1024)),
                ("backup_file_name", models.CharField(blank=True, max_length=255)),
                ("backup_file_path", models.CharField(blank=True, max_length=1024)),
                ("archive_size_bytes", models.PositiveBigIntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("initiated_by_user_id", models.PositiveBigIntegerField(blank=True, null=True)),
                ("initiated_by_username", models.CharField(blank=True, max_length=150)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["operation", "status", "-created_at"],
                        name="core_system_operati_b57ae5_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="core_system_status_74d190_idx",
                    ),
                ],
            },
        ),
    ]
