# Generated by Django 5.2.14 on 2026-06-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0011_shopsettings_enable_online_invoices"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="enable_job_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enable_kitchen_operations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enable_production_operations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enable_repair_operations",
            field=models.BooleanField(default=False),
        ),
    ]
