# Generated by Django 5.2.14 on 2026-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0012_shopsettings_enable_job_tracking_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="auto_print_kitchen_tickets",
            field=models.BooleanField(default=False),
        ),
    ]
