# Generated by Django 5.2.14 on 2026-06-15 00:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0013_shopsettings_auto_print_kitchen_tickets"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="stock_count_variance_min_units",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="stock_count_variance_percent",
            field=models.DecimalField(
                decimal_places=2,
                default=10,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
