# Generated by Django 5.2.14 on 2026-06-15 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0014_shopsettings_stock_count_variance_min_units_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="kitchen_auto_complete",
            field=models.BooleanField(default=True),
        ),
    ]
