# Generated by Django 5.2.14 on 2026-06-18 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0015_shopsettings_kitchen_auto_complete"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="shop_type",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
    ]
