# Generated by Django 5.2.14 on 2026-06-18 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0017_alter_idempotencyrecord_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="currency_code",
            field=models.CharField(default="LYD", max_length=8),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="currency_symbol",
            field=models.CharField(default="د.ل", max_length=8),
        ),
    ]
