# Generated by Django 5.2.14 on 2026-06-23 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0018_shopsettings_currency_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="require_customer_for_credit",
            field=models.BooleanField(default=True),
        ),
    ]
