# Generated by Django 6.0.2 on 2026-06-23 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0019_shopsettings_require_customer_for_credit"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="allow_cashier_customer_access",
            field=models.BooleanField(default=True),
        ),
    ]
