# Generated by Django 5.2.14 on 2026-07-07 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0020_shopsettings_allow_cashier_customer_access"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="warn_low_stock_before_sale",
            field=models.BooleanField(default=True),
        ),
    ]
