# Generated by Django 5.2.14 on 2026-07-22 01:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0021_shopsettings_warn_low_stock_before_sale"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="pos_cash_purchase_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
