# Generated by Django 5.2.14 on 2026-08-26 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0022_shopsettings_pos_cash_purchase_limit"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="inventory_valuation_method",
            field=models.CharField(
                choices=[
                    ("moving_average", "Moving average"),
                    ("fifo", "First in, first out (FIFO)"),
                    ("lifo", "Last in, first out (LIFO)"),
                ],
                default="moving_average",
                max_length=20,
            ),
        ),
    ]
