# Generated by Django 5.2.14 on 2026-08-31 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0023_shopsettings_inventory_valuation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="fx_bank_code",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fx_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fx_instrument",
            field=models.CharField(
                choices=[("cash", "Cash"), ("bank", "Bank transfer")],
                default="cash",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fx_manual_only",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fx_rate_staleness_hours",
            field=models.PositiveIntegerField(default=24),
        ),
    ]
