# Generated by Django 6.0.2 on 2026-09-01 18:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0024_shopsettings_fx_bank_code_shopsettings_fx_enabled_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="books_locked_through",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="fiscal_year_start_month",
            field=models.PositiveSmallIntegerField(
                default=1,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(12),
                ],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="month_end_report_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="month_end_snapshot_day",
            field=models.PositiveSmallIntegerField(
                default=1, validators=[django.core.validators.MaxValueValidator(28)]
            ),
        ),
    ]
