# Generated by Django 6.0.2 on 2026-09-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0025_accounting_calendar"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="enable_purchase_suggestions",
            field=models.BooleanField(default=True),
        ),
    ]
