# Generated by Django 5.2.14 on 2026-09-05 00:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0026_shopsettings_enable_purchase_suggestions"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="default_customer_credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enforce_customer_credit_limits",
            field=models.BooleanField(default=False),
        ),
    ]
