# Generated by Django 5.2.14 on 2026-09-07 04:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0028_alter_shopsettings_enforce_customer_credit_limits"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="enable_surveillance",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="surveillance_post_roll_seconds",
            field=models.PositiveSmallIntegerField(
                default=40, validators=[django.core.validators.MaxValueValidator(600)]
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="surveillance_pre_roll_seconds",
            field=models.PositiveSmallIntegerField(
                default=20, validators=[django.core.validators.MaxValueValidator(600)]
            ),
        ),
    ]
