# Generated by Django 6.0.2 on 2026-09-10 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0030_surveillance_roll_db_defaults"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="default_payment_terms_basis",
            field=models.CharField(
                choices=[
                    ("net_days", "Days after the invoice"),
                    ("end_of_month", "Days after the end of the invoice month"),
                ],
                db_default="net_days",
                default="net_days",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="default_payment_terms_days",
            field=models.PositiveIntegerField(
                db_default=0,
                default=0,
                validators=[django.core.validators.MaxValueValidator(730)],
            ),
        ),
    ]
