# Generated by Django 5.2.14 on 2026-09-15 14:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0031_shopsettings_default_payment_terms_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="auto_print_min_line_count",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="auto_print_min_total",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
