# Generated by Django 5.2.14 on 2026-09-17 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0032_shopsettings_auto_print_min_line_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="batch_auto_pick_strategy",
            field=models.CharField(
                choices=[
                    ("fefo", "First expiring, first out"),
                    ("fifo", "First in, first out"),
                ],
                default="fefo",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="default_expiry_warning_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enable_batch_tracking",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="enable_serialized_inventory",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="prevent_selling_expired_batches",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="serialized_capture_later_allowed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="serialized_require_customer_for_asset",
            field=models.BooleanField(default=True),
        ),
    ]
