# Generated by Django 6.0.2 on 2026-09-18 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0033_identified_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_auto_sms_on_sale",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_clause_owner_risk",
            field=models.TextField(
                blank=True,
                default="الأمانة على مسؤولية صاحبها، والمحل غير مسؤول عن أي تلف أو فقدان.",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_clause_shop_liable",
            field=models.TextField(
                blank=True, default="المحل ضامن للأمانة حتى تسليمها لصاحبها أو بيعها."
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_clause_shop_liable_except_fm",
            field=models.TextField(
                blank=True,
                default="المحل ضامن للأمانة ما عدا الظروف القاهرة من حريق أو فيضان أو اضطرابات.",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_default_liability_policy",
            field=models.CharField(
                choices=[
                    ("owner_risk", "الأمانة على مسؤولية صاحبها"),
                    ("shop_liable_except_fm", "المحل ضامن ما عدا الظروف القاهرة"),
                    ("shop_liable", "المحل ضامن"),
                ],
                default="owner_risk",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_require_declared_value",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_sale_sms_template",
            field=models.TextField(
                blank=True,
                default="مرحباً {consignor_name}،\nتم بحمد الله بيع أمانتكم ({product_name} - رقم: {code}) بالفاتورة رقم #{invoice_number}.\nالمبلغ الصافي المستحق لكم: {payout_amount} د.ل.\nنرجو التفضل بزيارة المحل لاستلام المبلغ.\nشكراً لثقتكم بنا.",
            ),
        ),
        migrations.AddField(
            model_name="shopsettings",
            name="consignment_unclaimed_payout_reminder_days",
            field=models.PositiveIntegerField(default=30),
        ),
    ]
