# Generated by Django 5.2.14 on 2026-09-19 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0034_phase_c_consignment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="shop_phone",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
