# Generated by Django 5.2.14 on 2026-09-22 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0035_shopsettings_shop_phone"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="max_invoice_discount_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
    ]
