# Generated by Django 5.2.14 on 2026-09-26 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0037_shopsettings_repair_ticket"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="print_voucher_qr_codes",
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
