# Generated by Django 5.2.14 on 2026-09-27 00:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0038_shopsettings_print_voucher_qr_codes"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayinstallation",
            name="sms_enabled",
            field=models.BooleanField(db_default=False, default=False),
        ),
    ]
