# Generated by Django 5.2.14 on 2026-09-27 18:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0039_relayinstallation_sms_enabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="shopsettings",
            name="surveillance_archive_retention_days",
            field=models.PositiveSmallIntegerField(
                db_default=30,
                default=30,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(3650),
                ],
            ),
        ),
    ]
