# Generated by Django 5.2.14 on 2026-09-29 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0040_shopsettings_surveillance_archive_retention_days"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayinstallation",
            name="integrations_disabled",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
    ]
