# Generated by Django 5.2.14 on 2026-10-01 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0041_relayinstallation_integrations_disabled"),
    ]

    operations = [
        migrations.AddField(
            model_name="relayinstallation",
            name="ai_paid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relayinstallation",
            name="remote_access_paid_until",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="relayinstallation",
            name="sms_balance",
            field=models.DecimalField(
                db_default=0, decimal_places=3, default=0, max_digits=14
            ),
        ),
        migrations.AddField(
            model_name="relayinstallation",
            name="sms_price",
            field=models.DecimalField(
                db_default=0, decimal_places=3, default=0, max_digits=8
            ),
        ),
    ]
