# Generated by Django 5.2.14 on 2026-07-01 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MessagingGateway",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("sms_gate", "SMS Gate (Android)"),
                            ("fake", "Fake (testing)"),
                        ],
                        default="sms_gate",
                        max_length=32,
                    ),
                ),
                (
                    "channel",
                    models.CharField(
                        choices=[("sms", "SMS")], default="sms", max_length=16
                    ),
                ),
                ("config", models.JSONField(blank=True, default=dict)),
                ("secrets_encrypted", models.TextField(blank=True, editable=False)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("max_messages_per_minute", models.PositiveIntegerField(default=6)),
                ("daily_cap", models.PositiveIntegerField(default=0)),
                ("quiet_hours_start", models.TimeField(blank=True, null=True)),
                ("quiet_hours_end", models.TimeField(blank=True, null=True)),
                ("send_timeout_seconds", models.PositiveIntegerField(default=15)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["name"],
                "permissions": [
                    (
                        "manage_gateways",
                        "Can configure messaging gateways and send tests",
                    ),
                    ("view_logs", "Can view messaging send/receive logs"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_default", True)),
                        fields=("is_default",),
                        name="unique_default_messaging_gateway",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OutboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(default="sms", max_length=16)),
                ("to_phone", models.CharField(db_index=True, max_length=32)),
                ("to_phone_raw", models.CharField(blank=True, max_length=64)),
                ("body", models.TextField()),
                (
                    "consent_class",
                    models.CharField(
                        choices=[
                            ("transactional", "Transactional"),
                            ("marketing", "Marketing"),
                        ],
                        default="transactional",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("scheduled", "Scheduled"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                            ("blocked_consent", "Blocked (consent)"),
                            ("expired", "Expired"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=20,
                    ),
                ),
                ("segments", models.PositiveSmallIntegerField(default=1)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("attempts", models.PositiveSmallIntegerField(default=0)),
                ("max_attempts", models.PositiveSmallIntegerField(default=3)),
                ("next_attempt_at", models.DateTimeField(blank=True, null=True)),
                ("not_before", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "dedup_key",
                    models.CharField(
                        blank=True, max_length=180, null=True, unique=True
                    ),
                ),
                ("error_code", models.CharField(blank=True, max_length=48)),
                ("error_detail", models.TextField(blank=True)),
                ("source_type", models.CharField(blank=True, max_length=40)),
                ("source_id", models.CharField(blank=True, max_length=64)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="outbound_messages",
                        to="messaging.messaginggateway",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["status", "next_attempt_at"],
                        name="messaging_o_status_e4c004_idx",
                    ),
                    models.Index(
                        fields=["gateway", "status"],
                        name="messaging_o_gateway_771c0b_idx",
                    ),
                    models.Index(
                        fields=["source_type", "source_id"],
                        name="messaging_o_source__2c638c_idx",
                    ),
                ],
            },
        ),
    ]
