# Generated by Django 5.2.14 on 2026-07-01 02:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DeliveryReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=128),
                ),
                ("status", models.CharField(blank=True, max_length=32)),
                ("raw", models.JSONField(blank=True, default=dict)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delivery_receipts",
                        to="messaging.messaginggateway",
                    ),
                ),
                (
                    "outbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="receipts",
                        to="messaging.outboundmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InboundMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("channel", models.CharField(default="sms", max_length=16)),
                ("from_phone", models.CharField(db_index=True, max_length=32)),
                ("from_phone_raw", models.CharField(blank=True, max_length=64)),
                ("body", models.TextField(blank=True)),
                ("provider_message_id", models.CharField(blank=True, max_length=128)),
                ("received_at", models.DateTimeField(blank=True, null=True)),
                ("handled", models.BooleanField(default=False)),
                (
                    "handled_as",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unhandled"),
                            ("conversation", "Conversation"),
                            ("consent_command", "Consent command"),
                            ("staff_command", "Staff command"),
                            ("ignored", "Ignored"),
                        ],
                        default="",
                        max_length=20,
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="inbound_messages",
                        to="messaging.messaginggateway",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["from_phone", "-created_at"],
                        name="messaging_i_from_ph_87c510_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("provider_message_id", ""), _negated=True),
                        fields=("gateway", "provider_message_id"),
                        name="unique_inbound_per_gateway_provider_id",
                    )
                ],
            },
        ),
    ]
