# Generated by Django 5.2.14 on 2026-09-27 00:46

from django.db import migrations, models


def retire_sms_gate_gateways(apps, schema_editor):
    """Switch off the Android-phone gateways this release no longer drives.

    Kept, not deleted: their messages still reference them. Left active, one
    would stay the default and every send would reach for a driver that is gone;
    switched off, the relay gateway provisions itself on the next send.
    """
    MessagingGateway = apps.get_model("messaging", "MessagingGateway")
    MessagingGateway.objects.filter(provider="sms_gate").update(
        is_active=False, is_default=False
    )


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0002_deliveryreceipt_inboundmessage"),
    ]

    operations = [
        migrations.AddField(
            model_name="outboundmessage",
            name="template_kind",
            field=models.CharField(blank=True, db_default="", default="", max_length=40),
        ),
        migrations.AddField(
            model_name="outboundmessage",
            name="template_values",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AlterField(
            model_name="messaginggateway",
            name="max_messages_per_minute",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="messaginggateway",
            name="provider",
            field=models.CharField(
                choices=[("relay", "Pointy relay (Resala)"), ("fake", "Fake (testing)")],
                default="relay",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="messaginggateway",
            name="send_timeout_seconds",
            field=models.PositiveIntegerField(default=20),
        ),
        migrations.RunPython(retire_sms_gate_gateways, migrations.RunPython.noop),
    ]
