# Generated by Django 6.0.2 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0002_seed_default_categories"),
    ]

    operations = [
        migrations.AlterField(
            model_name="expense",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="expensecategory",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
