# Generated by Django 6.0.2 on 2026-09-22 19:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0005_backfill_expense_lifecycle"),
        ("sales", "0037_order_extra_discount_amount"),
        ("treasury", "0004_moneyaccount_bank_slug_moneyaccount_iban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="expense",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="expenses",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="expense",
            index=models.Index(
                fields=["money_account", "payment_method", "-spent_at"],
                name="expense_account_spent_idx",
            ),
        ),
    ]
