# Generated by Django 6.0.2 on 2026-09-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0002_seed_default_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="moneyaccount",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank"),
                    ("provider", "Provider float"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
    ]
