# Generated by Django 6.0.2 on 2026-09-22 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("treasury", "0003_alter_moneyaccount_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="moneyaccount",
            name="bank_slug",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="iban",
            field=models.CharField(blank=True, max_length=34),
        ),
    ]
