# Generated by Django 5.2.14 on 2026-10-03 18:59

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0016_payment_method_account_credit"),
        ("treasury", "0004_moneyaccount_bank_slug_moneyaccount_iban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CardSettlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "doc_status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("submitted", "Submitted"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_default="draft",
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("cancel_reason", models.TextField(blank=True, db_default="")),
                (
                    "amendment_index",
                    models.PositiveSmallIntegerField(db_default=0, default=0),
                ),
                (
                    "settled_on",
                    models.DateField(
                        db_index=True, default=django.utils.timezone.localdate
                    ),
                ),
                (
                    "amount_received",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("gross_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "commission_amount",
                    models.DecimalField(decimal_places=2, max_digits=12),
                ),
                ("difference", models.DecimalField(decimal_places=2, max_digits=12)),
                ("payment_count", models.PositiveIntegerField(default=0)),
                ("first_day", models.DateField(blank=True, null=True)),
                ("last_day", models.DateField(blank=True, null=True)),
                ("reference", models.CharField(blank=True, max_length=128)),
                ("note", models.TextField(blank=True)),
            ],
            options={
                "ordering": ["-settled_on", "-created_at"],
                "permissions": [
                    (
                        "cancel_cardsettlement",
                        "Cancel a recorded card settlement and hold its payments again",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CardSettlementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_live", models.BooleanField(db_default=True, default=True)),
            ],
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="closed_on",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="holds_untagged_card",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="settlement_cutoff",
            field=models.TimeField(
                db_default=datetime.time(0, 0), default=datetime.time(0, 0)
            ),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="settlement_lag_days",
            field=models.PositiveSmallIntegerField(
                db_default=1,
                default=1,
                validators=[django.core.validators.MaxValueValidator(10)],
            ),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="settlement_weekdays",
            field=models.CharField(
                db_default="6,0,1,2,3", default="6,0,1,2,3", max_length=32
            ),
        ),
        migrations.AddField(
            model_name="moneyaccount",
            name="settles_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clearing_accounts",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AlterField(
            model_name="moneyaccount",
            name="kind",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("bank", "Bank"),
                    ("provider", "Provider float"),
                    ("clearing", "Card takings held by the processor"),
                ],
                db_index=True,
                max_length=8,
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(("closed_on__isnull", True), ("kind", "clearing")),
                fields=("settles_into",),
                name="treasury_one_open_clearing_per_bank",
            ),
        ),
        migrations.AddConstraint(
            model_name="moneyaccount",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("closed_on__isnull", True),
                    ("holds_untagged_card", True),
                    ("kind", "clearing"),
                ),
                fields=("holds_untagged_card",),
                name="treasury_one_open_untagged_clearing",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="amended_from",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_amendments",
                to="treasury.cardsettlement",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="bank_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements_in",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="cancelled_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_cancelled",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="clearing_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlements_out",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="card_settlements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="submitted_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_submitted",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cardsettlement",
            name="superseded_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(app_label)s_%(class)s_supersedes",
                to="treasury.cardsettlement",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlementline",
            name="payment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settlement_lines",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="cardsettlementline",
            name="settlement",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="treasury.cardsettlement",
            ),
        ),
        migrations.AddIndex(
            model_name="cardsettlement",
            index=models.Index(
                fields=["clearing_account", "doc_status", "settled_on"],
                name="treasury_settle_clearing_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="cardsettlement",
            index=models.Index(
                fields=["bank_account", "doc_status", "settled_on"],
                name="treasury_settle_bank_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="cardsettlementline",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_live", True)),
                fields=("payment",),
                name="treasury_payment_settled_once",
            ),
        ),
    ]
