# Generated by Django 5.2.14 on 2026-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("key", models.CharField(max_length=64, unique=True)),
                ("name_en", models.CharField(max_length=120)),
                ("name_ar", models.CharField(max_length=120)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("national", "national"),
                            ("religious", "religious"),
                            ("international", "international"),
                            ("commercial", "commercial"),
                            ("local", "local"),
                        ],
                        default="national",
                        max_length=20,
                    ),
                ),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("fixed", "fixed"),
                            ("nth_weekday", "nth_weekday"),
                            ("range", "range"),
                        ],
                        max_length=20,
                    ),
                ),
                ("month", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("day", models.PositiveSmallIntegerField(blank=True, null=True)),
                ("weekday", models.SmallIntegerField(blank=True, null=True)),
                ("week_ordinal", models.SmallIntegerField(blank=True, null=True)),
                ("offset_days", models.SmallIntegerField(default=0)),
                ("span_days", models.PositiveSmallIntegerField(default=1)),
                ("start_date", models.DateField(blank=True, null=True)),
                ("end_date", models.DateField(blank=True, null=True)),
                ("show_in_dashboard", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("builtin", "builtin"),
                            ("relay", "relay"),
                            ("local", "local"),
                        ],
                        default="builtin",
                        max_length=20,
                    ),
                ),
                ("relay_id", models.CharField(blank=True, default="", max_length=80)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["category", "key"],
            },
        ),
    ]
