# Generated by Django 5.2.14 on 2026-05-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attachments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="role",
            field=models.CharField(
                choices=[
                    ("general", "General"),
                    ("document", "Document"),
                    ("product_image", "Product image"),
                    ("supplier_invoice_scan", "Supplier invoice scan"),
                    ("shop_logo", "Shop logo"),
                ],
                db_index=True,
                default="general",
                max_length=64,
            ),
        ),
    ]
