# Generated by Django 5.2.14 on 2026-06-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SalesChannel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "slug",
                    models.SlugField(allow_unicode=True, max_length=64, unique=True),
                ),
                (
                    "channel_type",
                    models.CharField(
                        choices=[
                            ("pos", "Point of sale"),
                            ("delivery", "Delivery app"),
                            ("ecommerce", "E-commerce"),
                            ("marketplace", "Marketplace"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=24,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_system", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                (
                    "api_key_prefix",
                    models.CharField(blank=True, db_index=True, max_length=16),
                ),
                (
                    "api_key_hash",
                    models.CharField(blank=True, editable=False, max_length=128),
                ),
                ("api_key_generated_at", models.DateTimeField(blank=True, null=True)),
                ("api_key_last_used_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["-is_system", "name"],
            },
        ),
    ]
