# Generated by Django 5.2.14 on 2026-06-19 12:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="reasoning",
            field=models.TextField(blank=True),
        ),
    ]
