# Generated by Django 5.2.14 on 2026-06-19 14:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0002_aimessage_reasoning"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="attachments",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
