# Generated by Django 5.2.14 on 2026-06-19 19:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("ai", "0003_aimessage_attachments"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="tool_events",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
