# Generated by Django 6.0.2 on 2026-06-21 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0006_aimessage_prior_tool_messages"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="sources",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="aimessage",
            name="web_searched",
            field=models.BooleanField(default=False),
        ),
    ]
