# Generated by Django 6.0.2 on 2026-09-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai", "0007_aimessage_sources_aimessage_web_searched"),
    ]

    operations = [
        migrations.AddField(
            model_name="aimessage",
            name="ui_surfaces",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
