# Generated by Django 5.2.14 on 2026-09-02 00:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("attachments", "0003_alter_attachment_created_at_and_more"),
        ("purchasing", "0026_purchaseline_unit_cost_in_currency_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InvoiceIntake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.CharField(
                        choices=[("chat", "Chat"), ("purchasing", "Purchasing screen")],
                        default="chat",
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("capturing", "Capturing"),
                            ("extracting", "Extracting"),
                            ("reconciling", "Reconciling"),
                            ("planned", "Planned"),
                            ("applied", "Applied"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="capturing",
                        max_length=16,
                    ),
                ),
                ("extraction", models.JSONField(blank=True, default=dict)),
                ("plan", models.JSONField(blank=True, default=dict)),
                ("review_edits", models.JSONField(blank=True, default=dict)),
                ("confidence_summary", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_intakes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "pages",
                    models.ManyToManyField(
                        blank=True,
                        related_name="invoice_intakes",
                        to="attachments.attachment",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_intakes",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invoice_intakes",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
    ]
