# Generated by Django 6.0.2 on 2026-06-20 18:04

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="MigrationSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("system_key", models.CharField(max_length=64)),
                (
                    "transport_kind",
                    models.CharField(
                        choices=[
                            ("mssql", "Microsoft SQL Server"),
                            ("postgres", "PostgreSQL"),
                            ("sqlite", "SQLite"),
                            ("mongo", "MongoDB"),
                        ],
                        max_length=16,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=255)),
                ("port", models.PositiveIntegerField(blank=True, null=True)),
                ("database_name", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=150)),
                ("password", models.CharField(blank=True, max_length=255)),
                ("extra_options", models.JSONField(blank=True, default=dict)),
                ("detected_version", models.CharField(blank=True, max_length=64)),
                (
                    "last_compat_status",
                    models.CharField(
                        choices=[
                            ("unknown", "Not checked"),
                            ("compatible", "Compatible"),
                            ("incompatible", "Incompatible"),
                        ],
                        default="unknown",
                        max_length=16,
                    ),
                ),
                ("last_compat_report", models.JSONField(blank=True, default=dict)),
                ("last_run_at", models.DateTimeField(blank=True, null=True)),
                ("credentials_cleared", models.BooleanField(default=False)),
                ("is_archived", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "mode",
                    models.CharField(
                        choices=[("dry_run", "Dry run"), ("import", "Import")],
                        max_length=8,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Completed with issues"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("selected_entities", models.JSONField(blank=True, default=list)),
                (
                    "progress_percent",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[django.core.validators.MaxValueValidator(100)],
                    ),
                ),
                ("progress_message", models.CharField(blank=True, max_length=240)),
                ("current_entity", models.CharField(blank=True, max_length=48)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("error_message", models.TextField(blank=True)),
                (
                    "initiated_by_user_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("initiated_by_username", models.CharField(blank=True, max_length=150)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="runs",
                        to="migration.migrationsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MigrationIdentityMap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(db_index=True, max_length=48)),
                ("source_key", models.CharField(max_length=255)),
                ("target_object_id", models.PositiveBigIntegerField()),
                (
                    "target_content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "first_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="migration.migrationrun",
                    ),
                ),
                (
                    "last_seen_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="migration.migrationrun",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="identities",
                        to="migration.migrationsource",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MigrationIssue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("entity_type", models.CharField(db_index=True, max_length=48)),
                ("source_key", models.CharField(blank=True, max_length=255)),
                (
                    "severity",
                    models.CharField(
                        choices=[("warning", "Warning"), ("error", "Error")],
                        max_length=8,
                    ),
                ),
                ("code", models.CharField(max_length=48)),
                ("message", models.TextField()),
                ("detail", models.JSONField(blank=True, default=dict)),
                (
                    "run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="issues",
                        to="migration.migrationrun",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(fields=["run", "severity"], name="migration_m_run_id_71c8c5_idx"),
                    models.Index(
                        fields=["run", "entity_type"],
                        name="migration_m_run_id_b57088_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="migrationrun",
            index=models.Index(
                fields=["source", "-created_at"], name="migration_m_source__bbf36c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrationrun",
            index=models.Index(
                fields=["status", "-created_at"], name="migration_m_status_f34704_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="migrationidentitymap",
            index=models.Index(
                fields=["source", "entity_type"], name="migration_m_source__89ccba_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="migrationidentitymap",
            constraint=models.UniqueConstraint(
                fields=("source", "entity_type", "source_key"),
                name="uniq_identity_per_source_entity_key",
            ),
        ),
    ]
