# Generated by Django 5.2.14 on 2026-06-21 01:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("migration", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="migrationrun",
            name="options",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
