# Generated by Django 5.2.14 on 2026-09-19 14:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_paymentcard_cardholder_name"),
        ("migration", "0005_alter_migrationrun_error_message_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CollapsePlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Reading the catalogue"),
                            ("ready", "Ready to review"),
                            ("failed", "Failed"),
                            ("approved", "Approved"),
                            ("applied", "Applied"),
                            ("superseded", "Superseded"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("stages", models.JSONField(blank=True, db_default=[], default=list)),
                ("error_message", models.TextField(blank=True, db_default="")),
                ("warranty_days", models.PositiveIntegerField(db_default=0, default=0)),
                ("stats", models.JSONField(blank=True, db_default={}, default=dict)),
                ("built_at", models.DateTimeField(blank=True, null=True)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by_user_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "approved_by_username",
                    models.CharField(blank=True, db_default="", max_length=150),
                ),
                (
                    "applied_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collapse_plans",
                        to="migration.migrationrun",
                    ),
                ),
                (
                    "asset_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="collapse_plans",
                        to="customers.assettype",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="collapse_plans",
                        to="migration.migrationsource",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CollapseCandidate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("source_key", models.CharField(max_length=255)),
                (
                    "source_name",
                    models.CharField(blank=True, db_default="", max_length=255),
                ),
                (
                    "variant_source_key",
                    models.CharField(blank=True, db_default="", max_length=255),
                ),
                (
                    "legacy_barcode",
                    models.CharField(blank=True, db_default="", max_length=64),
                ),
                (
                    "decision",
                    models.CharField(
                        choices=[
                            ("collapse", "Collapse into a unit"),
                            ("keep", "Keep as a product"),
                        ],
                        db_index=True,
                        default="collapse",
                        max_length=12,
                    ),
                ),
                ("stem", models.CharField(blank=True, db_default="", max_length=255)),
                (
                    "stem_key",
                    models.CharField(
                        blank=True, db_default="", db_index=True, max_length=255
                    ),
                ),
                (
                    "identifier",
                    models.CharField(blank=True, db_default="", max_length=120),
                ),
                (
                    "identifier_kind",
                    models.CharField(blank=True, db_default="", max_length=16),
                ),
                ("options", models.JSONField(blank=True, db_default={}, default=dict)),
                (
                    "attributes",
                    models.JSONField(blank=True, db_default={}, default=dict),
                ),
                (
                    "unit_status",
                    models.CharField(
                        choices=[("in_stock", "In stock"), ("sold", "Sold")],
                        default="in_stock",
                        max_length=12,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        db_default=0, decimal_places=6, default=0, max_digits=18
                    ),
                ),
                (
                    "list_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "sold_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("acquired_at", models.DateTimeField(blank=True, null=True)),
                ("sold_at", models.DateTimeField(blank=True, null=True)),
                (
                    "supplier_source_key",
                    models.CharField(blank=True, db_default="", max_length=255),
                ),
                (
                    "sale_source_key",
                    models.CharField(blank=True, db_default="", max_length=255),
                ),
                (
                    "confidence",
                    models.DecimalField(decimal_places=2, default=0, max_digits=3),
                ),
                ("reasons", models.JSONField(blank=True, db_default=[], default=list)),
                ("edited", models.BooleanField(db_default=False, default=False)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="candidates",
                        to="migration.collapseplan",
                    ),
                ),
            ],
            options={
                "ordering": ["confidence", "stem_key", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="collapseplan",
            index=models.Index(
                fields=["source", "-created_at"], name="migration_c_source__a5190a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collapsecandidate",
            index=models.Index(
                fields=["plan", "confidence", "id"],
                name="migration_c_plan_id_629c52_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="collapsecandidate",
            index=models.Index(
                fields=["plan", "stem_key"], name="migration_c_plan_id_98eb2a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="collapsecandidate",
            index=models.Index(
                fields=["plan", "decision"], name="migration_c_plan_id_ced756_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="collapsecandidate",
            constraint=models.UniqueConstraint(
                fields=("plan", "source_key"), name="uniq_collapse_candidate_per_plan"
            ),
        ),
    ]
