# Generated by Codex on 2026-06-05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("printing", "0001_initial"),
        ("purchasing", "0016_purchase_line_expiry_dates"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PrintAuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("sale_order", "Sale order"),
                            ("purchase_order", "Purchase order"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[("print", "Print"), ("share", "Share")],
                        max_length=16,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("completed", "Completed"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                    ),
                ),
                ("document_number", models.CharField(db_index=True, max_length=64)),
                ("agent_identifier", models.CharField(blank=True, max_length=120)),
                ("device_name", models.CharField(blank=True, max_length=160)),
                ("printer_name", models.CharField(blank=True, max_length=160)),
                ("printer_endpoint", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "agent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to="printing.printagent",
                    ),
                ),
                (
                    "print_job",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_audit_events",
                        to="printing.printjob",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_audit_events",
                        to="purchasing.purchaseorder",
                    ),
                ),
                (
                    "sale_order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_audit_events",
                        to="sales.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="print_audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="printauditevent",
            index=models.Index(
                fields=["document_type", "sale_order", "-created_at"],
                name="print_audit_sale_doc_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="printauditevent",
            index=models.Index(
                fields=["document_type", "purchase_order", "-created_at"],
                name="print_audit_purchase_idx",
            ),
        ),
    ]
