# Generated by Django 5.2.14 on 2026-06-13 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0009_product_is_prepared_product_unit_and_more"),
        ("printing", "0003_printjob_lease_expires_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="printjob",
            name="job_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("kitchen", "Kitchen ticket")],
                default="receipt",
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="printtemplate",
            name="template_type",
            field=models.CharField(
                choices=[("receipt", "Receipt"), ("kitchen", "Kitchen ticket")],
                default="receipt",
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="PrepStation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120, unique=True)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("priority", models.IntegerField(default=0)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="prep_stations",
                        to="catalog.productcategory",
                    ),
                ),
                (
                    "printer_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prep_stations",
                        to="printing.printerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="printjob",
            name="prep_station",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="print_jobs",
                to="printing.prepstation",
            ),
        ),
        migrations.AddConstraint(
            model_name="prepstation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_default", True)),
                fields=("is_default",),
                name="unique_default_prep_station",
            ),
        ),
    ]
