# Generated by Django 5.2.14 on 2026-06-23 17:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0007_backfill_payment_session_paid_at"),
        ("printing", "0005_alter_prepstation_created_at_and_more"),
        ("purchasing", "0018_alter_purchaseline_created_at_and_more"),
        ("sales", "0023_stockreservation"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="printauditevent",
            name="payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="print_audit_events",
                to="payments.payment",
            ),
        ),
        migrations.AddField(
            model_name="printauditevent",
            name="supplier_payment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="print_audit_events",
                to="purchasing.supplierpayment",
            ),
        ),
        migrations.AlterField(
            model_name="printauditevent",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("sale_order", "Sale order"),
                    ("purchase_order", "Purchase order"),
                    ("payment_receipt", "Payment receipt"),
                ],
                max_length=32,
            ),
        ),
        migrations.AddIndex(
            model_name="printauditevent",
            index=models.Index(
                fields=["document_type", "payment", "-created_at"],
                name="print_audit_payment_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="printauditevent",
            index=models.Index(
                fields=["document_type", "supplier_payment", "-created_at"],
                name="print_audit_supplier_pay_idx",
            ),
        ),
    ]
