<#
  Pointy on-prem - the ONLY PowerShell we ship.

  Everything that deploys, updates, watches and heals the stack is bash under
  deploy/onprem/*.sh, running inside a WSL2 distro. This file exists solely
  because three jobs cannot be done from Linux:

    1. INSTALL  - enabling the Windows features, installing WSL, importing the
                  distro, and setting up what keeps it alive.
    2. KEEPING THE DISTRO ALIVE. WSL powers a distro off about 15 s after its
                  last Windows-side client (a wsl.exe) exits, and systemd
                  running inside does not count. What shops found works is a
                  PowerShell window with `wsl` running in it, left open. The
                  install sets that up: keep-pointy-running.ps1 opens it,
                  minimised, at every sign-in, holds a hidden wsl.exe open, and
                  starts the distro again the moment that client dies (a
                  `wsl --shutdown`, Windows Update servicing WSL). -Boot, the
                  session-0 supervisor of the PointyWSL task, does the same
                  from boot with no one signed in; it has not been reliable in
                  the field, so it is registered off and is only the fallback.
    3. -Boot    - bridging the Windows LAN into the NAT'd WSL VM (portproxy +
                  firewall), which must be re-done every time the VM starts
                  because its IP changes each time. (The keeper does this too.)

  It deliberately contains NO deployment logic. It hands off to install.sh
  inside the distro and never duplicates it.

      # First install (elevated PowerShell, from the extracted bundle):
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1

      # What the scheduled task runs at boot, and re-runs should it ever exit:
      # supervise the distro and the LAN bridge until Windows shuts down.
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1 -Boot

      # One reconcile pass that returns - for an operator at the keyboard:
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1 -Boot -Once

  Re-run the install form any time; it is idempotent.
#>
[CmdletBinding()]
param(
    # Supervise: start the distro, hold it open, re-point the LAN bridge at it,
    # and keep doing so until Windows stops. What the PointyWSL task runs.
    [switch]$Boot,
    # With -Boot: one reconcile pass, then return. For an operator at the
    # keyboard; the running supervisor is left alone (and started if absent).
    [switch]$Once,
    # Distro name. Changing this on an existing install orphans the old one.
    [string]$Distro = "Pointy",
    # Where the distro's ext4.vhdx lives. MUST be a local NTFS disk.
    [string]$InstallRoot = (Join-Path $env:ProgramData "Pointy"),
    # LAN ports published from inside WSL to the shop network.
    [int]$ApiPort = 8000,
    [int]$WebPort = 80,
    # Skip the interactive confirmation when Docker Desktop is present.
    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

# wsl.exe emits UTF-16LE by default, which turns every parsed line into
# "P\0o\0i\0n\0t\0y\0". WSL_UTF8 makes it emit UTF-8 (wsl.exe 0.64+); we still
# decode defensively below for the inbox Windows 10 build that ignores it.
$env:WSL_UTF8 = "1"

$BundleRoot  = Split-Path -Parent $PSScriptRoot   # ...\<bundle>\  (wsl\ is one down)
$LogDir      = Join-Path $InstallRoot "logs"
$LogFile     = Join-Path $LogDir "bootstrap.log"
$StateFile   = Join-Path $InstallRoot "bridge-state.json"
$TaskName    = "PointyWSL"
# keep-pointy-running.ps1's task. While it is on, it keeps the distro alive and
# the PointyWSL supervisor stands down: two keepers fight over one distro.
$KeeperTaskName = "PointyKeepAlive"
$GuestDir    = "/opt/pointy"
# First line of the .wslconfig this script writes; how -Boot tells its own file
# from one an operator wrote by hand.
$WslConfigMarker = "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem."
# The keep-alive client ("anchor") the supervisor holds open - see -Boot below.
$AnchorCommand  = "/bin/sleep"
$AnchorArgument = "infinity"
$SupervisorMutexName = "Global\PointyWSL-Supervisor"
$SupervisorStateFile = Join-Path $InstallRoot "supervisor-state.json"
# How often the supervisor re-proves the LAN bridge while everything is quiet.
$ReconcileIntervalSec = 300
# Consecutive checks the distro may fail to answer before it is terminated and
# started fresh. Three, a minute apart: a VM that has not answered `true` for
# that long is not busy, it is gone.
$DistroFailuresBeforeTerminate = 3
# Why the last `wsl --list` returned nothing: "" when it worked, else its
# error. An absent distro and a WSL service that is mid-update look the same
# to a caller that only counts names.
$script:WslListError = ""

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $line = "{0} [pointy-wsl] {1} {2}" -f (Get-Date -Format "yyyy-MM-ddTHH:mm:ss"), $Level, $Message
    switch ($Level) {
        "WARN"  { Write-Host $line -ForegroundColor Yellow }
        "ERROR" { Write-Host $line -ForegroundColor Red }
        default { Write-Host $line }
    }
    try {
        if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null }
        # The supervisor writes a line every few minutes for years; keep one
        # generation behind so a till's disk never fills with our diary.
        if ((Test-Path $LogFile) -and ((Get-Item $LogFile).Length -gt 5MB)) {
            Move-Item -Force $LogFile ($LogFile -replace '\.log$', '.1.log')
        }
        Add-Content -Path $LogFile -Value $line -Encoding UTF8
    } catch { }   # never let logging break the install
}

function Die { param([string]$Message) Write-Log $Message "ERROR"; exit 1 }

function Test-Admin {
    (New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent())
    ).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
}

# Run a native command and return its stdout, without $ErrorActionPreference
# turning ordinary non-zero exits (which wsl.exe uses for "not installed") into
# terminating errors.
function Invoke-Native {
    param([string]$File, [string[]]$Arguments)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $out = & $File @Arguments 2>&1
        return [pscustomobject]@{
            ExitCode = $LASTEXITCODE
            Output   = ($out | Out-String)
        }
    } finally { $ErrorActionPreference = $prev }
}

# One argument, quoted the way CommandLineToArgvW un-quotes it, so a command
# line rebuilt from an array carries spaces and quotes through intact.
function ConvertTo-NativeArgument {
    param([string]$Value)
    if ($Value -ne "" -and $Value -notmatch '[\s"]') { return $Value }
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    $backslashes = 0
    foreach ($ch in $Value.ToCharArray()) {
        if ($ch -eq [char]'\') { $backslashes++; continue }
        if ($ch -eq [char]'"') {
            [void]$sb.Append([char]'\', $backslashes * 2 + 1)
            [void]$sb.Append([char]'"')
            $backslashes = 0
            continue
        }
        if ($backslashes) { [void]$sb.Append([char]'\', $backslashes); $backslashes = 0 }
        [void]$sb.Append($ch)
    }
    if ($backslashes) { [void]$sb.Append([char]'\', $backslashes * 2) }
    [void]$sb.Append('"')
    return $sb.ToString()
}

# Like Invoke-Native, but bounded. A wedged WSL service answers nothing, ever,
# and a supervisor blocked on it forever is a supervisor that never restarts
# anything. Output goes through files rather than pipes: a Linux daemon that
# inherits a pipe would keep the read side open long after wsl.exe returned.
function Invoke-NativeTimeout {
    param([string]$File, [string[]]$Arguments, [int]$TimeoutSec = 120)
    $stamp   = [guid]::NewGuid().ToString("N")
    $tempDir = [System.IO.Path]::GetTempPath()
    $outFile = Join-Path $tempDir "pointy-native-${stamp}.out"
    $errFile = Join-Path $tempDir "pointy-native-${stamp}.err"
    $line    = (($Arguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $start = @{ FilePath = $File; NoNewWindow = $true; PassThru = $true; ErrorAction = "Stop"
                    RedirectStandardOutput = $outFile; RedirectStandardError = $errFile }
        if ($line -ne "") { $start.ArgumentList = $line }   # an empty -ArgumentList is an error, not "no arguments"
        $p = Start-Process @start
        if (-not $p.WaitForExit($TimeoutSec * 1000)) {
            try { $p.Kill() } catch { }
            return [pscustomobject]@{ ExitCode = -1; TimedOut = $true
                Output = "timed out after ${TimeoutSec}s: ${File} ${line}" }
        }
        $p.WaitForExit()
        $text = ""
        foreach ($f in @($outFile, $errFile)) {
            if (Test-Path $f) { $text += [System.IO.File]::ReadAllText($f, (New-Object System.Text.UTF8Encoding($false))) }
        }
        return [pscustomobject]@{ ExitCode = $p.ExitCode; TimedOut = $false; Output = $text }
    } catch {
        return [pscustomobject]@{ ExitCode = -1; TimedOut = $false; Output = "could not run ${File}: $($_.Exception.Message)" }
    } finally {
        $ErrorActionPreference = $prev
        Remove-Item $outFile, $errFile -Force -ErrorAction SilentlyContinue
    }
}

function Invoke-Wsl {
    param([string[]]$Arguments, [int]$TimeoutSec = 120)
    Invoke-NativeTimeout -File "wsl.exe" -Arguments $Arguments -TimeoutSec $TimeoutSec
}

# Run a command inside the distro as root, returning trimmed stdout.
function Invoke-Guest {
    param([string]$Command, [int]$TimeoutSec = 120)
    $r = Invoke-Wsl @("-d", $Distro, "-u", "root", "--", "bash", "-lc", $Command) -TimeoutSec $TimeoutSec
    return [pscustomobject]@{ ExitCode = $r.ExitCode; Output = $r.Output.Trim() }
}

function Get-RegisteredDistros {
    $r = Invoke-Wsl @("--list", "--quiet") -TimeoutSec 60
    $script:WslListError = ""
    if ($r.ExitCode -ne 0) {
        $first = @((($r.Output -replace "`0", "") -split "`r?`n") | Where-Object { $_.Trim() } | Select-Object -First 1)
        $script:WslListError = "wsl --list failed (exit $($r.ExitCode)): $(($first -join '').Trim())"
        return @()
    }
    # Strip NULs in case WSL_UTF8 was ignored (inbox Windows 10 wsl.exe).
    return ($r.Output -replace "`0", "") -split "`r?`n" |
        ForEach-Object { $_.Trim() } | Where-Object { $_ }
}

function Test-DistroExists { (Get-RegisteredDistros) -contains $Distro }


# ---------------------------------------------------------------------------
# Keeping the distro alive.
#
# WSL powers a distro off about 15 seconds after its last Windows-side client
# (a wsl.exe) exits. systemd, dockerd and Postgres running inside do NOT count;
# only a process WSL itself launched from Windows does. So a boot task that
# starts the distro and returns has, in effect, started it for 15 seconds -
# and the shops that "kept a PowerShell window open" had found the only fix.
#
# This is documented ("systemd services will NOT keep your WSL instance
# alive" - learn.microsoft.com/windows/wsl/systemd) and it is how the service
# is written: WslService registers a wait on the CALLING WINDOWS PROCESS and
# queues the instance's termination timer (general.instanceIdleTimeout, 15 s)
# when the last such process is gone; nothing inside Linux is consulted. On
# the WSL the installer bundles, that termination is a hard power-off of the
# VM - Postgres dies mid-write - and the old 5-minute task was therefore
# hard-killing the stack up to 288 times a day.
#
# `vmIdleTimeout=-1` in .wslconfig keeps the empty VM, not the distro. The
# `[general] instanceIdleTimeout` that does keep the distro exists only from
# WSL 2.5.4, and the installer bundles 2.3.26, so it cannot be the fix for the
# fleet. What works on every WSL is the oldest trick there is: hold a client
# open. The "anchor" is a hidden `wsl.exe -d Pointy -u root --exec /bin/sleep
# infinity` that lives as long as Windows does; the supervisor below waits on
# it and starts the distro again the moment it exits.
#
# One more service rule that makes the supervisor's ORDER matter: WslService
# keeps one session per user, and a Windows logoff terminates that session
# (every instance and the VM) only if the session was first created from the
# logging-off Windows session. Created from session 0 - by this task, before
# anyone logs on - it is terminated only when the service stops. So the task
# starting the distro first, 30 s after boot, is what makes a cashier's logoff
# harmless; and should an interactive wsl.exe ever get there first, the anchor
# dying at that logoff is what makes the supervisor start it again, from
# session 0 this time.
# ---------------------------------------------------------------------------

function Get-AnchorArguments {
    return @("-d", $Distro, "-u", "root", "--exec", $AnchorCommand, $AnchorArgument)
}

# The anchor for THIS distro, whoever started it: the supervisor, an earlier
# supervisor that handed over, or the installer from the operator's session.
function Get-AnchorProcess {
    try {
        $rows = @(Get-CimInstance -ClassName Win32_Process -Filter "Name='wsl.exe'" -ErrorAction Stop)
    } catch { return $null }
    foreach ($row in $rows) {
        $cmd = "$($row.CommandLine)"
        if ($cmd -match "(^|\s)-d\s+$([regex]::Escape($Distro))(\s|$)" -and
            $cmd -like "*--exec ${AnchorCommand} ${AnchorArgument}*") {
            try { return [System.Diagnostics.Process]::GetProcessById([int]$row.ProcessId) } catch { }
        }
    }
    return $null
}

# No console window, no inherited console: closing the window this was started
# from must not take the shop's server with it.
function Start-AnchorProcess {
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName        = "wsl.exe"
    $psi.Arguments       = ((Get-AnchorArguments) -join " ")
    $psi.UseShellExecute = $false
    $psi.CreateNoWindow  = $true
    $p = New-Object System.Diagnostics.Process
    $p.StartInfo = $psi
    if (-not $p.Start()) { throw "wsl.exe did not start" }
    return $p
}

function Test-ProcessAlive {
    param($Process)
    if ($null -eq $Process) { return $false }
    try { return (-not $Process.HasExited) } catch { return $false }
}

function Stop-ProcessQuietly {
    param($Process)
    try { if (Test-ProcessAlive $Process) { $Process.Kill() } } catch { }
}

# Adopt the attached anchor, or attach one. Idempotent; used by the installer
# so the distro stays up between its steps, and by the supervisor each cycle.
function Start-AnchorIfMissing {
    $existing = Get-AnchorProcess
    if (Test-ProcessAlive $existing) { return $existing }
    try {
        $p = Start-AnchorProcess
        Write-Log "attached the keep-alive client to '${Distro}' (PID $($p.Id)); WSL keeps the distro up while it runs"
        return $p
    } catch {
        Write-Log "could not attach the keep-alive client to '${Distro}': $($_.Exception.Message)" "ERROR"
        return $null
    }
}

# Why can this process not see the distro? What a log can tell apart: it was
# never registered for this user, or the task's logon has no registry hive,
# so WSL - which looks registrations up through the caller's HKCU - reads an
# empty default profile. The second is the one theory about the boot task
# nobody has been able to confirm or rule out from a desk; this line settles
# it from the field.
function Write-DistroVisibilityDiagnosis {
    try {
        $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
        $hiveLoaded = Test-Path "Registry::HKEY_USERS\${sid}"
        $lxss = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss"
        $registered = @()
        if (Test-Path $lxss) {
            $registered = @(Get-ChildItem $lxss -ErrorAction SilentlyContinue | ForEach-Object {
                "$((Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DistributionName)" } | Where-Object { $_ })
        }
        $names = "none"
        if ($registered.Count) { $names = ($registered -join ", ") }
        Write-Log ("  running as ${env:USERDOMAIN}\${env:USERNAME} (${sid}); profile hive loaded: ${hiveLoaded}; " +
                   "distros registered under HKCU: ${names}") "ERROR"
        if (-not $hiveLoaded) {
            Write-Log ("  the task's logon has no registry hive, so WSL sees an empty profile. Give the task a stored " +
                       "password instead:  schtasks /Change /TN ${TaskName} /RU <user> /RP <password>") "ERROR"
        }
    } catch { }
}

# Does the distro answer at all? Bounded: at boot the WSL service may not be
# ready yet, and a wedged one never is.
function Test-DistroAnswers {
    param([int]$TimeoutSec = 60)
    return ((Invoke-Guest "true" -TimeoutSec $TimeoutSec).ExitCode -eq 0)
}


# ---------------------------------------------------------------------------
# -Boot : the supervisor.
#
# The Windows counterpart of what systemd is for a Linux shop. The PointyWSL
# task starts it at boot and it runs until Windows stops. Each cycle it makes
# sure the anchor is attached, the distro answers, and the LAN bridge points at
# the VM; and it wakes the instant the anchor exits, so a distro that Windows
# Update or an operator shut down is back before the tills notice. A second
# copy - the task's 5-minute repetition, an operator running -Boot by hand -
# finds the mutex held and does one pass instead.
# ---------------------------------------------------------------------------

function Enter-SupervisorLock {
    # $true when this process now holds the supervisor role.
    try {
        $created = $false
        $script:SupervisorMutex = New-Object System.Threading.Mutex($true, $SupervisorMutexName, [ref]$created)
        if ($created) { return $true }
        # Not created: another process owns it, unless that process died without
        # releasing - an abandoned mutex is handed to us with an exception.
        try {
            return $script:SupervisorMutex.WaitOne(0)
        } catch [System.Threading.AbandonedMutexException] { return $true }
    } catch {
        Write-Log "could not take the supervisor lock ($($_.Exception.Message)); running a single pass" "WARN"
        return $false
    }
}

function Exit-SupervisorLock {
    try {
        if ($script:SupervisorMutex) { $script:SupervisorMutex.ReleaseMutex(); $script:SupervisorMutex.Dispose() }
    } catch { }
    $script:SupervisorMutex = $null
}

# Sleep until the bridge is due again, but wake the instant the anchor exits.
# Returns how long it actually waited, so the caller's clock is the sum of
# these rather than wall time (which a test cannot script).
function Wait-AnchorOrInterval {
    param($Anchor, [int]$Seconds)
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $exited = $false
    if (Test-ProcessAlive $Anchor) {
        try { $exited = $Anchor.WaitForExit($Seconds * 1000) } catch { Start-Sleep -Seconds $Seconds }
    } else {
        Start-Sleep -Seconds $Seconds
    }
    return [pscustomobject]@{ AnchorExited = $exited; Seconds = [int]$sw.Elapsed.TotalSeconds }
}

# The supervisor's heartbeat, read by collect-diagnostics.ps1: a task that has
# been "running" for a week is healthy exactly when this file is fresh.
function Write-SupervisorState {
    param($Anchor, [bool]$Answering, [int]$Restarts, [datetime]$StartedAt)
    try {
        $anchorPid = 0
        if (Test-ProcessAlive $Anchor) { $anchorPid = [int]$Anchor.Id }
        @{ supervisor_pid = $PID; started_at = $StartedAt.ToString("o"); heartbeat_at = (Get-Date -Format "o")
           anchor_pid = $anchorPid; distro_answering = $Answering; distro_restarts = $Restarts } |
            ConvertTo-Json | Set-Content -Path $SupervisorStateFile -Encoding UTF8
    } catch { }
}

# Hand over to a newer bootstrap: start it detached and let this one return.
# It inherits nothing but the anchor, which stays attached throughout.
function Start-SupervisorProcess {
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    $arguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-File", $stable,
                   "-Boot", "-Distro", $Distro, "-InstallRoot", $InstallRoot, "-ApiPort", "$ApiPort", "-WebPort", "$WebPort")
    try {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName        = "powershell.exe"
        $psi.Arguments       = (($arguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow  = $true
        $p = New-Object System.Diagnostics.Process
        $p.StartInfo = $psi
        [void]$p.Start()
        Write-Log "started the newer bootstrap as PID $($p.Id)"
    } catch {
        Write-Log "could not start the newer bootstrap ($($_.Exception.Message)); the '${TaskName}' task re-launches it within 5 minutes" "WARN"
    }
}

# Start the PointyWSL task if it is not running: after this pass returns, only
# its supervisor keeps the distro up. A second start is ignored (IgnoreNew).
function Start-SupervisorTask {
    try {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        if ("$($task.State)" -eq "Running") { return $true }
        Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        Write-Log "started the '${TaskName}' task; its supervisor holds the distro open from here on"
        return $true
    } catch {
        Write-Log ("could not start the '${TaskName}' task: $($_.Exception.Message). Without it the distro powers off " +
                   "about 15 s after the last wsl.exe exits.") "WARN"
        return $false
    }
}

function Invoke-Supervise {
    param([int]$MaxCycles = 0)   # 0 = until Windows stops; tests bound it
    Write-Log ("supervisor started (PID ${PID}): holding '${Distro}' open, re-proving the LAN bridge every " +
               "$([int]($ReconcileIntervalSec / 60)) minutes, restarting the distro the moment it stops")
    $anchor = $null
    $cycle = 0; $failures = 0; $restarts = 0
    $sinceReconcile = $ReconcileIntervalSec      # the first cycle reconciles
    $backoff = 5
    $notVisibleLogged = $false
    $startedAt = Get-Date
    while ($MaxCycles -le 0 -or $cycle -lt $MaxCycles) {
        $cycle++
        try {
            $anchorStarted = $false

            # 1. The anchor: adopt one that is attached, else attach one. The
            #    anchor is what starts the distro; nothing else needs to.
            if (-not (Test-ProcessAlive $anchor)) { $anchor = Get-AnchorProcess }
            if (-not (Test-ProcessAlive $anchor)) {
                if (Test-DistroExists) {
                    $notVisibleLogged = $false
                    $anchor = Start-AnchorIfMissing
                    $anchorStarted = (Test-ProcessAlive $anchor)
                } elseif ($script:WslListError) {
                    # wsl.exe itself is not answering: the service is being
                    # updated or restarted. Nothing to fix, only to outwait.
                    if (-not $notVisibleLogged) {
                        Write-Log "WSL is not answering ($($script:WslListError)); waiting for it to come back" "WARN"
                        $notVisibleLogged = $true
                    }
                } elseif (-not $notVisibleLogged) {
                    Write-Log ("distro '${Distro}' is not registered for the user this runs as, so nothing can be started. " +
                               "Run this script without -Boot to install; if it IS installed, the '${TaskName}' task must " +
                               "run as the Windows user that installed it.") "ERROR"
                    Write-DistroVisibilityDiagnosis
                    $notVisibleLogged = $true
                }
            }

            # 2. Does the distro answer? An anchor can be holding a wedged VM.
            $answering = $false
            if (Test-ProcessAlive $anchor) {
                $answering = Test-DistroAnswers
                if ($answering) {
                    if ($failures -gt 0) { Write-Log "distro '${Distro}' answers again" }
                    $failures = 0; $backoff = 5
                    if ($anchorStarted -or $sinceReconcile -ge $ReconcileIntervalSec) {
                        Invoke-BootReconcile | Out-Null
                        $sinceReconcile = 0
                    }
                } else {
                    $failures++
                    Write-Log "distro '${Distro}' is not answering (${failures} of ${DistroFailuresBeforeTerminate} before it is restarted)" "WARN"
                    if ($failures -ge $DistroFailuresBeforeTerminate) {
                        Write-Log "terminating '${Distro}' so the next cycle starts it fresh" "ERROR"
                        Invoke-Wsl @("--terminate", $Distro) -TimeoutSec 60 | Out-Null
                        Stop-ProcessQuietly $anchor
                        $anchor = $null
                        $failures = 0
                        $restarts++
                    }
                }
            }

            Write-SupervisorState -Anchor $anchor -Answering $answering -Restarts $restarts -StartedAt $startedAt

            # 3. A newer bootstrap that arrived with a release update takes over.
            if ($answering -and (Update-BootstrapFromGuest)) {
                Write-Log "handing over to the newer bootstrap; the keep-alive client stays attached"
                Exit-SupervisorLock
                Start-SupervisorProcess
                return
            }

            # 4. Wait for the next bridge check, or for the anchor to exit.
            $wait = $ReconcileIntervalSec - $sinceReconcile
            if (-not $answering) { $wait = $backoff; $backoff = [math]::Min(60, $backoff * 2) }
            if ($wait -lt 1) { $wait = 1 }
            $waited = Wait-AnchorOrInterval -Anchor $anchor -Seconds $wait
            $sinceReconcile += $waited.Seconds
            if ($waited.AnchorExited) {
                Write-Log "the keep-alive client exited (wsl --shutdown, a WSL update, or a logoff); starting '${Distro}' again now" "WARN"
                $restarts++
                $anchor = $null
            }
        } catch {
            # One bad cycle must not end the supervisor: log it and carry on.
            Write-Log "supervisor cycle failed: $($_.Exception.Message)" "ERROR"
            Start-Sleep -Seconds 30
        }
    }
}


# ---------------------------------------------------------------------------
# -Boot : bridge the LAN into the NAT'd WSL VM.
#
# WSL2 sits behind a NAT with a fresh private IP on every VM start. So the tills
# cannot reach the stack until we forward the host's ports at the WSL IP, and we
# must re-do it whenever that IP changes.
#
# The forward listens on 0.0.0.0, which includes 127.0.0.1, so it also serves a
# till running on this same PC. It has to be the ONLY thing holding these ports
# on Windows - see the localhostForwarding note in Write-WslConfig.
#
# We do NOT use mirrored networking (which would remove all of this) because it
# needs Windows 11 22H2+; the shop fleet includes Windows 10, and running two
# different network designs is the exact split this migration exists to end.
# ---------------------------------------------------------------------------

function Get-WslIp {
    # eth0 specifically, NOT `hostname -I`: once Docker is running the distro also
    # holds docker0 and per-network bridge addresses (172.17.x, 172.18.x), and
    # `hostname -I` returns them in no guaranteed order. Forwarding the LAN to a
    # docker bridge address silently blackholes every till.
    #
    # Parsed here rather than with awk/cut inside the guest: the command crosses
    # PowerShell -> wsl.exe -> bash quoting, and a nested quote is a real bug
    # waiting to happen for no benefit.
    $r = Invoke-Guest "ip -4 -o addr show dev eth0"
    if ($r.ExitCode -ne 0) { return $null }
    if (($r.Output -replace "`0", "") -match 'inet\s+(\d{1,3}(?:\.\d{1,3}){3})') {
        return $Matches[1]
    }
    return $null
}

# portproxy is implemented by the IP Helper service. Without it running, every
# `netsh ... add` silently succeeds and forwards nothing - the single most
# common reason a WSL deployment is unreachable from the LAN.
function Enable-IpHelper {
    try {
        $svc = Get-Service -Name iphlpsvc -ErrorAction Stop
        if ($svc.StartType -ne "Automatic") {
            Set-Service -Name iphlpsvc -StartupType Automatic -ErrorAction Stop
            Write-Log "set the IP Helper service to start automatically"
        }
        if ($svc.Status -ne "Running") {
            Start-Service -Name iphlpsvc -ErrorAction Stop
            Write-Log "started the IP Helper service (portproxy needs it)"
        }
    } catch {
        Write-Log "could not ensure the IP Helper service is running: $($_.Exception.Message)" "WARN"
    }
}

function Get-PortProxyTarget {
    param([int]$Port)
    $r = Invoke-Native -File "netsh.exe" -Arguments @("interface", "portproxy", "show", "v4tov4")
    foreach ($line in ($r.Output -split "`r?`n")) {
        # "0.0.0.0         8000        172.28.144.3    8000"
        if ($line -match '^\s*(\S+)\s+(\d+)\s+(\S+)\s+(\d+)\s*$' -and [int]$Matches[2] -eq $Port) {
            return $Matches[3]
        }
    }
    return $null
}

# -Force re-creates a forward whose rule already looks right. A rule is only
# configuration; whether its listener actually bound is a separate question,
# and deleting and re-adding the rule is what makes the IP Helper try again.
function Set-PortProxy {
    param([int]$Port, [string]$Target, [switch]$Force)
    $current = Get-PortProxyTarget -Port $Port
    if ($current -eq $Target -and -not $Force) { return $false }
    if ($current) {
        Invoke-Native -File "netsh.exe" -Arguments @(
            "interface", "portproxy", "delete", "v4tov4",
            "listenaddress=0.0.0.0", "listenport=$Port") | Out-Null
    }
    $r = Invoke-Native -File "netsh.exe" -Arguments @(
        "interface", "portproxy", "add", "v4tov4",
        "listenaddress=0.0.0.0", "listenport=$Port",
        "connectaddress=$Target", "connectport=$Port")
    if ($r.ExitCode -ne 0) {
        Write-Log "failed to forward port ${Port} to ${Target}: $($r.Output.Trim())" "ERROR"
        return $false
    }
    Write-Log "LAN port ${Port} -> ${Target}:${Port} (was ${current})"
    return $true
}

# The addresses a till on the shop network dials: every IPv4 this machine holds
# on an adapter the LAN can reach. WSL's own vEthernet is left out on purpose -
# it often sits in 192.168.x too, and a till sent there can never route to it.
# Hyper-V's Default Switch and the VirtualBox/VMware host-only adapters are just
# as private. (A Hyper-V *external* switch stays in: on a machine that has one,
# it is where the real LAN address lives.)
function Get-LanIPv4 {
    try {
        return @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" -and
                "$($_.AddressState)" -eq "Preferred" -and
                $_.InterfaceAlias -notmatch 'WSL|Default Switch|VirtualBox|VMware|Loopback'
            } | Select-Object -ExpandProperty IPAddress)
    } catch { return @() }
}

# Does this URL reach one of OUR front doors? Both answer their health path
# themselves ("ok", 200), so a pass cannot come from IIS or a vendor's web
# server that happens to hold the port. No proxy: a shop PC's system proxy must
# not be asked for a LAN address.
function Test-PointyHttp {
    param([string]$Url, [int]$TimeoutMs = 4000)
    $response = $null
    try {
        $request = [System.Net.WebRequest]::Create($Url)
        $request.Proxy = $null
        $request.Timeout = $TimeoutMs
        $response = $request.GetResponse()
        return ([int]$response.StatusCode -eq 200)
    } catch {
        return $false
    } finally {
        if ($response) { $response.Close() }
    }
}

function Get-DeadAddresses {
    param([string[]]$Addresses, [int]$Port, [string]$HealthPath)
    return @($Addresses | Where-Object { -not (Test-PointyHttp "http://${_}:${Port}${HealthPath}") })
}

# Who holds a port, by address and process: the evidence a broken forward
# needs, because netsh never says that one failed to bind.
function Get-PortListeners {
    param([int]$Port)
    try {
        return @(Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction Stop | ForEach-Object {
            [pscustomobject]@{
                Address   = "$($_.LocalAddress)"
                ProcessId = [int]$_.OwningProcess
                Name      = "$((Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue).ProcessName)"
            }
        })
    } catch { return @() }   # Get-NetTCPConnection throws when nothing is listening
}

# The services running inside a process. "svchost" alone says nothing: the IP
# Helper that carries our forwards lives in one, and so does IIS's FTP service.
function Get-ServicesInProcess {
    param([int]$ProcessId)
    try {
        return @(Get-CimInstance -ClassName Win32_Service -Filter "ProcessId=$ProcessId" -ErrorAction Stop |
            ForEach-Object { "$($_.Name)" })
    } catch { return @() }
}

# -Fix replaces the generic advice for a port whose owner knows better.
function Write-PortDiagnosis {
    param([int]$Port, [string]$Fix = "")
    $listeners = @(Get-PortListeners -Port $Port)
    if ($listeners.Count -eq 0) {
        Write-Log ("  nothing is listening on port ${Port}: the IP Helper service has not opened the " +
                   "forward. Check 'Get-Service iphlpsvc' and 'netsh interface portproxy show v4tov4'.") "ERROR"
        return
    }
    foreach ($listener in $listeners) {
        $services = @(Get-ServicesInProcess -ProcessId $listener.ProcessId)
        $hosted = ""
        if ($services.Count -gt 0) { $hosted = ": " + ($services -join ", ") }
        Write-Log ("  {0}:{1} is held by {2} (PID {3}{4})" -f $listener.Address, $Port, $listener.Name, $listener.ProcessId, $hosted) "ERROR"
    }
    if (@($listeners | Where-Object { $_.Name -like "wslrelay*" }).Count -gt 0) {
        # See Write-WslConfig: this is the install-order race, already turned off
        # in .wslconfig, which only a fresh start of the WSL VM applies.
        Write-Log ("  wslrelay is WSL's localhost forwarding. It took port ${Port} before the LAN forward " +
                   "could, so the forward cannot bind. It is switched off in .wslconfig from now on; " +
                   "restart Windows once to apply that.") "ERROR"
    } elseif ($Fix) {
        Write-Log "  Fix: $Fix" "ERROR"
    } elseif ($Port -eq $WebPort) {
        # Windows very often already has something on :80 - IIS, the World Wide
        # Web Publishing Service, a vendor's print or label server. HTTP.sys
        # listeners show up as System (PID 4).
        Write-Log ("  Fix: stop that service, or set POINTY_WEB_PORT to a free port in ${GuestDir}/.env, " +
                   "re-run install.sh inside the distro, and re-run this script with -WebPort <port>.") "ERROR"
    } else {
        Write-Log "  Fix: stop the conflicting service, or set POINTY_BACKEND_PORT and -ApiPort together." "ERROR"
    }
}

# netsh reports success for a forward whose listener never bound, and a stack
# behind a dead forward looks perfectly healthy: containers up, log clean, the
# server's own till working. So walk the path a till takes, one hop at a time,
# and name the hop that breaks.
#
# Returns $true when every address answers, $false when the path is broken,
# and $null when the stack itself is not up yet, so there is nothing to judge.
function Confirm-LanBridge {
    param([string]$WslIp, [int]$Port, [string]$HealthPath)

    # 1. The stack, from inside the VM. Down here means the containers are still
    #    starting (normal at boot) or broken - neither is the bridge's doing.
    $guest = Invoke-Guest "curl -fsS -o /dev/null -m 4 http://127.0.0.1:${Port}${HealthPath}"
    if ($guest.ExitCode -ne 0) {
        Write-Log "port ${Port}: the stack is not answering inside WSL yet; the bridge is checked again on the next run" "WARN"
        return $null
    }

    # 2. Windows to the VM: the hop the forward itself makes.
    if (-not (Test-PointyHttp "http://${WslIp}:${Port}${HealthPath}")) {
        Write-Log ("port ${Port}: the stack answers inside WSL but not at ${WslIp}:${Port} from Windows. " +
                   "Check that POINTY_BACKEND_BIND and POINTY_WEB_BIND in ${GuestDir}/.env are 0.0.0.0; " +
                   "on Windows 11, also that no Hyper-V firewall policy blocks the WSL VM.") "ERROR"
        return $false
    }

    # 3. This machine's own addresses, the way a till dials them. From here that
    #    is a loopback hop, so it proves the forward binds and forwards; it cannot
    #    prove the firewall, which only filters traffic from other devices.
    $lan = @(Get-LanIPv4)
    $targets = @("127.0.0.1") + $lan
    $dead = @(Get-DeadAddresses -Addresses $targets -Port $Port -HealthPath $HealthPath)
    if ($dead.Count -gt 0) {
        Write-Log "port ${Port}: the LAN forward does not answer on $($dead -join ', '); re-creating it" "WARN"
        Set-PortProxy -Port $Port -Target $WslIp -Force | Out-Null
        Start-Sleep -Seconds 2
        $dead = @(Get-DeadAddresses -Addresses $targets -Port $Port -HealthPath $HealthPath)
        if ($dead.Count -gt 0) {
            Write-Log "port ${Port}: still unreachable on $($dead -join ', ') after re-creating the forward" "ERROR"
            Write-PortDiagnosis -Port $Port
            return $false
        }
        Write-Log "port ${Port}: the re-created forward answers"
    }
    if ($lan.Count -eq 0) {
        Write-Log "port ${Port}: this machine has no LAN address right now, so no till can reach it" "WARN"
        return $false
    }
    return $true
}

# Two things no check on this machine can see, because its requests to its own
# LAN address never pass the inbound firewall. Name them instead.
function Write-FirewallWarnings {
    param($Ftp = $null)
    $ports = "${ApiPort} and ${WebPort}"
    if ($Ftp) { $ports = "${ApiPort}, ${WebPort}, $($Ftp.Port) and $($Ftp.Range) (FTP camera uploads)" }
    try {
        foreach ($fwProfile in @(Get-NetFirewallProfile -PolicyStore ActiveStore -ErrorAction Stop)) {
            if ("$($fwProfile.Enabled)" -eq "True" -and "$($fwProfile.AllowLocalFirewallRules)" -eq "False") {
                Write-Log ("Group Policy makes the '$($fwProfile.Name)' firewall profile ignore local rules, so " +
                           "the Pointy allow rules do nothing there. Allow inbound TCP ${ports} " +
                           "in that policy instead.") "WARN"
            }
        }
    } catch { }
    try {
        foreach ($product in @(Get-CimInstance -Namespace "root/SecurityCenter2" -ClassName FirewallProduct -ErrorAction Stop)) {
            Write-Log ("a third-party firewall is installed ($($product.displayName)). If other devices cannot " +
                       "connect, allow inbound TCP ${ports} in it too.") "WARN"
        }
    } catch { }   # Windows Server has no Security Center
}

# -Port is one port or a range ("30000-30019"). -RemoteAddress narrows who may
# connect; without it, anyone the profile lets through.
function Add-FirewallRule {
    param([string]$Name, [string]$Port, [string[]]$RemoteAddress = @())
    try {
        if (Get-NetFirewallRule -DisplayName $Name -ErrorAction SilentlyContinue) { return }
        $rule = @{ DisplayName = $Name; Direction = "Inbound"; Action = "Allow"; Protocol = "TCP"
                   LocalPort = $Port; Profile = "Any"; ErrorAction = "Stop" }
        if ($RemoteAddress) { $rule.RemoteAddress = $RemoteAddress }
        New-NetFirewallRule @rule | Out-Null
        Write-Log "opened the firewall for inbound TCP ${Port} ('${Name}')"
    } catch {
        Write-Log "could not add firewall rule '${Name}': $($_.Exception.Message)" "WARN"
    }
}


# ---------------------------------------------------------------------------
# The DVRs' side of the bridge: FTP upload setups (SURVEILLANCE_FTP_PLAN.md).
#
# A DVR uploads to the `ftp` service on a control port (21) and opens its data
# connections on a passive range (30000-30019), and every one of those ports
# must cross the bridge like the tills' two. PASV hands the DVR this PC's LAN
# address - the one the installer was shown - so each passive port is forwarded
# 1:1. The ports come from the stack's own .env, so a shop that moved them (IIS
# already holding 21, say) is followed without anyone re-running this by hand.
#
# Two differences from the tills' ports. No HTTP health path proves them: the
# control port is proven by the server's greeting, and the passive ports - dark
# between transfers - by their forwards' listeners. And a broken FTP bridge
# stops camera uploads, not selling, so it is reported and never makes the
# till bridge count as broken.
#
# The firewall rules admit the private ranges only: the backend refuses public
# addresses itself on Linux, but behind a portproxy every DVR arrives from this
# PC's own address, so here the firewall is the only thing that can.
# ---------------------------------------------------------------------------

# 30000,30001,30002,30005 -> "30000-30002, 30005"
function Format-PortList {
    param([int[]]$Ports)
    $sorted = @($Ports | Sort-Object -Unique)
    $parts = @()
    $i = 0
    while ($i -lt $sorted.Count) {
        $j = $i
        while ($j + 1 -lt $sorted.Count -and $sorted[$j + 1] -eq $sorted[$j] + 1) { $j++ }
        if ($j -gt $i) { $parts += "$($sorted[$i])-$($sorted[$j])" } else { $parts += "$($sorted[$i])" }
        $i = $j + 1
    }
    return ($parts -join ", ")
}

# The FTP ports as the stack's .env sets them (lines of `grep ^POINTY_FTP_`),
# with docker-compose.yml's defaults for anything it leaves out. $null, and
# logged, when the .env names something the bridge must not forward.
function ConvertFrom-FtpEnv {
    param([string]$Text)
    $port = 21; $low = 30000; $high = 30019
    foreach ($line in (($Text -replace "`0", "") -split "`r?`n")) {
        if ($line -match '^\s*POINTY_FTP_PUBLIC_PORT\s*=\s*["'']?(\d{1,5})["'']?\s*(#.*)?$') {
            $port = [int]$Matches[1]
        } elseif ($line -match '^\s*POINTY_FTP_PASSIVE_PORTS\s*=\s*["'']?(\d{1,5}(-\d{1,5})?)["'']?\s*(#.*)?$') {
            $bounds = @($Matches[1] -split '-')
            $low = [int]$bounds[0]
            $high = [int]$bounds[-1]
        }
    }
    if ($port -lt 1 -or $port -gt 65535 -or $low -lt 1024 -or $high -lt $low -or $high -gt 65535 -or
        ($port -ge $low -and $port -le $high)) {
        Write-Log ("the FTP ports in ${GuestDir}/.env (POINTY_FTP_PUBLIC_PORT=${port}, POINTY_FTP_PASSIVE_PORTS=" +
                   "${low}-${high}) are not usable; FTP camera uploads are not bridged to the LAN") "ERROR"
        return $null
    }
    # One portproxy rule per port: a range meant for a Linux host (thousands of
    # ports) would bury the IP Helper.
    if ($high - $low + 1 -gt 100) {
        Write-Log ("POINTY_FTP_PASSIVE_PORTS in ${GuestDir}/.env spans $($high - $low + 1) ports; the Windows " +
                   "bridge forwards each port on its own and stops at 100. Narrow it (30000-30019 is plenty) and " +
                   "re-run install.sh; FTP camera uploads are not bridged until then") "ERROR"
        return $null
    }
    $range = "$low"
    if ($high -gt $low) { $range = "${low}-${high}" }
    return [pscustomobject]@{ Port = $port; Passive = @($low..$high); Range = $range }
}

function Get-FtpPorts {
    # Exit 1 is "no such line" and 2 "no .env yet": both leave the defaults.
    $r = Invoke-Guest "grep '^POINTY_FTP_' '${GuestDir}/.env'"
    return (ConvertFrom-FtpEnv -Text $r.Output)
}

# What a server says on connect, or "" when nothing answered in time.
function Get-FtpGreeting {
    param([string]$Address, [int]$Port, [int]$TimeoutMs = 4000)
    $client = New-Object System.Net.Sockets.TcpClient
    try {
        $pending = $client.BeginConnect($Address, $Port, $null, $null)
        if (-not $pending.AsyncWaitHandle.WaitOne($TimeoutMs)) { return "" }
        $client.EndConnect($pending)
        $stream = $client.GetStream()
        $stream.ReadTimeout = $TimeoutMs
        $buffer = New-Object byte[] 256
        $text = ""
        while ($text -notmatch "`n" -and $text.Length -lt 256) {
            $read = $stream.Read($buffer, 0, $buffer.Length)
            if ($read -le 0) { break }
            $text += [System.Text.Encoding]::ASCII.GetString($buffer, 0, $read)
        }
        return $text.Trim()
    } catch {
        return ""
    } finally {
        $client.Close()
    }
}

# Ours greets with "220 Pointy camera upload ready." - so, like the HTTP health
# paths, a pass cannot come from IIS's FTP service holding the port instead.
function Test-PointyFtp {
    param([string]$Address, [int]$Port)
    return ((Get-FtpGreeting -Address $Address -Port $Port) -like "220*Pointy*")
}

# The ports the IP Helper - which carries out every portproxy forward - is
# listening on right now, as a set; $null when that cannot be told.
function Get-ForwardListeningPorts {
    try {
        $helper = Get-CimInstance -ClassName Win32_Service -Filter "Name='iphlpsvc'" -ErrorAction Stop
        $helperPid = [int]$helper.ProcessId
        $ports = @{}
        if ($helperPid -le 0) { return $ports }
        foreach ($connection in @(Get-NetTCPConnection -State Listen -ErrorAction Stop)) {
            if ([int]$connection.OwningProcess -eq $helperPid) { $ports[[int]$connection.LocalPort] = $true }
        }
        return $ports
    } catch { return $null }
}

# Port ranges Windows keeps from programs, from
# `netsh interface ipv4 show excludedportrange protocol=tcp`. Hyper-V's NAT,
# which WSL runs on, takes blocks of the dynamic range (49152 and up) at every
# boot, and a forward inside one cannot listen: netsh still says it worked.
# Administered (*) ranges are an operator's own reservations, which a program
# may still listen on.
function Get-ExcludedPortRanges {
    $r = Invoke-Native -File "netsh.exe" -Arguments @("interface", "ipv4", "show", "excludedportrange", "protocol=tcp")
    $ranges = @()
    foreach ($line in ($r.Output -split "`r?`n")) {
        if ($line -match '^\s*(\d+)\s+(\d+)\s*(\*?)\s*$') {
            $ranges += [pscustomobject]@{ Start = [int]$Matches[1]; End = [int]$Matches[2]; Administered = ($Matches[3] -eq "*") }
        }
    }
    return $ranges
}

function Write-FtpPassiveDiagnosis {
    param([int[]]$Ports)
    $named = $false
    foreach ($range in @(Get-ExcludedPortRanges | Where-Object { -not $_.Administered })) {
        $inside = @($Ports | Where-Object { $_ -ge $range.Start -and $_ -le $range.End })
        if ($inside.Count -gt 0) {
            Write-Log ("  Windows has reserved TCP $($range.Start)-$($range.End) (Hyper-V's NAT, which WSL runs on, " +
                       "takes blocks like it at boot), so nothing can listen on $(Format-PortList $inside)") "ERROR"
            $named = $true
        }
    }
    foreach ($port in $Ports) {
        foreach ($listener in @(Get-PortListeners -Port $port)) {
            Write-Log ("  {0}:{1} is held by {2} (PID {3})" -f $listener.Address, $port, $listener.Name, $listener.ProcessId) "ERROR"
            $named = $true
        }
    }
    if (-not $named) {
        Write-Log ("  nothing else holds them: the IP Helper service has not opened the forwards. Check " +
                   "'Get-Service iphlpsvc' and 'netsh interface portproxy show v4tov4'.") "ERROR"
        return
    }
    Write-Log ("  Fix: set POINTY_FTP_PASSIVE_PORTS in ${GuestDir}/.env to a free range below 49152 (30000-30019 " +
               "by default), re-run install.sh inside the distro, then this script with -Boot -Once. " +
               "'netsh interface ipv4 show excludedportrange protocol=tcp' lists what Windows holds.") "ERROR"
}

# Forward every FTP port at the VM and open the firewall for them. Returns
# $true when a forward was (re)pointed.
function Update-FtpBridge {
    param([string]$WslIp, $Ftp)
    $changed = $false
    foreach ($port in @($Ftp.Port) + @($Ftp.Passive)) {
        if (Set-PortProxy -Port $port -Target $WslIp) { $changed = $true }
    }
    $lan = @("10.0.0.0/8", "172.16.0.0/12", "192.168.0.0/16", "169.254.0.0/16")
    Add-FirewallRule -Name "Pointy FTP (TCP $($Ftp.Port))" -Port "$($Ftp.Port)" -RemoteAddress $lan
    Add-FirewallRule -Name "Pointy FTP data (TCP $($Ftp.Range))" -Port $Ftp.Range -RemoteAddress $lan
    return $changed
}

# The DVRs' path, walked like the tills' (Confirm-LanBridge). $true when it
# answers, $false when a hop is broken, $null when the FTP service itself is
# not answering yet - nothing to judge, and nothing to repair.
function Confirm-FtpBridge {
    param([string]$WslIp, $Ftp)
    $port = $Ftp.Port

    # 1. The service, from Windows to the VM.
    if (-not (Test-PointyFtp -Address $WslIp -Port $port)) {
        Write-Log ("FTP port ${port}: the camera upload service does not answer at ${WslIp}:${port} yet, so FTP " +
                   "upload setups cannot connect ('docker compose ps ftp' in ${GuestDir} says why)") "WARN"
        return $null
    }

    # 2. The control port on this machine's own addresses, the way a DVR dials it.
    $targets = @("127.0.0.1") + @(Get-LanIPv4)
    $dead = @($targets | Where-Object { -not (Test-PointyFtp -Address $_ -Port $port) })
    if ($dead.Count -gt 0) {
        Write-Log "FTP port ${port}: the LAN forward does not answer on $($dead -join ', '); re-creating it" "WARN"
        Set-PortProxy -Port $port -Target $WslIp -Force | Out-Null
        Start-Sleep -Seconds 2
        $dead = @($targets | Where-Object { -not (Test-PointyFtp -Address $_ -Port $port) })
        if ($dead.Count -gt 0) {
            Write-Log "FTP port ${port}: still unreachable on $($dead -join ', ') after re-creating the forward" "ERROR"
            Write-PortDiagnosis -Port $port -Fix ("stop that service (IIS's FTP server is 'ftpsvc'), or set " +
                "POINTY_FTP_PUBLIC_PORT in ${GuestDir}/.env to a free port, re-run install.sh inside the distro, " +
                "and type the new port into each DVR's FTP settings.")
            return $false
        }
        Write-Log "FTP port ${port}: the re-created forward answers"
    }

    # 3. The passive range: a listener per forward, or a DVR logs in and then
    #    cannot send a byte. The control port's forward has just answered, so
    #    its listener must be in the set; if it is not, this machine hides who
    #    listens, and a data port missing from the set would prove nothing -
    #    re-creating twenty working forwards every cycle is worse than not
    #    looking.
    $listening = Get-ForwardListeningPorts
    if ($null -eq $listening -or -not $listening.ContainsKey($port)) { return $true }
    $missing = @($Ftp.Passive | Where-Object { -not $listening.ContainsKey($_) })
    if ($missing.Count -gt 0) {
        Write-Log "FTP data ports: no forward is listening on $(Format-PortList $missing); re-creating them" "WARN"
        foreach ($p in $missing) { Set-PortProxy -Port $p -Target $WslIp -Force | Out-Null }
        Start-Sleep -Seconds 2
        $listening = Get-ForwardListeningPorts
        if ($null -ne $listening) { $missing = @($missing | Where-Object { -not $listening.ContainsKey($_) }) }
        if ($missing.Count -gt 0) {
            Write-Log ("FTP data ports: still nothing listening on $(Format-PortList $missing), so a DVR can log in " +
                       "but not upload") "ERROR"
            Write-FtpPassiveDiagnosis -Ports $missing
            return $false
        }
        Write-Log "FTP data ports: the re-created forwards listen"
    }
    return $true
}

# One reconcile pass. Returns $true when the bridge was (re)pointed at the
# VM, $false when there was nothing to point it at. Never exits: the
# supervisor runs this every cycle and must outlive any single failure.
function Invoke-BootReconcile {
    if (-not (Test-DistroExists)) {
        Write-Log "distro '$Distro' is not registered - run this script without -Boot to install." "ERROR"
        return $false
    }

    # Any wsl.exe boots the VM if it is down. What keeps it up afterwards is
    # the supervisor's anchor - NOT systemd, which WSL does not count.
    $ping = Invoke-Guest "true" -TimeoutSec 60
    if ($ping.ExitCode -ne 0) {
        Write-Log "could not start distro '$Distro': $($ping.Output)" "ERROR"
        return $false
    }

    Enable-IpHelper
    Update-GeneratedWslConfig

    $ip = Get-WslIp
    if (-not $ip) {
        Write-Log "could not read the distro's eth0 address; not touching the LAN bridge." "ERROR"
        return $false
    }

    # Each port with the path its own front door answers without the backend:
    # edge owns the API port, web the browser port.
    $bridge = @(
        [pscustomobject]@{ Port = $ApiPort; HealthPath = "/healthz-edge" },
        [pscustomobject]@{ Port = $WebPort; HealthPath = "/healthz-web" }
    )

    $changed = $false
    foreach ($entry in $bridge) {
        if (Set-PortProxy -Port $entry.Port -Target $ip) { $changed = $true }
    }
    Add-FirewallRule -Name "Pointy API (TCP $ApiPort)" -Port $ApiPort
    Add-FirewallRule -Name "Pointy Web (TCP $WebPort)" -Port $WebPort

    $verified = $true
    foreach ($entry in $bridge) {
        $result = Confirm-LanBridge -WslIp $ip -Port $entry.Port -HealthPath $entry.HealthPath
        if ($result -ne $true) { $verified = $false }
    }

    # The DVRs' ports, judged apart: see "The DVRs' side of the bridge".
    $ftp = Get-FtpPorts
    $ftpVerified = $null
    if ($ftp) {
        if (Update-FtpBridge -WslIp $ip -Ftp $ftp) { $changed = $true }
        $ftpVerified = Confirm-FtpBridge -WslIp $ip -Ftp $ftp
    }
    # Once per boot is enough: these only change when someone changes the machine.
    if ($changed) { Write-FirewallWarnings -Ftp $ftp }

    $lan = @(Get-LanIPv4)
    try {
        $state = @{ wsl_ip = $ip; lan_ips = $lan; api_port = $ApiPort; web_port = $WebPort
                    verified = $verified; updated_at = (Get-Date -Format "o") }
        if ($ftp) {
            $state.ftp_port = $ftp.Port; $state.ftp_passive_ports = $ftp.Range; $state.ftp_verified = $ftpVerified
        }
        $state | ConvertTo-Json | Set-Content -Path $StateFile -Encoding UTF8
    } catch { }

    $where = if ($lan.Count) { " - tills reach it at " + (($lan | ForEach-Object { "http://${_}:${ApiPort}" }) -join ", ") } else { "" }
    if ($changed) {
        Write-Log "LAN bridge reconciled onto ${ip}${where}"
        if ($ftp -and $lan.Count) {
            Write-Log ("DVRs upload over FTP to " + (($lan | ForEach-Object { "${_}:$($ftp.Port)" }) -join ", ") +
                       " (data ports $($ftp.Range))")
        }
    }
    elseif ($verified -and $ftpVerified -ne $false) { Write-Log "LAN bridge already correct and answering (${ip}); nothing to do" }
    else { Write-Log "LAN bridge configured for ${ip}, but not every hop answered; see above" "WARN" }
    return $true
}


# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------

function Assert-Preflight {
    if (-not (Test-Admin)) {
        Die "run this in an ELEVATED (Administrator) PowerShell."
    }
    if ([Environment]::Is64BitOperatingSystem -eq $false) {
        Die "WSL2 requires 64-bit Windows."
    }

    $build = [int](Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").CurrentBuildNumber
    if ($build -lt 19041) {
        Die ("Windows build ${build} is too old for WSL2 (needs 19041 / Windows 10 2004 or newer). " +
             "Update Windows, or install this shop on a newer machine.")
    }
    if ($build -lt 19044) {
        Write-Log ("Windows build ${build} is out of support; WSL2 works but you are on your own " +
                   "for OS security fixes. 19044 (21H2) or newer is strongly recommended.") "WARN"
    }
    Write-Log "Windows build ${build}: OK"

    # Virtualization must be on in firmware. This is the one failure that needs
    # a physical visit (a BIOS/UEFI setting), so name it precisely rather than
    # letting `wsl --import` fail with an opaque HCS error later.
    $cs = Get-CimInstance -ClassName Win32_ComputerSystem
    if (-not $cs.HypervisorPresent) {
        $virt = (Get-CimInstance -ClassName Win32_Processor | Select-Object -First 1).VirtualizationFirmwareEnabled
        if ($virt -eq $false) {
            Die ("Hardware virtualization is DISABLED in this machine's BIOS/UEFI. " +
                 "Reboot into firmware setup and enable Intel VT-x / AMD-V (often called " +
                 "'Virtualization Technology' or 'SVM Mode'), then re-run this script.")
        }
        Write-Log "no hypervisor running yet - expected before the Windows features are enabled" "INFO"
    }

    $drive = (Get-Item $InstallRoot -ErrorAction SilentlyContinue)
    $root  = if ($drive) { $drive.PSDrive.Name } else { (Split-Path -Qualifier $InstallRoot).TrimEnd(':') }
    try {
        $free = (Get-PSDrive -Name $root).Free / 1GB
        if ($free -lt 20) {
            Write-Log ("only {0:N1} GB free on {1}: - the distro, images and Postgres data all live " +
                       "here and the virtual disk only ever grows. 20 GB+ recommended." -f $free, $root) "WARN"
        }
    } catch { }

    if (Get-Service -Name "com.docker.service" -ErrorAction SilentlyContinue) {
        Write-Log ("Docker Desktop is installed on this machine. This installer does NOT migrate an " +
                   "existing Docker Desktop deployment - it builds a clean WSL one alongside it.") "WARN"
        if (-not $Force) {
            $answer = Read-Host "Continue anyway? Type 'yes' to proceed"
            if ($answer -ne "yes") { Die "aborted at the operator's request." }
        }
    }
}

# A server must not sleep, and must not Fast Start. Fast Startup turns 'Shut
# down' into hibernating the kernel session: the next power-on is a resume, not
# a boot, so an At-startup task trigger never fires, and the WSL VM - which no
# hibernation preserves - is simply gone. The sleep timers are the other
# silent server-killer on a PC that was somebody's desktop until yesterday.
function Set-ServerPowerSettings {
    foreach ($setting in @("standby-timeout-ac", "hibernate-timeout-ac")) {
        $r = Invoke-Native -File "powercfg.exe" -Arguments @("/change", $setting, "0")
        if ($r.ExitCode -ne 0) { Write-Log "could not set ${setting} to never: $($r.Output.Trim())" "WARN" }
    }
    Write-Log "power: this PC will not sleep or hibernate on mains power"
    try {
        $key = "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power"
        $current = (Get-ItemProperty -Path $key -Name HiberbootEnabled -ErrorAction SilentlyContinue).HiberbootEnabled
        if ($null -ne $current -and [int]$current -ne 0) {
            Set-ItemProperty -Path $key -Name HiberbootEnabled -Value 0 -Type DWord -ErrorAction Stop
            Write-Log "power: turned Windows Fast Startup off (a Fast Startup power-on is not a boot, so the boot task never fired)"
        }
    } catch {
        Write-Log "could not turn Fast Startup off: $($_.Exception.Message)" "WARN"
    }
}

function Enable-WindowsFeatures {
    $needed = @("Microsoft-Windows-Subsystem-Linux", "VirtualMachinePlatform")
    $rebootRequired = $false
    foreach ($feature in $needed) {
        $state = Invoke-Native -File "dism.exe" -Arguments @(
            "/online", "/get-featureinfo", "/featurename:$feature")
        if ($state.Output -match "State\s*:\s*Enabled") {
            Write-Log "Windows feature ${feature}: already enabled"
            continue
        }
        Write-Log "enabling Windows feature ${feature}..."
        # DISM works with no internet, unlike the Store-based paths.
        $r = Invoke-Native -File "dism.exe" -Arguments @(
            "/online", "/enable-feature", "/featurename:$feature", "/all", "/norestart")
        if ($r.ExitCode -eq 3010) { $rebootRequired = $true }
        elseif ($r.ExitCode -ne 0) { Die "could not enable ${feature}: $($r.Output.Trim())" }
    }
    if ($rebootRequired) {
        Write-Log "" 
        Write-Log "REBOOT REQUIRED to finish enabling the Windows virtualization features." "WARN"
        Write-Log "Reboot, then run this exact command again to continue the install:" "WARN"
        Write-Log "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" "WARN"
        exit 2
    }
}

# Is a working, modern wsl.exe actually present? This is the ONLY thing that
# decides whether the WSL step succeeded. An installer exit code is a hint about
# one attempt; this is the outcome, and the outcome is what the next step needs.
#
# Only the modern (Store/MSI, 1.0+) wsl.exe counts, because only it runs
# systemd, and the whole self-healing design - Docker on boot, the watchdog
# timer - stands on systemd being PID 1. The inbox Windows 10 wsl.exe answers
# --status but has no --version, no systemd, and a per-session service a boot
# task cannot reach; a machine with only that one needs the bundled MSI just
# as a machine with no WSL at all does.
function Test-WslReady {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    return ($ver.ExitCode -eq 0 -and (($ver.Output -replace "`0","") -match "WSL[^\d]*\d+\.\d+"))
}

# The running WSL's version, or $null when there is no modern wsl.exe.
function Get-WslVersion {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    if ($ver.ExitCode -ne 0) { return $null }
    if (($ver.Output -replace "`0","") -match 'WSL[^\d]*(\d+)\.(\d+)\.(\d+)') {
        return [version]"$($Matches[1]).$($Matches[2]).$($Matches[3])"
    }
    return $null
}

function Get-WslVersionLine {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    if ($ver.ExitCode -ne 0) { return "unknown" }
    return ((($ver.Output -replace "`0","") -split "`r?`n" | Select-Object -First 1).Trim())
}

function Install-Wsl {
    # Already working (a re-run, or an up-to-date machine)? Do nothing. Installing
    # over a good WSL is how a working machine gets broken.
    if (Test-WslReady) {
        Write-Log "WSL already present and working: $(Get-WslVersionLine)"
        $r = Invoke-Wsl @("--set-default-version", "2") -TimeoutSec 60
        if ($r.ExitCode -ne 0) { Write-Log "could not set WSL default version 2: $($r.Output.Trim())" "WARN" }
        return
    }
    if ((Invoke-Wsl @("--status") -TimeoutSec 30).ExitCode -eq 0) {
        Write-Log ("an older inbox wsl.exe is present (no --version). It cannot run systemd, so nothing inside the " +
                   "distro would start on boot; installing the bundled WSL over it.") "WARN"
    }

    # Prefer the MSI we ship: it is the same modern wsl.exe on Windows 10 and 11,
    # needs no internet and no Microsoft Store (shops are frequently offline, and
    # the Store is commonly stripped from POS images).
    $msi = Get-ChildItem -Path $PSScriptRoot -Filter "wsl*.msi" -ErrorAction SilentlyContinue |
        Sort-Object Name -Descending | Select-Object -First 1

    $rebootHint = $false
    $lastCode   = $null
    $lastOutput = ""

    if ($msi) {
        # Windows Installer is single-threaded machine-wide. The DISM feature
        # enable we just ran, Windows Update, or a vendor updater will hold that
        # mutex and msiexec returns 1618 IMMEDIATELY. That is a "come back in a
        # moment", not a failure - and it is why this step used to fail on the
        # first run and pass on the second.
        $transient = @(1618, 1601)   # 1601 = Windows Installer service unavailable
        $attempts  = 5
        for ($i = 1; $i -le $attempts; $i++) {
            Write-Log "installing WSL from the bundled $($msi.Name) (attempt ${i}/${attempts})..."
            # Verbose MSI log next to our own, so a genuine failure is diagnosable
            # on site instead of being a bare exit code.
            $msiLog = Join-Path $LogDir ("wsl-msi-{0}.log" -f $i)
            try { if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null } } catch { }
            # No manual quoting: PowerShell quotes each array element itself, and
            # adding our own passes literal quote characters through to msiexec.
            $r = Invoke-Native -File "msiexec.exe" -Arguments @(
                "/i", $msi.FullName, "/quiet", "/norestart", "/l*v", $msiLog)
            $lastCode = $r.ExitCode; $lastOutput = $r.Output.Trim()

            if ($r.ExitCode -in @(0, 1638)) { break }          # 1638 = same-or-newer installed
            if ($r.ExitCode -in @(3010, 1641)) { $rebootHint = $true; break }
            if ($r.ExitCode -in $transient -and $i -lt $attempts) {
                Write-Log ("Windows Installer is busy (exit $($r.ExitCode)); another install is " +
                           "running. Waiting 20s and retrying.") "WARN"
                Start-Sleep -Seconds 20
                continue
            }
            Write-Log "msiexec returned $($r.ExitCode); verifying whether WSL works anyway. Log: ${msiLog}" "WARN"
            break
        }
    } else {
        Write-Log "no bundled WSL MSI found; falling back to 'wsl --update' (needs internet)" "WARN"
        $r = Invoke-Wsl @("--update") -TimeoutSec 1800
        $lastCode = $r.ExitCode; $lastOutput = $r.Output.Trim()
    }

    # THE decision. `wsl --update` reports non-zero when there is nothing to do,
    # and msiexec can report an odd code for an install that landed perfectly, so
    # neither exit code is trusted over the machine's actual state.
    if (Test-WslReady) {
        if ($null -ne $lastCode -and $lastCode -notin @(0, 1638)) {
            Write-Log "the WSL installer returned ${lastCode}, but WSL works - continuing." "WARN"
        }
        Write-Log "WSL: $(Get-WslVersionLine)"
        $r = Invoke-Wsl @("--set-default-version", "2") -TimeoutSec 60
        if ($r.ExitCode -ne 0) { Write-Log "could not set WSL default version 2: $($r.Output.Trim())" "WARN" }
        return
    }

    # Not working. Now the exit code earns its keep as the explanation.
    if ($rebootHint) {
        Write-Log ""
        Write-Log "WSL was installed but needs a REBOOT before it can run." "WARN"
        Write-Log "Reboot, then run this exact command again to continue the install:" "WARN"
        Write-Log "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" "WARN"
        exit 2
    }
    if (-not $msi) {
        Die ("WSL is not installed and could not be updated online (exit ${lastCode}). Put the WSL MSI " +
             "(wsl.<version>.x64.msi) next to this script and re-run. ${lastOutput}")
    }
    Die ("WSL still does not run after installing $($msi.Name) (msiexec exit ${lastCode}). " +
         "The verbose MSI log is under ${LogDir}. If this machine has never had the " +
         "virtualization features enabled, reboot once and re-run this script. ${lastOutput}")
}

# Where WSL reads .wslconfig from: the profile of the user wsl.exe runs as.
# Not $env:USERPROFILE - under the boot task that can name a profile WSL never
# reads (Default, or the system's), and a .wslconfig written there is one that
# never applies.
function Get-OwnerProfileDir {
    try {
        $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
        $row = Get-CimInstance -ClassName Win32_UserProfile -Filter "SID='${sid}'" -ErrorAction Stop
        if ($row -and $row.LocalPath -and (Test-Path $row.LocalPath)) { return "$($row.LocalPath)" }
    } catch { }
    return $env:USERPROFILE
}

function Write-WslConfig {
    # Host-wide WSL2 VM tuning. Unknown keys are ignored with a warning by older
    # wsl.exe, so we only write the modern ones when the running WSL supports
    # them - otherwise every single `wsl` call prints noise into our logs. And
    # each key goes under ITS section: WSL reads a key only there, so a right
    # key in the wrong section is a warning and nothing else.
    $totalGb = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB)
    $memGb   = [int][math]::Max(4, [math]::Min(8, [math]::Floor($totalGb / 2)))
    $cpus    = [int][math]::Max(2, [math]::Min(4, [Environment]::ProcessorCount))

    $version = Get-WslVersion
    $modern  = ($null -ne $version -and $version.Major -ge 2)

    $lines = @(
        $WslConfigMarker,
        "[wsl2]",
        "memory=${memGb}GB",
        "processors=${cpus}",
        "swap=2GB",
        "# OFF on purpose. Every till reaches the stack through the netsh portproxy",
        "# forward (see -Boot), which listens on 0.0.0.0 and so also answers",
        "# 127.0.0.1 for a till on this same PC. WSL's own relay would bind",
        "# 127.0.0.1 on the same ports, and whichever of the two binds first can stop",
        "# the other from binding at all - on a fresh install that left the server's",
        "# own till working and every other device unable to find the server.",
        "localhostForwarding=false",
        "guiApplications=false",
        "nestedVirtualization=false"
    )
    # No sparseVhd and no autoMemoryReclaim, on purpose: WSL 2.5.6+ refuses
    # sparse disks over a data-corruption risk, and "gradual" reclaim breaks the
    # Docker daemon running as a service. keep-pointy-running.ps1 removes both
    # from a file an older bootstrap wrote, so the two scripts agree on it.
    if ($modern) {
        $lines += @(
            "# Never idle-stop the VM: it is a server, not a developer shell. This keeps",
            "# the empty VM; what keeps the DISTRO is the keep-alive client.",
            "vmIdleTimeout=-1"
        )
    }
    if ($null -ne $version -and $version -ge [version]"2.5.4") {
        $lines += @(
            "[general]",
            "# Belt and braces for the keep-alive client: never power the distro off for",
            "# being idle. Only WSL 2.5.4+ knows this key; older ones warn on every call.",
            "instanceIdleTimeout=-1"
        )
    }

    $path = Join-Path (Get-OwnerProfileDir) ".wslconfig"
    $content = ($lines -join "`n") + "`n"
    $previous = if (Test-Path $path) { [System.IO.File]::ReadAllText($path) } else { "" }
    # Whether anything changed: WSL reads this file only when its VM starts.
    if ($previous -eq $content) { return $false }
    # LF + no BOM: the WSL config parser rejects a BOM outright.
    [System.IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Log "wrote ${path} (memory=${memGb}GB, processors=${cpus})"
    return $true
}

# On a re-run over a live install, a changed .wslconfig does nothing until the
# WSL VM restarts. Stop the stack cleanly first - `wsl --shutdown` on its own
# kills Postgres mid-write - then restart the VM here, while an operator is at
# the machine anyway. The rest of the install brings the stack back up.
function Restart-WslVm {
    Write-Log "restarting WSL so the new .wslconfig applies; the stack comes back up below"
    Invoke-Guest "cd '${GuestDir}' && test -f docker-compose.yml && docker compose --env-file .env -f docker-compose.yml stop" -TimeoutSec 600 | Out-Null
    $r = Invoke-Wsl @("--shutdown") -TimeoutSec 120
    if ($r.ExitCode -ne 0) {
        Write-Log "wsl --shutdown failed: $($r.Output.Trim()). Restart Windows once to apply .wslconfig." "WARN"
    }
}

# Shops installed by an older bootstrap have an older generated .wslconfig:
# localhostForwarding still on, keys in sections WSL ignores, no idle setting.
# Converge it - only if this script generated it, never an operator's own - so
# the fix reaches them at the next start of the WSL VM, i.e. the next Windows
# restart. Nothing is restarted from here: that would take the tills down in
# the middle of trading.
function Update-GeneratedWslConfig {
    try {
        $path = Join-Path (Get-OwnerProfileDir) ".wslconfig"
        if (-not (Test-Path $path)) { return }
        $text = [System.IO.File]::ReadAllText($path)
        if (-not $text.StartsWith($WslConfigMarker)) { return }
        if (Write-WslConfig) {
            Write-Log "updated the generated .wslconfig; it takes effect the next time Windows restarts"
        }
    } catch {
        Write-Log "could not update .wslconfig: $($_.Exception.Message)" "WARN"
    }
}

function Import-Distro {
    if (Test-DistroExists) {
        Write-Log "distro '${Distro}' is already registered; leaving it and its data alone"
        return
    }
    $rootfs = Get-ChildItem -Path $PSScriptRoot -Filter "pointy-wsl-rootfs*.tar*" -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if (-not $rootfs) {
        Die ("no distro image found. Expected pointy-wsl-rootfs.tar.gz next to this script - " +
             "is this a complete bundle?")
    }
    $target = Join-Path $InstallRoot "distro"
    New-Item -ItemType Directory -Force -Path $target | Out-Null
    Write-Log "importing '${Distro}' from $($rootfs.Name) into ${target} (this takes a few minutes)..."
    $r = Invoke-Wsl @("--import", $Distro, $target, $rootfs.FullName, "--version", "2") -TimeoutSec 7200
    if ($r.ExitCode -ne 0) {
        $detail = ($r.Output -replace "`0", "").Trim()
        Die "wsl --import failed: ${detail}"
    }
    Write-Log "distro '${Distro}' imported"
}

function Set-GuestTimezone {
    # A freshly imported distro is UTC. Z-reports, day rollups, holiday tagging
    # and shift boundaries are all business-local, so an unset timezone silently
    # files the evening's sales on the wrong day.
    try {
        $winTz = (Get-TimeZone).Id
        $map = Join-Path $PSScriptRoot "timezone-map.txt"
        $ianaTz = $null
        if (Test-Path $map) {
            foreach ($line in (Get-Content $map)) {
                if ($line -match '^\s*#') { continue }
                $parts = $line -split '\|', 2
                if ($parts.Count -eq 2 -and $parts[0].Trim() -eq $winTz) { $ianaTz = $parts[1].Trim(); break }
            }
        }
        if (-not $ianaTz) {
            Write-Log "no IANA mapping for Windows time zone '${winTz}'; the distro stays on UTC." "WARN"
            Write-Log "  Set it by hand:  wsl -d ${Distro} -u root ln -sf /usr/share/zoneinfo/<Area/City> /etc/localtime" "WARN"
            return
        }
        Invoke-Guest "ln -sf /usr/share/zoneinfo/${ianaTz} /etc/localtime && echo ${ianaTz} > /etc/timezone" | Out-Null
        Write-Log "distro time zone set to ${ianaTz} (from Windows '${winTz}')"
    } catch {
        Write-Log "could not set the distro time zone: $($_.Exception.Message)" "WARN"
    }
}

function Copy-BundleIntoGuest {
    # Stream the bundle in as a tar over stdin. A Windows-side file copy would
    # go through DrvFs and can rewrite line endings; a single CRLF in a .sh makes
    # bash fail with "\r: command not found", and a CRLF in .env puts a trailing
    # \r inside the generated Postgres password - a failure that only shows up
    # later, as an unexplained authentication error.
    Write-Log "copying the bundle into ${GuestDir} inside the distro..."
    Invoke-Guest "mkdir -p ${GuestDir}" | Out-Null

    $tar = Join-Path $env:TEMP ("pointy-bundle-{0}.tar" -f ([guid]::NewGuid().ToString("N")))
    try {
        # bsdtar ships in Windows 10 17063+.
        #
        # wsl/ goes IN (minus its install-only inputs): update.sh adopts
        # wsl/bootstrap-wsl.ps1 out of each new bundle, and -Boot copies it back
        # out to Windows - that is the only way a fix to the LAN bridge ever
        # reaches an installed shop. The rootfs tarball and the MSI are excluded:
        # they are one-time install inputs and together are most of the bundle.
        $r = Invoke-Native -File "tar.exe" -Arguments @(
            "-cf", $tar, "-C", $BundleRoot,
            "--exclude", "./wsl/pointy-wsl-rootfs*",
            "--exclude", "./wsl/*.msi",
            ".")
        if ($r.ExitCode -ne 0) { Die "could not archive the bundle: $($r.Output.Trim())" }

        $guestTar = "/tmp/pointy-bundle.tar"
        $winTar   = $tar -replace '\\', '/'
        # Read it from the Windows filesystem in BINARY through /mnt - the copy
        # is byte-exact because tar content is opaque to DrvFs.
        $mnt = "/mnt/" + $winTar.Substring(0,1).ToLower() + $winTar.Substring(2)
        $x = Invoke-Guest "cp '${mnt}' ${guestTar} && tar -xf ${guestTar} -C ${GuestDir} && rm -f ${guestTar}" -TimeoutSec 3600
        if ($x.ExitCode -ne 0) { Die "could not unpack the bundle inside the distro: $($x.Output)" }

        Invoke-Guest "chmod +x ${GuestDir}/*.sh 2>/dev/null; true" | Out-Null
        # Belt and braces: strip any CR that survived, so bash never sees one.
        Invoke-Guest "sed -i 's/\r$//' ${GuestDir}/*.sh 2>/dev/null; true" | Out-Null
        Write-Log "bundle unpacked into ${GuestDir}"
    } finally {
        Remove-Item $tar -ErrorAction SilentlyContinue
    }
}

function Invoke-GuestInstall {
    Write-Log "running install.sh inside the distro - this is where the stack actually comes up..."
    # Stream it live: this step loads images and starts Postgres, and takes
    # minutes. A silent installer here reads as a hang.
    $code = 1
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        # `cd` inside the command rather than wsl.exe's --cd, which only exists
        # in newer wsl.exe builds.
        & wsl.exe -d $Distro -u root -- bash -lc "cd '$GuestDir' && bash ./install.sh"
        $code = $LASTEXITCODE
    } finally { $ErrorActionPreference = $prev }
    if ($code -ne 0) { Die "install.sh failed inside the distro (exit ${code}). See the output above." }
    Write-Log "install.sh completed"
}

# The scheduled task must NOT point into the extracted bundle folder: an
# operator tidying up their Downloads directory would silently disable the LAN
# bridge, and the bundle is not where updates land anyway. Keep a copy at a
# stable path and run that.
function Install-BootstrapToStablePath {
    New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null
    foreach ($name in @("bootstrap-wsl.ps1", "keep-pointy-running.ps1", "collect-diagnostics.ps1", "timezone-map.txt")) {
        $src = Join-Path $PSScriptRoot $name
        if (Test-Path $src) { Copy-Item -Force $src (Join-Path $InstallRoot $name) }
    }
    Write-Log "installed the bootstrap to ${InstallRoot}"
}

# Promote a newer bootstrap that arrived inside the distro with a release
# bundle. This mirrors update-agent.sh's self-promote: the Windows half of the
# deployment has to be updatable from the Linux half, or every shop keeps the
# bridge it was installed with forever. Returns $true only when the installed
# copy verifiably changed - the supervisor then hands over to it.
function Update-BootstrapFromGuest {
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    if ($PSCommandPath -ne $stable) { return $false }   # only self-update the installed copy

    $guestPath = "${GuestDir}/wsl/bootstrap-wsl.ps1"
    $r = Invoke-Guest "test -f '${guestPath}' && sha256sum '${guestPath}' | cut -c1-64"
    if ($r.ExitCode -ne 0) { return $false }
    $guestHash = ($r.Output -replace "`0", "").Trim()
    if ($guestHash -notmatch '^[0-9a-f]{64}$') { return $false }

    $localHash = (Get-FileHash -Path $stable -Algorithm SHA256).Hash.ToLower()
    if ($guestHash -eq $localHash) { return $false }

    Write-Log "a newer bootstrap arrived with a release update; promoting it"
    foreach ($name in @("bootstrap-wsl.ps1", "keep-pointy-running.ps1", "collect-diagnostics.ps1", "timezone-map.txt")) {
        $win = (Join-Path $InstallRoot $name) -replace '\\', '/'
        $mnt = "/mnt/" + $win.Substring(0,1).ToLower() + $win.Substring(2)
        Invoke-Guest "test -f '${GuestDir}/wsl/${name}' && cp -f '${GuestDir}/wsl/${name}' '${mnt}'" | Out-Null
    }
    # Only a copy that verifiably landed is a promotion; anything else would
    # hand over to the very same file, forever.
    $localHash = (Get-FileHash -Path $stable -Algorithm SHA256).Hash.ToLower()
    if ($localHash -ne $guestHash) {
        Write-Log "the promoted bootstrap does not match the bundle's copy; keeping the running one" "WARN"
        return $false
    }
    return $true
}

# The install re-registers the task, which ends its running supervisor at a
# moment of Task Scheduler's choosing. End it here instead, at the start, so
# the installer's own anchor is what carries the distro through the install.
function Stop-BootTask {
    try {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        if (-not $task) { return }
        if ("$($task.State)" -eq "Running") {
            Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop
            Write-Log "stopped the running '${TaskName}' supervisor for the install; it is started again at the end"
        }
    } catch {
        Write-Log "could not stop the '${TaskName}' task: $($_.Exception.Message)" "WARN"
    }
}

function Register-BootTask {
    # ONE task. It runs the supervisor: boots the distro (systemd then runs the
    # watchdog, the update agent and the stack), holds it open, and re-points
    # the LAN bridge. Everything else that used to be a Windows scheduled task
    # is now a systemd unit inside Linux.
    #
    # -Disabled registers it off, in one step, so its 5-minute trigger cannot
    # start a supervisor beside the keeper that replaces it (see Install-Keeper).
    param([switch]$Disabled)
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument (
        "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$stable`" " +
        "-Boot -Distro `"$Distro`" -InstallRoot `"$InstallRoot`" -ApiPort $ApiPort -WebPort $WebPort")

    $atStartup = New-ScheduledTaskTrigger -AtStartup
    $atStartup.Delay = "PT30S"
    # A clock trigger as well. Windows does not count a Fast Startup power-on
    # as a boot, so on such a machine an At-startup trigger alone never fires;
    # and should the supervisor ever exit (a handover to a newer bootstrap, a
    # crash), the repetition re-launches it within 5 minutes. While it runs,
    # IgnoreNew makes every repetition a no-op.
    $everyFiveMinutes = New-ScheduledTaskTrigger -Once -At (Get-Date).Date `
        -RepetitionInterval (New-TimeSpan -Minutes 5) `
        -RepetitionDuration (New-TimeSpan -Days 3650)

    # No execution time limit: the supervisor is meant to run until shutdown.
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -MultipleInstances IgnoreNew `
        -Disable:$Disabled

    # S4U runs as this user WITHOUT an interactive session and WITHOUT storing a
    # password. That is the whole point of the migration: Docker Desktop could
    # only run inside a logged-in session, which forced shops to enable Windows
    # auto-logon with the password in clear text under Winlogon. This does not.
    #
    # The distro is registered to THIS user's SID, so the task must run as this
    # user - not SYSTEM, which cannot see it.
    $userId = "$env:USERDOMAIN\$env:USERNAME"
    try {
        $principal = New-ScheduledTaskPrincipal -UserId $userId -LogonType S4U -RunLevel Highest
        Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($atStartup, $everyFiveMinutes) `
            -Principal $principal -Settings $settings -Force -ErrorAction Stop | Out-Null
        $when = "at startup, and every 5 minutes"
        if ($Disabled) { $when += "; registered OFF, the keeper replaces it (its -Uninstall turns this back on)" }
        Write-Log "registered scheduled task '${TaskName}' as ${userId} (LogonType=S4U): ${when}"
    } catch {
        # We deliberately do NOT prompt for the password and store it ourselves.
        # Task Scheduler asks for it in its own secure dialog and keeps it in the
        # protected credential store; routing it through this script would put
        # the shop's password in a PowerShell variable for no benefit.
        Write-Log "could not register '${TaskName}' automatically: $($_.Exception.Message)" "ERROR"
        # Registered off, it is only the keeper's fallback: not worth stopping
        # the install that sets the keeper up.
        if ($Disabled) {
            Write-Log "carrying on: the keeper keeps the distro alive, and '${TaskName}' would only be its fallback" "WARN"
            return
        }
        Die ("Create the task by hand in Task Scheduler (taskschd.msc):`n" +
             "  Name    : ${TaskName}`n" +
             "  Run as  : ${userId}   <- must be THIS user; WSL distros are per-user`n" +
             "            tick 'Run whether user is logged on or not'`n" +
             "            tick 'Run with highest privileges'`n" +
             "  Triggers: At startup (delay 30s), AND daily at 00:00 repeating every 5 minutes`n" +
             "            for 3650 days; settings: no time limit, do not start a new instance`n" +
             "  Action  : powershell.exe`n" +
             "  Args    : -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$stable`" -Boot")
    }
}

function Enable-BootTask {
    try {
        Enable-ScheduledTask -TaskName $TaskName -ErrorAction Stop | Out-Null
        Write-Log "turned the '${TaskName}' task on: with no keeper, its supervisor keeps the distro alive"
    } catch {
        Write-Log "could not turn the '${TaskName}' task on: $($_.Exception.Message)" "ERROR"
    }
}

# What keeps a shop's distro alive: keep-pointy-running.ps1, a minimised window
# in the signed-in session holding a wsl.exe open. Shop staff found that by
# hand - a PowerShell window running `wsl`, left open - and it is the one
# arrangement proven on shop PCs. Its -Install registers the PointyKeepAlive
# task for this user, turns PointyWSL off, and starts the window now. $false
# when it could not be installed; the caller then falls back to PointyWSL.
function Install-Keeper {
    param([string]$Path)
    Write-Log "setting up the keeper: $Path -Install"
    $r = Invoke-Native -File "powershell.exe" -Arguments @("-NoProfile", "-ExecutionPolicy", "Bypass", "-File", $Path,
        "-Install", "-Distro", $Distro, "-ApiPort", "$ApiPort", "-WebPort", "$WebPort")
    # Its own log lines (keepalive.log has them too), for the operator watching.
    foreach ($line in @("$($r.Output)" -split "`r?`n")) { if ($line.Trim()) { Write-Host "    $line" } }
    if ($r.ExitCode -ne 0) {
        Write-Log "the keeper could not be set up (exit $($r.ExitCode)); the '${TaskName}' task keeps the distro alive instead" "ERROR"
        return $false
    }
    return $true
}

# Is keep-pointy-running.ps1 installed and switched on? Then it keeps the
# distro alive, and the supervisor must not run beside it.
function Test-KeeperInstalled {
    try {
        $task = Get-ScheduledTask -TaskName $KeeperTaskName -ErrorAction Stop
        return ("$($task.State)" -ne "Disabled")
    } catch { return $false }
}

# After a one-off pass the distro must outlive the operator's window: start
# whichever keeps it alive here.
function Start-KeepAliveTask {
    if (-not (Test-KeeperInstalled)) { return (Start-SupervisorTask) }
    try {
        $task = Get-ScheduledTask -TaskName $KeeperTaskName -ErrorAction Stop
        if ("$($task.State)" -eq "Running") { return $true }
        Start-ScheduledTask -TaskName $KeeperTaskName -ErrorAction Stop
        Write-Log "started the '${KeeperTaskName}' task; its window holds the distro open from here on"
        return $true
    } catch {
        Write-Log ("could not start the '${KeeperTaskName}' task: $($_.Exception.Message). It starts by itself " +
                   "within a minute while its Windows user is signed in.") "WARN"
        return $false
    }
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if ($Boot) {
    if (-not (Test-Admin)) {
        Write-Log "not elevated: the distro can be started from here, but the LAN bridge and firewall cannot be changed" "WARN"
    }
    if ($Once) {
        # One pass for an operator at the keyboard: start the distro if it is
        # down, re-point and prove the bridge, and make sure the keeper (or
        # the supervisor) is up so the distro outlives this window.
        $ok = Invoke-BootReconcile
        Start-KeepAliveTask | Out-Null
        if ($ok) { exit 0 } else { exit 1 }
    }
    if (Test-KeeperInstalled) {
        # Turned back on by hand, or started in the moment before the keeper
        # turned it off: either way the keeper holds the distro, and two
        # keepers fight over it.
        Write-Log "the '${KeeperTaskName}' task (keep-pointy-running.ps1) keeps the distro alive here; the supervisor stands down"
        exit 0
    }
    if (Enter-SupervisorLock) {
        Invoke-Supervise
        exit 0
    }
    Write-Log "a supervisor is already running (see ${SupervisorStateFile}); doing one reconcile pass instead"
    if (Invoke-BootReconcile) { exit 0 } else { exit 1 }
}

Write-Log "=== Pointy on-prem WSL bootstrap ==="
Assert-Preflight
Set-ServerPowerSettings
Enable-WindowsFeatures
Install-Wsl
Stop-BootTask
$reinstall = Test-DistroExists
if ((Write-WslConfig) -and $reinstall) { Restart-WslVm }
Import-Distro
# From here to the end the distro must stay up: with no client attached, WSL
# would power it off 15 s after each step below returns, and the next step
# would boot it again. It stays attached until this user signs out, so the
# distro is up while the keeper (or the supervisor) attaches its own.
Start-AnchorIfMissing | Out-Null
Set-GuestTimezone
Copy-BundleIntoGuest
Invoke-GuestInstall
Install-BootstrapToStablePath
# The keeper keeps the distro alive whenever the bundle has it; PointyWSL is
# registered beside it, off, for its -Uninstall to fall back to.
$keeperScript = Join-Path $PSScriptRoot "keep-pointy-running.ps1"
$useKeeper = Test-Path $keeperScript
Register-BootTask -Disabled:$useKeeper
Invoke-BootReconcile | Out-Null
$keeperInstalled = $useKeeper -and (Install-Keeper -Path $keeperScript)
if (-not $keeperInstalled) {
    if ($useKeeper) { Enable-BootTask }
    Start-SupervisorTask | Out-Null
}
Write-FirewallWarnings

$ip = Get-WslIp
$lan = @(Get-LanIPv4)
if ($lan.Count -eq 0) { $lan = @("<this-pc-lan-ip>") }

Write-Log ""
Write-Log "Done. The stack runs inside WSL distro '${Distro}' (VM address ${ip})."
if ($keeperInstalled) {
    Write-Log "A minimised 'Pointy server' window holds the distro open whenever ${env:USERNAME} is signed in,"
    Write-Log "and starts it again within seconds if WSL is shut down or updated. After a restart the server"
    Write-Log "stays down until ${env:USERNAME} signs in, so let Windows sign in by itself (Sysinternals Autologon)."
} else {
    Write-Log "The '${TaskName}' task holds the distro open from boot to shutdown, no logon needed,"
    Write-Log "and starts it again within seconds if WSL is shut down or updated."
}
Write-Log ""
foreach ($address in $lan) {
    Write-Log "  Tills reach it at : http://${address}:${ApiPort}"
    Write-Log "  Browser app       : http://${address}:${WebPort}"
}
Write-Log "  Shell in          : wsl -d ${Distro} -u root --cd ${GuestDir}"
Write-Log "  Stack status      : wsl -d ${Distro} -u root --cd ${GuestDir} -- docker compose ps"
Write-Log "  Watchdog log      : wsl -d ${Distro} -u root -- journalctl -u pointy-watchdog -f"
if ($keeperInstalled) {
    Write-Log "  Keeper            : Get-ScheduledTask ${KeeperTaskName}; $(Join-Path $env:ProgramData 'Pointy\logs\keepalive.log')"
} else {
    Write-Log "  Supervisor        : Get-ScheduledTask ${TaskName}; $(Join-Path $InstallRoot 'supervisor-state.json')"
}
Write-Log "  If it misbehaves  : powershell -ExecutionPolicy Bypass -File `"$(Join-Path $InstallRoot 'collect-diagnostics.ps1')`""
Write-Log ""
Write-Log "Everything from here on is Linux. There is no second set of Windows scripts:"
Write-Log "updates, healing and the watchdog all run as systemd units inside the distro."
