<#
  Pointy on-prem - the ONLY PowerShell we ship.

  Everything that deploys, updates, watches and heals the stack is bash under
  deploy/onprem/*.sh, running inside a WSL2 distro. This file exists solely
  because three jobs cannot be done from Linux:

    1. INSTALL  - enabling the Windows features, installing WSL, importing the
                  distro, and registering the boot task.
    2. -Boot    - KEEPING THE DISTRO ALIVE. WSL powers a distro off about 15 s
                  after its last Windows-side client (a wsl.exe) exits, and
                  systemd running inside does not count. So the boot task holds
                  one hidden wsl.exe open for as long as Windows is up, and
                  starts the distro again the moment that client dies (a
                  `wsl --shutdown`, Windows Update servicing WSL, a logoff).
    3. -Boot    - bridging the Windows LAN into the NAT'd WSL VM (portproxy +
                  firewall), which must be re-done every time the VM starts
                  because its IP changes each time.

  It deliberately contains NO deployment logic. It hands off to install.sh
  inside the distro and never duplicates it.

      # First install (elevated PowerShell, from the extracted bundle):
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1

      # What the scheduled task runs at boot, and re-runs should it ever exit:
      # supervise the distro and the LAN bridge until Windows shuts down.
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1 -Boot

      # One reconcile pass that returns - for an operator at the keyboard:
      powershell -ExecutionPolicy Bypass -File .\wsl\bootstrap-wsl.ps1 -Boot -Once

  Re-run the install form any time; it is idempotent.
#>
[CmdletBinding()]
param(
    # Supervise: start the distro, hold it open, re-point the LAN bridge at it,
    # and keep doing so until Windows stops. What the PointyWSL task runs.
    [switch]$Boot,
    # With -Boot: one reconcile pass, then return. For an operator at the
    # keyboard; the running supervisor is left alone (and started if absent).
    [switch]$Once,
    # Distro name. Changing this on an existing install orphans the old one.
    [string]$Distro = "Pointy",
    # Where the distro's ext4.vhdx lives. MUST be a local NTFS disk.
    [string]$InstallRoot = (Join-Path $env:ProgramData "Pointy"),
    # LAN ports published from inside WSL to the shop network.
    [int]$ApiPort = 8000,
    [int]$WebPort = 80,
    # Skip the interactive confirmation when Docker Desktop is present.
    [switch]$Force
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

# wsl.exe emits UTF-16LE by default, which turns every parsed line into
# "P\0o\0i\0n\0t\0y\0". WSL_UTF8 makes it emit UTF-8 (wsl.exe 0.64+); we still
# decode defensively below for the inbox Windows 10 build that ignores it.
$env:WSL_UTF8 = "1"

$BundleRoot  = Split-Path -Parent $PSScriptRoot   # ...\<bundle>\  (wsl\ is one down)
$LogDir      = Join-Path $InstallRoot "logs"
$LogFile     = Join-Path $LogDir "bootstrap.log"
$StateFile   = Join-Path $InstallRoot "bridge-state.json"
$TaskName    = "PointyWSL"
$GuestDir    = "/opt/pointy"
# First line of the .wslconfig this script writes; how -Boot tells its own file
# from one an operator wrote by hand.
$WslConfigMarker = "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem."
# The keep-alive client ("anchor") the supervisor holds open - see -Boot below.
$AnchorCommand  = "/bin/sleep"
$AnchorArgument = "infinity"
$SupervisorMutexName = "Global\PointyWSL-Supervisor"
$SupervisorStateFile = Join-Path $InstallRoot "supervisor-state.json"
# How often the supervisor re-proves the LAN bridge while everything is quiet.
$ReconcileIntervalSec = 300
# Consecutive checks the distro may fail to answer before it is terminated and
# started fresh. Three, a minute apart: a VM that has not answered `true` for
# that long is not busy, it is gone.
$DistroFailuresBeforeTerminate = 3
# Why the last `wsl --list` returned nothing: "" when it worked, else its
# error. An absent distro and a WSL service that is mid-update look the same
# to a caller that only counts names.
$script:WslListError = ""
# Run wsl.exe the classic way (PowerShell's own call operator, no timeout)
# instead of the bounded way. Select-WslRunner turns this on, on a machine
# where wsl.exe answers only the classic way.
$script:UseClassicRunner = $false

function Write-Log {
    param([string]$Message, [string]$Level = "INFO")
    $line = "{0} [pointy-wsl] {1} {2}" -f (Get-Date -Format "yyyy-MM-ddTHH:mm:ss"), $Level, $Message
    switch ($Level) {
        "WARN"  { Write-Host $line -ForegroundColor Yellow }
        "ERROR" { Write-Host $line -ForegroundColor Red }
        default { Write-Host $line }
    }
    try {
        if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null }
        # The supervisor writes a line every few minutes for years; keep one
        # generation behind so a till's disk never fills with our diary.
        if ((Test-Path $LogFile) -and ((Get-Item $LogFile).Length -gt 5MB)) {
            Move-Item -Force $LogFile ($LogFile -replace '\.log$', '.1.log')
        }
        Add-Content -Path $LogFile -Value $line -Encoding UTF8
    } catch { }   # never let logging break the install
}

function Die { param([string]$Message) Write-Log $Message "ERROR"; exit 1 }

function Test-Admin {
    (New-Object Security.Principal.WindowsPrincipal(
        [Security.Principal.WindowsIdentity]::GetCurrent())
    ).IsInRole([Security.Principal.WindowsBuiltinRole]::Administrator)
}

# Run a native command and return its stdout, without $ErrorActionPreference
# turning ordinary non-zero exits (which wsl.exe uses for "not installed") into
# terminating errors.
function Invoke-Native {
    param([string]$File, [string[]]$Arguments)
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        $out = & $File @Arguments 2>&1
        return [pscustomobject]@{
            ExitCode = $LASTEXITCODE
            Output   = ($out | Out-String)
        }
    } finally { $ErrorActionPreference = $prev }
}

# One argument, quoted the way CommandLineToArgvW un-quotes it, so a command
# line rebuilt from an array carries spaces and quotes through intact.
function ConvertTo-NativeArgument {
    param([string]$Value)
    if ($Value -ne "" -and $Value -notmatch '[\s"]') { return $Value }
    $sb = New-Object System.Text.StringBuilder
    [void]$sb.Append('"')
    $backslashes = 0
    foreach ($ch in $Value.ToCharArray()) {
        if ($ch -eq [char]'\') { $backslashes++; continue }
        if ($ch -eq [char]'"') {
            [void]$sb.Append([char]'\', $backslashes * 2 + 1)
            [void]$sb.Append([char]'"')
            $backslashes = 0
            continue
        }
        if ($backslashes) { [void]$sb.Append([char]'\', $backslashes); $backslashes = 0 }
        [void]$sb.Append($ch)
    }
    if ($backslashes) { [void]$sb.Append([char]'\', $backslashes * 2) }
    [void]$sb.Append('"')
    return $sb.ToString()
}

# Like Invoke-Native, but bounded. A wedged WSL service answers nothing, ever,
# and a supervisor blocked on it forever is a supervisor that never restarts
# anything.
#
# System.Diagnostics.Process, deliberately not Start-Process: on Windows
# PowerShell 5.1 a process from `Start-Process -PassThru` reports a NULL exit
# code once it has exited, so every wsl.exe call read as a failure and the
# installer declared a working WSL broken. A Process that started the child
# itself owns the handle and its ExitCode is real. Both pipes are drained by
# background tasks so neither can fill up and stall the child.
function Invoke-NativeTimeout {
    param([string]$File, [string[]]$Arguments, [int]$TimeoutSec = 120)
    $line = (($Arguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
    $p = $null
    try {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName               = $File
        $psi.Arguments              = $line
        $psi.UseShellExecute        = $false
        $psi.CreateNoWindow         = $true
        $psi.RedirectStandardOutput = $true
        $psi.RedirectStandardError  = $true
        $psi.StandardOutputEncoding = [System.Text.Encoding]::UTF8
        $psi.StandardErrorEncoding  = [System.Text.Encoding]::UTF8
        $p = New-Object System.Diagnostics.Process
        $p.StartInfo = $psi
        [void]$p.Start()
        $outTask = $p.StandardOutput.ReadToEndAsync()
        $errTask = $p.StandardError.ReadToEndAsync()
        if (-not $p.WaitForExit($TimeoutSec * 1000)) {
            try { $p.Kill() } catch { }
            return [pscustomobject]@{ ExitCode = -1; TimedOut = $true
                Output = "timed out after ${TimeoutSec}s: ${File} ${line}" }
        }
        $text = ""
        foreach ($task in @($outTask, $errTask)) {
            # Bounded too: a grandchild holding the pipe must not hold us.
            if ($task.Wait(10000)) { $text += $task.Result }
        }
        return [pscustomobject]@{ ExitCode = [int]$p.ExitCode; TimedOut = $false; Output = $text }
    } catch {
        return [pscustomobject]@{ ExitCode = -1; TimedOut = $false; Output = "could not run ${File}: $($_.Exception.Message)" }
    } finally {
        if ($p) { try { $p.Dispose() } catch { } }
    }
}

function Invoke-Wsl {
    param([string[]]$Arguments, [int]$TimeoutSec = 120)
    if ($script:UseClassicRunner) {
        try {
            $r = Invoke-Native -File "wsl.exe" -Arguments $Arguments
            return [pscustomobject]@{ ExitCode = $r.ExitCode; TimedOut = $false; Output = $r.Output }
        } catch {
            return [pscustomobject]@{ ExitCode = -1; TimedOut = $false; Output = "could not run wsl.exe: $($_.Exception.Message)" }
        }
    }
    Invoke-NativeTimeout -File "wsl.exe" -Arguments $Arguments -TimeoutSec $TimeoutSec
}

# Run a command inside the distro as root, returning trimmed stdout.
function Invoke-Guest {
    param([string]$Command, [int]$TimeoutSec = 120)
    $r = Invoke-Wsl @("-d", $Distro, "-u", "root", "--", "bash", "-lc", $Command) -TimeoutSec $TimeoutSec
    return [pscustomobject]@{ ExitCode = $r.ExitCode; Output = $r.Output.Trim() }
}

# Which way can THIS machine run wsl.exe? On one shop PC every bounded call
# (a hidden child, pipes read by .NET) came back empty within a second, while
# the classic call (PowerShell's call operator, the shared console) answered
# as it always had. Rather than guess at the cause from a desk, try both,
# prefer the bounded one, fall back to the classic one, and write down what
# each returned. Cheap (one `wsl --version` each) and run once per start.
function Select-WslRunner {
    $script:UseClassicRunner = $false
    $bounded = Invoke-NativeTimeout -File "wsl.exe" -Arguments @("--version") -TimeoutSec 30
    if ($bounded.ExitCode -eq 0 -and (($bounded.Output -replace "`0", "") -match '[0-9]+\.[0-9]+\.[0-9]+')) { return }
    $classic = $null
    try { $classic = Invoke-Native -File "wsl.exe" -Arguments @("--version") } catch { return }
    if ($classic.ExitCode -eq 0 -and (($classic.Output -replace "`0", "") -match '[0-9]+\.[0-9]+\.[0-9]+')) {
        $script:UseClassicRunner = $true
        $seen = @((($bounded.Output -replace "`0", "") -split "`r?`n") | Where-Object { $_.Trim() } | Select-Object -First 1)
        Write-Log ("wsl.exe answers only when run the classic way on this machine (the bounded way: exit " +
                   "$($bounded.ExitCode), '$(($seen -join '').Trim())'). Using the classic way from now on; " +
                   "its calls have no timeout.") "WARN"
    }
}

function Get-RegisteredDistros {
    $r = Invoke-Wsl @("--list", "--quiet") -TimeoutSec 60
    $script:WslListError = ""
    if ($r.ExitCode -ne 0) {
        $first = @((($r.Output -replace "`0", "") -split "`r?`n") | Where-Object { $_.Trim() } | Select-Object -First 1)
        $script:WslListError = "wsl --list failed (exit $($r.ExitCode)): $(($first -join '').Trim())"
        return @()
    }
    # Strip NULs in case WSL_UTF8 was ignored (inbox Windows 10 wsl.exe).
    return ($r.Output -replace "`0", "") -split "`r?`n" |
        ForEach-Object { $_.Trim() } | Where-Object { $_ }
}

function Test-DistroExists { (Get-RegisteredDistros) -contains $Distro }


# ---------------------------------------------------------------------------
# Keeping the distro alive.
#
# WSL powers a distro off about 15 seconds after its last Windows-side client
# (a wsl.exe) exits. systemd, dockerd and Postgres running inside do NOT count;
# only a process WSL itself launched from Windows does. So a boot task that
# starts the distro and returns has, in effect, started it for 15 seconds -
# and the shops that "kept a PowerShell window open" had found the only fix.
#
# This is documented ("systemd services will NOT keep your WSL instance
# alive" - learn.microsoft.com/windows/wsl/systemd) and it is how the service
# is written: WslService registers a wait on the CALLING WINDOWS PROCESS and
# queues the instance's termination timer (general.instanceIdleTimeout, 15 s)
# when the last such process is gone; nothing inside Linux is consulted. On
# the WSL the installer bundles, that termination is a hard power-off of the
# VM - Postgres dies mid-write - and the old 5-minute task was therefore
# hard-killing the stack up to 288 times a day.
#
# `vmIdleTimeout=-1` in .wslconfig keeps the empty VM, not the distro. The
# `[general] instanceIdleTimeout` that does keep the distro exists only from
# WSL 2.5.4, and the installer bundles 2.3.26, so it cannot be the fix for the
# fleet. What works on every WSL is the oldest trick there is: hold a client
# open. The "anchor" is a hidden `wsl.exe -d Pointy -u root --exec /bin/sleep
# infinity` that lives as long as Windows does; the supervisor below waits on
# it and starts the distro again the moment it exits.
#
# One more service rule that makes the supervisor's ORDER matter: WslService
# keeps one session per user, and a Windows logoff terminates that session
# (every instance and the VM) only if the session was first created from the
# logging-off Windows session. Created from session 0 - by this task, before
# anyone logs on - it is terminated only when the service stops. So the task
# starting the distro first, 30 s after boot, is what makes a cashier's logoff
# harmless; and should an interactive wsl.exe ever get there first, the anchor
# dying at that logoff is what makes the supervisor start it again, from
# session 0 this time.
# ---------------------------------------------------------------------------

function Get-AnchorArguments {
    return @("-d", $Distro, "-u", "root", "--exec", $AnchorCommand, $AnchorArgument)
}

# The anchor for THIS distro, whoever started it: the supervisor, an earlier
# supervisor that handed over, or the installer from the operator's session.
function Get-AnchorProcess {
    try {
        $rows = @(Get-CimInstance -ClassName Win32_Process -Filter "Name='wsl.exe'" -ErrorAction Stop)
    } catch { return $null }
    foreach ($row in $rows) {
        $cmd = "$($row.CommandLine)"
        if ($cmd -match "(^|\s)-d\s+$([regex]::Escape($Distro))(\s|$)" -and
            $cmd -like "*--exec ${AnchorCommand} ${AnchorArgument}*") {
            try { return [System.Diagnostics.Process]::GetProcessById([int]$row.ProcessId) } catch { }
        }
    }
    return $null
}

# No console window, no inherited console: closing the window this was started
# from must not take the shop's server with it.
function Start-AnchorProcess {
    $psi = New-Object System.Diagnostics.ProcessStartInfo
    $psi.FileName        = "wsl.exe"
    $psi.Arguments       = ((Get-AnchorArguments) -join " ")
    $psi.UseShellExecute = $false
    $psi.CreateNoWindow  = $true
    $p = New-Object System.Diagnostics.Process
    $p.StartInfo = $psi
    if (-not $p.Start()) { throw "wsl.exe did not start" }
    return $p
}

function Test-ProcessAlive {
    param($Process)
    if ($null -eq $Process) { return $false }
    try { return (-not $Process.HasExited) } catch { return $false }
}

function Stop-ProcessQuietly {
    param($Process)
    try { if (Test-ProcessAlive $Process) { $Process.Kill() } } catch { }
}

# Adopt the attached anchor, or attach one. Idempotent; used by the installer
# so the distro stays up between its steps, and by the supervisor each cycle.
function Start-AnchorIfMissing {
    $existing = Get-AnchorProcess
    if (Test-ProcessAlive $existing) { return $existing }
    try {
        $p = Start-AnchorProcess
        Write-Log "attached the keep-alive client to '${Distro}' (PID $($p.Id)); WSL keeps the distro up while it runs"
        return $p
    } catch {
        Write-Log "could not attach the keep-alive client to '${Distro}': $($_.Exception.Message)" "ERROR"
        return $null
    }
}

# Why can this process not see the distro? What a log can tell apart: it was
# never registered for this user, or the task's logon has no registry hive,
# so WSL - which looks registrations up through the caller's HKCU - reads an
# empty default profile. The second is the one theory about the boot task
# nobody has been able to confirm or rule out from a desk; this line settles
# it from the field.
function Write-DistroVisibilityDiagnosis {
    try {
        $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
        $hiveLoaded = Test-Path "Registry::HKEY_USERS\${sid}"
        $lxss = "HKCU:\Software\Microsoft\Windows\CurrentVersion\Lxss"
        $registered = @()
        if (Test-Path $lxss) {
            $registered = @(Get-ChildItem $lxss -ErrorAction SilentlyContinue | ForEach-Object {
                "$((Get-ItemProperty $_.PSPath -ErrorAction SilentlyContinue).DistributionName)" } | Where-Object { $_ })
        }
        $names = "none"
        if ($registered.Count) { $names = ($registered -join ", ") }
        Write-Log ("  running as ${env:USERDOMAIN}\${env:USERNAME} (${sid}); profile hive loaded: ${hiveLoaded}; " +
                   "distros registered under HKCU: ${names}") "ERROR"
        if (-not $hiveLoaded) {
            Write-Log ("  the task's logon has no registry hive, so WSL sees an empty profile. Give the task a stored " +
                       "password instead:  schtasks /Change /TN ${TaskName} /RU <user> /RP <password>") "ERROR"
        }
    } catch { }
}

# Does the distro answer at all? Bounded: at boot the WSL service may not be
# ready yet, and a wedged one never is. Judged on what the distro prints, not
# on an exit code: this is the check that can restart a trading shop's server,
# and an exit code has lied to this script before (see Invoke-NativeTimeout).
function Test-DistroAnswers {
    param([int]$TimeoutSec = 60)
    $r = Invoke-Guest "echo pointy-alive" -TimeoutSec $TimeoutSec
    return (($r.Output -replace "`0", "") -like "*pointy-alive*")
}


# ---------------------------------------------------------------------------
# -Boot : the supervisor.
#
# The Windows counterpart of what systemd is for a Linux shop. The PointyWSL
# task starts it at boot and it runs until Windows stops. Each cycle it makes
# sure the anchor is attached, the distro answers, and the LAN bridge points at
# the VM; and it wakes the instant the anchor exits, so a distro that Windows
# Update or an operator shut down is back before the tills notice. A second
# copy - the task's 5-minute repetition, an operator running -Boot by hand -
# finds the mutex held and does one pass instead.
# ---------------------------------------------------------------------------

function Enter-SupervisorLock {
    # $true when this process now holds the supervisor role.
    try {
        $created = $false
        $script:SupervisorMutex = New-Object System.Threading.Mutex($true, $SupervisorMutexName, [ref]$created)
        if ($created) { return $true }
        # Not created: another process owns it, unless that process died without
        # releasing - an abandoned mutex is handed to us with an exception.
        try {
            return $script:SupervisorMutex.WaitOne(0)
        } catch [System.Threading.AbandonedMutexException] { return $true }
    } catch {
        Write-Log "could not take the supervisor lock ($($_.Exception.Message)); running a single pass" "WARN"
        return $false
    }
}

function Exit-SupervisorLock {
    try {
        if ($script:SupervisorMutex) { $script:SupervisorMutex.ReleaseMutex(); $script:SupervisorMutex.Dispose() }
    } catch { }
    $script:SupervisorMutex = $null
}

# Sleep until the bridge is due again, but wake the instant the anchor exits.
# Returns how long it actually waited, so the caller's clock is the sum of
# these rather than wall time (which a test cannot script).
function Wait-AnchorOrInterval {
    param($Anchor, [int]$Seconds)
    $sw = [System.Diagnostics.Stopwatch]::StartNew()
    $exited = $false
    if (Test-ProcessAlive $Anchor) {
        try { $exited = $Anchor.WaitForExit($Seconds * 1000) } catch { Start-Sleep -Seconds $Seconds }
    } else {
        Start-Sleep -Seconds $Seconds
    }
    return [pscustomobject]@{ AnchorExited = $exited; Seconds = [int]$sw.Elapsed.TotalSeconds }
}

# The supervisor's heartbeat, read by collect-diagnostics.ps1: a task that has
# been "running" for a week is healthy exactly when this file is fresh.
function Write-SupervisorState {
    param($Anchor, [bool]$Answering, [int]$Restarts, [datetime]$StartedAt)
    try {
        $anchorPid = 0
        if (Test-ProcessAlive $Anchor) { $anchorPid = [int]$Anchor.Id }
        @{ supervisor_pid = $PID; started_at = $StartedAt.ToString("o"); heartbeat_at = (Get-Date -Format "o")
           anchor_pid = $anchorPid; distro_answering = $Answering; distro_restarts = $Restarts } |
            ConvertTo-Json | Set-Content -Path $SupervisorStateFile -Encoding UTF8
    } catch { }
}

# Hand over to a newer bootstrap: start it detached and let this one return.
# It inherits nothing but the anchor, which stays attached throughout.
function Start-SupervisorProcess {
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    $arguments = @("-NoProfile", "-ExecutionPolicy", "Bypass", "-WindowStyle", "Hidden", "-File", $stable,
                   "-Boot", "-Distro", $Distro, "-InstallRoot", $InstallRoot, "-ApiPort", "$ApiPort", "-WebPort", "$WebPort")
    try {
        $psi = New-Object System.Diagnostics.ProcessStartInfo
        $psi.FileName        = "powershell.exe"
        $psi.Arguments       = (($arguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
        $psi.UseShellExecute = $false
        $psi.CreateNoWindow  = $true
        $p = New-Object System.Diagnostics.Process
        $p.StartInfo = $psi
        [void]$p.Start()
        Write-Log "started the newer bootstrap as PID $($p.Id)"
    } catch {
        Write-Log "could not start the newer bootstrap ($($_.Exception.Message)); the '${TaskName}' task re-launches it within 5 minutes" "WARN"
    }
}

# Start the PointyWSL task if it is not running: after this pass returns, only
# its supervisor keeps the distro up. A second start is ignored (IgnoreNew).
function Start-SupervisorTask {
    try {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        if ("$($task.State)" -eq "Running") { return $true }
        Start-ScheduledTask -TaskName $TaskName -ErrorAction Stop
        Write-Log "started the '${TaskName}' task; its supervisor holds the distro open from here on"
        return $true
    } catch {
        Write-Log ("could not start the '${TaskName}' task: $($_.Exception.Message). Without it the distro powers off " +
                   "about 15 s after the last wsl.exe exits.") "WARN"
        return $false
    }
}

function Invoke-Supervise {
    param([int]$MaxCycles = 0)   # 0 = until Windows stops; tests bound it
    Write-Log ("supervisor started (PID ${PID}): holding '${Distro}' open, re-proving the LAN bridge every " +
               "$([int]($ReconcileIntervalSec / 60)) minutes, restarting the distro the moment it stops")
    $anchor = $null
    $cycle = 0; $failures = 0; $restarts = 0
    $sinceReconcile = $ReconcileIntervalSec      # the first cycle reconciles
    $backoff = 5
    $notVisibleLogged = $false
    $startedAt = Get-Date
    while ($MaxCycles -le 0 -or $cycle -lt $MaxCycles) {
        $cycle++
        try {
            $anchorStarted = $false

            # 1. The anchor: adopt one that is attached, else attach one. The
            #    anchor is what starts the distro; nothing else needs to.
            if (-not (Test-ProcessAlive $anchor)) { $anchor = Get-AnchorProcess }
            if (-not (Test-ProcessAlive $anchor)) {
                if (Test-DistroExists) {
                    $notVisibleLogged = $false
                    $anchor = Start-AnchorIfMissing
                    $anchorStarted = (Test-ProcessAlive $anchor)
                } elseif ($script:WslListError) {
                    # wsl.exe itself is not answering: the service is being
                    # updated or restarted. Nothing to fix, only to outwait.
                    if (-not $notVisibleLogged) {
                        Write-Log "WSL is not answering ($($script:WslListError)); waiting for it to come back" "WARN"
                        $notVisibleLogged = $true
                    }
                } elseif (-not $notVisibleLogged) {
                    Write-Log ("distro '${Distro}' is not registered for the user this runs as, so nothing can be started. " +
                               "Run this script without -Boot to install; if it IS installed, the '${TaskName}' task must " +
                               "run as the Windows user that installed it.") "ERROR"
                    Write-DistroVisibilityDiagnosis
                    $notVisibleLogged = $true
                }
            }

            # 2. Does the distro answer? An anchor can be holding a wedged VM.
            $answering = $false
            if (Test-ProcessAlive $anchor) {
                $answering = Test-DistroAnswers
                if ($answering) {
                    if ($failures -gt 0) { Write-Log "distro '${Distro}' answers again" }
                    $failures = 0; $backoff = 5
                    if ($anchorStarted -or $sinceReconcile -ge $ReconcileIntervalSec) {
                        Invoke-BootReconcile | Out-Null
                        $sinceReconcile = 0
                    }
                } else {
                    $failures++
                    Write-Log "distro '${Distro}' is not answering (${failures} of ${DistroFailuresBeforeTerminate} before it is restarted)" "WARN"
                    if ($failures -ge $DistroFailuresBeforeTerminate) {
                        Write-Log "terminating '${Distro}' so the next cycle starts it fresh" "ERROR"
                        Invoke-Wsl @("--terminate", $Distro) -TimeoutSec 60 | Out-Null
                        Stop-ProcessQuietly $anchor
                        $anchor = $null
                        $failures = 0
                        $restarts++
                    }
                }
            }

            Write-SupervisorState -Anchor $anchor -Answering $answering -Restarts $restarts -StartedAt $startedAt

            # 3. A newer bootstrap that arrived with a release update takes over.
            if ($answering -and (Update-BootstrapFromGuest)) {
                Write-Log "handing over to the newer bootstrap; the keep-alive client stays attached"
                Exit-SupervisorLock
                Start-SupervisorProcess
                return
            }

            # 4. Wait for the next bridge check, or for the anchor to exit.
            $wait = $ReconcileIntervalSec - $sinceReconcile
            if (-not $answering) { $wait = $backoff; $backoff = [math]::Min(60, $backoff * 2) }
            if ($wait -lt 1) { $wait = 1 }
            $waited = Wait-AnchorOrInterval -Anchor $anchor -Seconds $wait
            $sinceReconcile += $waited.Seconds
            if ($waited.AnchorExited) {
                Write-Log "the keep-alive client exited (wsl --shutdown, a WSL update, or a logoff); starting '${Distro}' again now" "WARN"
                $restarts++
                $anchor = $null
            }
        } catch {
            # One bad cycle must not end the supervisor: log it and carry on.
            Write-Log "supervisor cycle failed: $($_.Exception.Message)" "ERROR"
            Start-Sleep -Seconds 30
        }
    }
}


# ---------------------------------------------------------------------------
# -Boot : bridge the LAN into the NAT'd WSL VM.
#
# WSL2 sits behind a NAT with a fresh private IP on every VM start. So the tills
# cannot reach the stack until we forward the host's ports at the WSL IP, and we
# must re-do it whenever that IP changes.
#
# The forward listens on 0.0.0.0, which includes 127.0.0.1, so it also serves a
# till running on this same PC. It has to be the ONLY thing holding these ports
# on Windows - see the localhostForwarding note in Write-WslConfig.
#
# We do NOT use mirrored networking (which would remove all of this) because it
# needs Windows 11 22H2+; the shop fleet includes Windows 10, and running two
# different network designs is the exact split this migration exists to end.
# ---------------------------------------------------------------------------

function Get-WslIp {
    # eth0 specifically, NOT `hostname -I`: once Docker is running the distro also
    # holds docker0 and per-network bridge addresses (172.17.x, 172.18.x), and
    # `hostname -I` returns them in no guaranteed order. Forwarding the LAN to a
    # docker bridge address silently blackholes every till.
    #
    # Parsed here rather than with awk/cut inside the guest: the command crosses
    # PowerShell -> wsl.exe -> bash quoting, and a nested quote is a real bug
    # waiting to happen for no benefit.
    # Judged on the output alone: an address in it is an address, whatever
    # the exit code claims.
    $r = Invoke-Guest "ip -4 -o addr show dev eth0"
    if (($r.Output -replace "`0", "") -match 'inet\s+(\d{1,3}(?:\.\d{1,3}){3})') {
        return $Matches[1]
    }
    return $null
}

# portproxy is implemented by the IP Helper service. Without it running, every
# `netsh ... add` silently succeeds and forwards nothing - the single most
# common reason a WSL deployment is unreachable from the LAN.
function Enable-IpHelper {
    try {
        $svc = Get-Service -Name iphlpsvc -ErrorAction Stop
        if ($svc.StartType -ne "Automatic") {
            Set-Service -Name iphlpsvc -StartupType Automatic -ErrorAction Stop
            Write-Log "set the IP Helper service to start automatically"
        }
        if ($svc.Status -ne "Running") {
            Start-Service -Name iphlpsvc -ErrorAction Stop
            Write-Log "started the IP Helper service (portproxy needs it)"
        }
    } catch {
        Write-Log "could not ensure the IP Helper service is running: $($_.Exception.Message)" "WARN"
    }
}

function Get-PortProxyTarget {
    param([int]$Port)
    $r = Invoke-Native -File "netsh.exe" -Arguments @("interface", "portproxy", "show", "v4tov4")
    foreach ($line in ($r.Output -split "`r?`n")) {
        # "0.0.0.0         8000        172.28.144.3    8000"
        if ($line -match '^\s*(\S+)\s+(\d+)\s+(\S+)\s+(\d+)\s*$' -and [int]$Matches[2] -eq $Port) {
            return $Matches[3]
        }
    }
    return $null
}

# -Force re-creates a forward whose rule already looks right. A rule is only
# configuration; whether its listener actually bound is a separate question,
# and deleting and re-adding the rule is what makes the IP Helper try again.
function Set-PortProxy {
    param([int]$Port, [string]$Target, [switch]$Force)
    $current = Get-PortProxyTarget -Port $Port
    if ($current -eq $Target -and -not $Force) { return $false }
    if ($current) {
        Invoke-Native -File "netsh.exe" -Arguments @(
            "interface", "portproxy", "delete", "v4tov4",
            "listenaddress=0.0.0.0", "listenport=$Port") | Out-Null
    }
    $r = Invoke-Native -File "netsh.exe" -Arguments @(
        "interface", "portproxy", "add", "v4tov4",
        "listenaddress=0.0.0.0", "listenport=$Port",
        "connectaddress=$Target", "connectport=$Port")
    if ($r.ExitCode -ne 0) {
        Write-Log "failed to forward port ${Port} to ${Target}: $($r.Output.Trim())" "ERROR"
        return $false
    }
    Write-Log "LAN port ${Port} -> ${Target}:${Port} (was ${current})"
    return $true
}

# The addresses a till on the shop network dials: every IPv4 this machine holds
# on an adapter the LAN can reach. WSL's own vEthernet is left out on purpose -
# it often sits in 192.168.x too, and a till sent there can never route to it.
# Hyper-V's Default Switch and the VirtualBox/VMware host-only adapters are just
# as private. (A Hyper-V *external* switch stays in: on a machine that has one,
# it is where the real LAN address lives.)
function Get-LanIPv4 {
    try {
        return @(Get-NetIPAddress -AddressFamily IPv4 -ErrorAction Stop |
            Where-Object {
                $_.IPAddress -notlike "127.*" -and $_.IPAddress -notlike "169.254.*" -and
                "$($_.AddressState)" -eq "Preferred" -and
                $_.InterfaceAlias -notmatch 'WSL|Default Switch|VirtualBox|VMware|Loopback'
            } | Select-Object -ExpandProperty IPAddress)
    } catch { return @() }
}

# Does this URL reach one of OUR front doors? Both answer their health path
# themselves ("ok", 200), so a pass cannot come from IIS or a vendor's web
# server that happens to hold the port. No proxy: a shop PC's system proxy must
# not be asked for a LAN address.
function Test-PointyHttp {
    param([string]$Url, [int]$TimeoutMs = 4000)
    $response = $null
    try {
        $request = [System.Net.WebRequest]::Create($Url)
        $request.Proxy = $null
        $request.Timeout = $TimeoutMs
        $response = $request.GetResponse()
        return ([int]$response.StatusCode -eq 200)
    } catch {
        return $false
    } finally {
        if ($response) { $response.Close() }
    }
}

function Get-DeadAddresses {
    param([string[]]$Addresses, [int]$Port, [string]$HealthPath)
    return @($Addresses | Where-Object { -not (Test-PointyHttp "http://${_}:${Port}${HealthPath}") })
}

# Who holds a port, by address and process: the evidence a broken forward
# needs, because netsh never says that one failed to bind.
function Get-PortListeners {
    param([int]$Port)
    try {
        return @(Get-NetTCPConnection -LocalPort $Port -State Listen -ErrorAction Stop | ForEach-Object {
            [pscustomobject]@{
                Address   = "$($_.LocalAddress)"
                ProcessId = [int]$_.OwningProcess
                Name      = "$((Get-Process -Id $_.OwningProcess -ErrorAction SilentlyContinue).ProcessName)"
            }
        })
    } catch { return @() }   # Get-NetTCPConnection throws when nothing is listening
}

function Write-PortDiagnosis {
    param([int]$Port)
    $listeners = @(Get-PortListeners -Port $Port)
    if ($listeners.Count -eq 0) {
        Write-Log ("  nothing is listening on port ${Port}: the IP Helper service has not opened the " +
                   "forward. Check 'Get-Service iphlpsvc' and 'netsh interface portproxy show v4tov4'.") "ERROR"
        return
    }
    foreach ($listener in $listeners) {
        Write-Log ("  {0}:{1} is held by {2} (PID {3})" -f $listener.Address, $Port, $listener.Name, $listener.ProcessId) "ERROR"
    }
    if (@($listeners | Where-Object { $_.Name -like "wslrelay*" }).Count -gt 0) {
        # See Write-WslConfig: this is the install-order race, already turned off
        # in .wslconfig, which only a fresh start of the WSL VM applies.
        Write-Log ("  wslrelay is WSL's localhost forwarding. It took port ${Port} before the LAN forward " +
                   "could, so the forward cannot bind. It is switched off in .wslconfig from now on; " +
                   "restart Windows once to apply that.") "ERROR"
    } elseif ($Port -eq $WebPort) {
        # Windows very often already has something on :80 - IIS, the World Wide
        # Web Publishing Service, a vendor's print or label server. HTTP.sys
        # listeners show up as System (PID 4).
        Write-Log ("  Fix: stop that service, or set POINTY_WEB_PORT to a free port in ${GuestDir}/.env, " +
                   "re-run install.sh inside the distro, and re-run this script with -WebPort <port>.") "ERROR"
    } else {
        Write-Log "  Fix: stop the conflicting service, or set POINTY_BACKEND_PORT and -ApiPort together." "ERROR"
    }
}

# netsh reports success for a forward whose listener never bound, and a stack
# behind a dead forward looks perfectly healthy: containers up, log clean, the
# server's own till working. So walk the path a till takes, one hop at a time,
# and name the hop that breaks.
#
# Returns $true when every address answers, $false when the path is broken,
# and $null when the stack itself is not up yet, so there is nothing to judge.
function Confirm-LanBridge {
    param([string]$WslIp, [int]$Port, [string]$HealthPath)

    # 1. The stack, from inside the VM. Down here means the containers are still
    #    starting (normal at boot) or broken - neither is the bridge's doing.
    $guest = Invoke-Guest "curl -fsS -o /dev/null -m 4 http://127.0.0.1:${Port}${HealthPath}"
    if ($guest.ExitCode -ne 0) {
        Write-Log "port ${Port}: the stack is not answering inside WSL yet; the bridge is checked again on the next run" "WARN"
        return $null
    }

    # 2. Windows to the VM: the hop the forward itself makes.
    if (-not (Test-PointyHttp "http://${WslIp}:${Port}${HealthPath}")) {
        Write-Log ("port ${Port}: the stack answers inside WSL but not at ${WslIp}:${Port} from Windows. " +
                   "Check that POINTY_BACKEND_BIND and POINTY_WEB_BIND in ${GuestDir}/.env are 0.0.0.0; " +
                   "on Windows 11, also that no Hyper-V firewall policy blocks the WSL VM.") "ERROR"
        return $false
    }

    # 3. This machine's own addresses, the way a till dials them. From here that
    #    is a loopback hop, so it proves the forward binds and forwards; it cannot
    #    prove the firewall, which only filters traffic from other devices.
    $lan = @(Get-LanIPv4)
    $targets = @("127.0.0.1") + $lan
    $dead = @(Get-DeadAddresses -Addresses $targets -Port $Port -HealthPath $HealthPath)
    if ($dead.Count -gt 0) {
        Write-Log "port ${Port}: the LAN forward does not answer on $($dead -join ', '); re-creating it" "WARN"
        Set-PortProxy -Port $Port -Target $WslIp -Force | Out-Null
        Start-Sleep -Seconds 2
        $dead = @(Get-DeadAddresses -Addresses $targets -Port $Port -HealthPath $HealthPath)
        if ($dead.Count -gt 0) {
            Write-Log "port ${Port}: still unreachable on $($dead -join ', ') after re-creating the forward" "ERROR"
            Write-PortDiagnosis -Port $Port
            return $false
        }
        Write-Log "port ${Port}: the re-created forward answers"
    }
    if ($lan.Count -eq 0) {
        Write-Log "port ${Port}: this machine has no LAN address right now, so no till can reach it" "WARN"
        return $false
    }
    return $true
}

# Two things no check on this machine can see, because its requests to its own
# LAN address never pass the inbound firewall. Name them instead.
function Write-FirewallWarnings {
    try {
        foreach ($fwProfile in @(Get-NetFirewallProfile -PolicyStore ActiveStore -ErrorAction Stop)) {
            if ("$($fwProfile.Enabled)" -eq "True" -and "$($fwProfile.AllowLocalFirewallRules)" -eq "False") {
                Write-Log ("Group Policy makes the '$($fwProfile.Name)' firewall profile ignore local rules, so " +
                           "the Pointy allow rules do nothing there. Allow inbound TCP ${ApiPort} and ${WebPort} " +
                           "in that policy instead.") "WARN"
            }
        }
    } catch { }
    try {
        foreach ($product in @(Get-CimInstance -Namespace "root/SecurityCenter2" -ClassName FirewallProduct -ErrorAction Stop)) {
            Write-Log ("a third-party firewall is installed ($($product.displayName)). If other devices cannot " +
                       "connect, allow inbound TCP ${ApiPort} and ${WebPort} in it too.") "WARN"
        }
    } catch { }   # Windows Server has no Security Center
}

function Add-FirewallRule {
    param([string]$Name, [int]$Port)
    try {
        if (Get-NetFirewallRule -DisplayName $Name -ErrorAction SilentlyContinue) { return }
        New-NetFirewallRule -DisplayName $Name -Direction Inbound -Action Allow `
            -Protocol TCP -LocalPort $Port -Profile Any -ErrorAction Stop | Out-Null
        Write-Log "opened the firewall for inbound TCP ${Port} ('${Name}')"
    } catch {
        Write-Log "could not add firewall rule '${Name}': $($_.Exception.Message)" "WARN"
    }
}

# One reconcile pass. Returns $true when the bridge was (re)pointed at the
# VM, $false when there was nothing to point it at. Never exits: the
# supervisor runs this every cycle and must outlive any single failure.
function Invoke-BootReconcile {
    if (-not (Test-DistroExists)) {
        Write-Log "distro '$Distro' is not registered - run this script without -Boot to install." "ERROR"
        return $false
    }

    # Any wsl.exe boots the VM if it is down. What keeps it up afterwards is
    # the supervisor's anchor - NOT systemd, which WSL does not count.
    $ping = Invoke-Guest "true" -TimeoutSec 60
    if ($ping.ExitCode -ne 0) {
        Write-Log "could not start distro '$Distro': $($ping.Output)" "ERROR"
        return $false
    }

    Enable-IpHelper
    Update-GeneratedWslConfig

    $ip = Get-WslIp
    if (-not $ip) {
        Write-Log "could not read the distro's eth0 address; not touching the LAN bridge." "ERROR"
        return $false
    }

    # Each port with the path its own front door answers without the backend:
    # edge owns the API port, web the browser port.
    $bridge = @(
        [pscustomobject]@{ Port = $ApiPort; HealthPath = "/healthz-edge" },
        [pscustomobject]@{ Port = $WebPort; HealthPath = "/healthz-web" }
    )

    $changed = $false
    foreach ($entry in $bridge) {
        if (Set-PortProxy -Port $entry.Port -Target $ip) { $changed = $true }
    }
    Add-FirewallRule -Name "Pointy API (TCP $ApiPort)" -Port $ApiPort
    Add-FirewallRule -Name "Pointy Web (TCP $WebPort)" -Port $WebPort

    $verified = $true
    foreach ($entry in $bridge) {
        $result = Confirm-LanBridge -WslIp $ip -Port $entry.Port -HealthPath $entry.HealthPath
        if ($result -ne $true) { $verified = $false }
    }
    # Once per boot is enough: these only change when someone changes the machine.
    if ($changed) { Write-FirewallWarnings }

    $lan = @(Get-LanIPv4)
    try {
        @{ wsl_ip = $ip; lan_ips = $lan; api_port = $ApiPort; web_port = $WebPort
           verified = $verified; updated_at = (Get-Date -Format "o") } |
            ConvertTo-Json | Set-Content -Path $StateFile -Encoding UTF8
    } catch { }

    $where = if ($lan.Count) { " - tills reach it at " + (($lan | ForEach-Object { "http://${_}:${ApiPort}" }) -join ", ") } else { "" }
    if ($changed) { Write-Log "LAN bridge reconciled onto ${ip}${where}" }
    elseif ($verified) { Write-Log "LAN bridge already correct and answering (${ip}); nothing to do" }
    else { Write-Log "LAN bridge configured for ${ip}, but not every hop answered; see above" "WARN" }
    return $true
}


# ---------------------------------------------------------------------------
# Install
# ---------------------------------------------------------------------------

function Assert-Preflight {
    if (-not (Test-Admin)) {
        Die "run this in an ELEVATED (Administrator) PowerShell."
    }
    if ([Environment]::Is64BitOperatingSystem -eq $false) {
        Die "WSL2 requires 64-bit Windows."
    }

    $build = [int](Get-ItemProperty "HKLM:\SOFTWARE\Microsoft\Windows NT\CurrentVersion").CurrentBuildNumber
    if ($build -lt 19041) {
        Die ("Windows build ${build} is too old for WSL2 (needs 19041 / Windows 10 2004 or newer). " +
             "Update Windows, or install this shop on a newer machine.")
    }
    if ($build -lt 19044) {
        Write-Log ("Windows build ${build} is out of support; WSL2 works but you are on your own " +
                   "for OS security fixes. 19044 (21H2) or newer is strongly recommended.") "WARN"
    }
    Write-Log "Windows build ${build}: OK"

    # Virtualization must be on in firmware. This is the one failure that needs
    # a physical visit (a BIOS/UEFI setting), so name it precisely rather than
    # letting `wsl --import` fail with an opaque HCS error later.
    $cs = Get-CimInstance -ClassName Win32_ComputerSystem
    if (-not $cs.HypervisorPresent) {
        $virt = (Get-CimInstance -ClassName Win32_Processor | Select-Object -First 1).VirtualizationFirmwareEnabled
        if ($virt -eq $false) {
            Die ("Hardware virtualization is DISABLED in this machine's BIOS/UEFI. " +
                 "Reboot into firmware setup and enable Intel VT-x / AMD-V (often called " +
                 "'Virtualization Technology' or 'SVM Mode'), then re-run this script.")
        }
        Write-Log "no hypervisor running yet - expected before the Windows features are enabled" "INFO"
    }

    $drive = (Get-Item $InstallRoot -ErrorAction SilentlyContinue)
    $root  = if ($drive) { $drive.PSDrive.Name } else { (Split-Path -Qualifier $InstallRoot).TrimEnd(':') }
    try {
        $free = (Get-PSDrive -Name $root).Free / 1GB
        if ($free -lt 20) {
            # Parenthesised on purpose: -f binds tighter than +, and without
            # the brackets a shop saw "{0:N1} GB free on {1}:" on its screen.
            Write-Log (("only {0:N1} GB free on {1}: - the distro, images and Postgres data all live " +
                        "here and the virtual disk only ever grows. 20 GB+ recommended.") -f $free, $root) "WARN"
        }
    } catch { }

    if (Get-Service -Name "com.docker.service" -ErrorAction SilentlyContinue) {
        Write-Log ("Docker Desktop is installed on this machine. This installer does NOT migrate an " +
                   "existing Docker Desktop deployment - it builds a clean WSL one alongside it.") "WARN"
        if (-not $Force) {
            $answer = Read-Host "Continue anyway? Type 'yes' to proceed"
            if ($answer -ne "yes") { Die "aborted at the operator's request." }
        }
    }
}

# A server must not sleep, and must not Fast Start. Fast Startup turns 'Shut
# down' into hibernating the kernel session: the next power-on is a resume, not
# a boot, so an At-startup task trigger never fires, and the WSL VM - which no
# hibernation preserves - is simply gone. The sleep timers are the other
# silent server-killer on a PC that was somebody's desktop until yesterday.
function Set-ServerPowerSettings {
    foreach ($setting in @("standby-timeout-ac", "hibernate-timeout-ac")) {
        $r = Invoke-Native -File "powercfg.exe" -Arguments @("/change", $setting, "0")
        if ($r.ExitCode -ne 0) { Write-Log "could not set ${setting} to never: $($r.Output.Trim())" "WARN" }
    }
    Write-Log "power: this PC will not sleep or hibernate on mains power"
    try {
        $key = "HKLM:\SYSTEM\CurrentControlSet\Control\Session Manager\Power"
        $current = (Get-ItemProperty -Path $key -Name HiberbootEnabled -ErrorAction SilentlyContinue).HiberbootEnabled
        if ($null -ne $current -and [int]$current -ne 0) {
            Set-ItemProperty -Path $key -Name HiberbootEnabled -Value 0 -Type DWord -ErrorAction Stop
            Write-Log "power: turned Windows Fast Startup off (a Fast Startup power-on is not a boot, so the boot task never fired)"
        }
    } catch {
        Write-Log "could not turn Fast Startup off: $($_.Exception.Message)" "WARN"
    }
}

function Enable-WindowsFeatures {
    $needed = @("Microsoft-Windows-Subsystem-Linux", "VirtualMachinePlatform")
    $rebootRequired = $false
    foreach ($feature in $needed) {
        $state = Invoke-Native -File "dism.exe" -Arguments @(
            "/online", "/get-featureinfo", "/featurename:$feature")
        if ($state.Output -match "State\s*:\s*Enabled") {
            Write-Log "Windows feature ${feature}: already enabled"
            continue
        }
        Write-Log "enabling Windows feature ${feature}..."
        # DISM works with no internet, unlike the Store-based paths.
        $r = Invoke-Native -File "dism.exe" -Arguments @(
            "/online", "/enable-feature", "/featurename:$feature", "/all", "/norestart")
        if ($r.ExitCode -eq 3010) { $rebootRequired = $true }
        elseif ($r.ExitCode -ne 0) { Die "could not enable ${feature}: $($r.Output.Trim())" }
    }
    if ($rebootRequired) {
        Write-Log "" 
        Write-Log "REBOOT REQUIRED to finish enabling the Windows virtualization features." "WARN"
        Write-Log "Reboot, then run this exact command again to continue the install:" "WARN"
        Write-Log "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" "WARN"
        exit 2
    }
}

# Is a working, modern wsl.exe actually present? This is the ONLY thing that
# decides whether the WSL step succeeded. An installer exit code is a hint about
# one attempt; this is the outcome, and the outcome is what the next step needs.
#
# Only the modern (Store/MSI, 1.0+) wsl.exe counts, because only it runs
# systemd, and the whole self-healing design - Docker on boot, the watchdog
# timer - stands on systemd being PID 1. The inbox Windows 10 wsl.exe answers
# --status but has no --version, no systemd, and a per-session service a boot
# task cannot reach; a machine with only that one needs the bundled MSI just
# as a machine with no WSL at all does.
#
# Judged by the NUMBERS in the output, never by the label in front of them:
# wsl.exe prints its messages in the Windows display language, and on an
# Arabic till the line that reads "WSL version: 2.3.26.0" in English need not
# contain the letters "WSL" at all. The inbox wsl.exe fails --version with
# usage text, which has no version number in it.
function Test-WslReady {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    return ($ver.ExitCode -eq 0 -and (($ver.Output -replace "`0","") -match '[0-9]+\.[0-9]+\.[0-9]+'))
}

# The running WSL's version, or $null when there is no modern wsl.exe. The
# first version number printed is WSL's own; the kernel's comes after it.
function Get-WslVersion {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    if ($ver.ExitCode -ne 0) { return $null }
    if (($ver.Output -replace "`0","") -match '([0-9]+)\.([0-9]+)\.([0-9]+)') {
        try { return [version]"$($Matches[1]).$($Matches[2]).$($Matches[3])" } catch { return $null }
    }
    return $null
}

# What `wsl --version` actually said, for the log line that explains a failed
# readiness check on site instead of leaving a technician to guess.
function Get-WslVersionEvidence {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    $first = @((($ver.Output -replace "`0","") -split "`r?`n") | Where-Object { $_.Trim() } | Select-Object -First 1)
    return "wsl --version exited $($ver.ExitCode): $(($first -join '').Trim())"
}

function Get-WslVersionLine {
    $ver = Invoke-Wsl @("--version") -TimeoutSec 30
    if ($ver.ExitCode -ne 0) { return "unknown" }
    return ((($ver.Output -replace "`0","") -split "`r?`n" | Select-Object -First 1).Trim())
}

function Install-Wsl {
    # A machine on which WSL already runs OUR distro has, by definition, a WSL
    # that works: `wsl --list` just answered with it. Nothing below may touch
    # that WSL, whatever a readiness probe makes of a localized, odd or slow
    # `wsl --version`. Installing over a good WSL is how a working shop gets
    # broken, and a probe's false alarm is how a working shop is refused an
    # update.
    if (Test-DistroExists) {
        Write-Log "WSL already runs distro '${Distro}' on this machine ($(Get-WslVersionEvidence)); leaving WSL alone"
        return
    }
    # Already working (a fresh machine that is up to date)? Do nothing.
    if (Test-WslReady) {
        Write-Log "WSL already present and working: $(Get-WslVersionLine)"
        $r = Invoke-Wsl @("--set-default-version", "2") -TimeoutSec 60
        if ($r.ExitCode -ne 0) { Write-Log "could not set WSL default version 2: $($r.Output.Trim())" "WARN" }
        return
    }
    Write-Log "WSL is not ready ($(Get-WslVersionEvidence))" "WARN"
    if ((Invoke-Wsl @("--status") -TimeoutSec 30).ExitCode -eq 0) {
        Write-Log ("an older inbox wsl.exe is present (no --version). It cannot run systemd, so nothing inside the " +
                   "distro would start on boot; installing the bundled WSL over it.") "WARN"
    }

    # Prefer the MSI we ship: it is the same modern wsl.exe on Windows 10 and 11,
    # needs no internet and no Microsoft Store (shops are frequently offline, and
    # the Store is commonly stripped from POS images).
    $msi = Get-ChildItem -Path $PSScriptRoot -Filter "wsl*.msi" -ErrorAction SilentlyContinue |
        Sort-Object Name -Descending | Select-Object -First 1

    $rebootHint = $false
    $lastCode   = $null
    $lastOutput = ""

    if ($msi) {
        # Windows Installer is single-threaded machine-wide. The DISM feature
        # enable we just ran, Windows Update, or a vendor updater will hold that
        # mutex and msiexec returns 1618 IMMEDIATELY. That is a "come back in a
        # moment", not a failure - and it is why this step used to fail on the
        # first run and pass on the second.
        $transient = @(1618, 1601)   # 1601 = Windows Installer service unavailable
        $attempts  = 5
        for ($i = 1; $i -le $attempts; $i++) {
            Write-Log "installing WSL from the bundled $($msi.Name) (attempt ${i}/${attempts})..."
            # Verbose MSI log next to our own, so a genuine failure is diagnosable
            # on site instead of being a bare exit code.
            $msiLog = Join-Path $LogDir ("wsl-msi-{0}.log" -f $i)
            try { if (-not (Test-Path $LogDir)) { New-Item -ItemType Directory -Force -Path $LogDir | Out-Null } } catch { }
            # No manual quoting: PowerShell quotes each array element itself, and
            # adding our own passes literal quote characters through to msiexec.
            $r = Invoke-Native -File "msiexec.exe" -Arguments @(
                "/i", $msi.FullName, "/quiet", "/norestart", "/l*v", $msiLog)
            $lastCode = $r.ExitCode; $lastOutput = $r.Output.Trim()

            if ($r.ExitCode -in @(0, 1638)) { break }          # 1638 = same-or-newer installed
            if ($r.ExitCode -in @(3010, 1641)) { $rebootHint = $true; break }
            if ($r.ExitCode -in $transient -and $i -lt $attempts) {
                Write-Log ("Windows Installer is busy (exit $($r.ExitCode)); another install is " +
                           "running. Waiting 20s and retrying.") "WARN"
                Start-Sleep -Seconds 20
                continue
            }
            Write-Log "msiexec returned $($r.ExitCode); verifying whether WSL works anyway. Log: ${msiLog}" "WARN"
            break
        }
    } else {
        Write-Log "no bundled WSL MSI found; falling back to 'wsl --update' (needs internet)" "WARN"
        $r = Invoke-Wsl @("--update") -TimeoutSec 1800
        $lastCode = $r.ExitCode; $lastOutput = $r.Output.Trim()
    }

    # A wsl.exe that was just installed is judged the same way as one that was
    # already there: by whichever way of running it answers.
    Select-WslRunner

    # THE decision. `wsl --update` reports non-zero when there is nothing to do,
    # and msiexec can report an odd code for an install that landed perfectly, so
    # neither exit code is trusted over the machine's actual state.
    if (Test-WslReady) {
        if ($null -ne $lastCode -and $lastCode -notin @(0, 1638)) {
            Write-Log "the WSL installer returned ${lastCode}, but WSL works - continuing." "WARN"
        }
        Write-Log "WSL: $(Get-WslVersionLine)"
        $r = Invoke-Wsl @("--set-default-version", "2") -TimeoutSec 60
        if ($r.ExitCode -ne 0) { Write-Log "could not set WSL default version 2: $($r.Output.Trim())" "WARN" }
        return
    }

    # Not working. Now the exit code earns its keep as the explanation.
    if ($rebootHint) {
        Write-Log ""
        Write-Log "WSL was installed but needs a REBOOT before it can run." "WARN"
        Write-Log "Reboot, then run this exact command again to continue the install:" "WARN"
        Write-Log "  powershell -ExecutionPolicy Bypass -File `"$PSCommandPath`"" "WARN"
        exit 2
    }
    if (-not $msi) {
        Die ("WSL is not installed and could not be updated online (exit ${lastCode}). Put the WSL MSI " +
             "(wsl.<version>.x64.msi) next to this script and re-run. ${lastOutput}")
    }
    Die ("WSL still does not run after installing $($msi.Name) (msiexec exit ${lastCode}; " +
         "$(Get-WslVersionEvidence)). The verbose MSI log is under ${LogDir}. If this machine has never had " +
         "the virtualization features enabled, reboot once and re-run this script. ${lastOutput}")
}

# Where WSL reads .wslconfig from: the profile of the user wsl.exe runs as.
# Not $env:USERPROFILE - under the boot task that can name a profile WSL never
# reads (Default, or the system's), and a .wslconfig written there is one that
# never applies.
function Get-OwnerProfileDir {
    try {
        $sid = [System.Security.Principal.WindowsIdentity]::GetCurrent().User.Value
        $row = Get-CimInstance -ClassName Win32_UserProfile -Filter "SID='${sid}'" -ErrorAction Stop
        if ($row -and $row.LocalPath -and (Test-Path $row.LocalPath)) { return "$($row.LocalPath)" }
    } catch { }
    return $env:USERPROFILE
}

function Write-WslConfig {
    # Host-wide WSL2 VM tuning. Unknown keys are ignored with a warning by older
    # wsl.exe, so we only write the modern ones when the running WSL supports
    # them - otherwise every single `wsl` call prints noise into our logs. And
    # each key goes under ITS section: WSL reads a key only there, so a right
    # key in the wrong section is a warning and nothing else.
    $totalGb = [math]::Round((Get-CimInstance Win32_ComputerSystem).TotalPhysicalMemory / 1GB)
    $memGb   = [int][math]::Max(4, [math]::Min(8, [math]::Floor($totalGb / 2)))
    $cpus    = [int][math]::Max(2, [math]::Min(4, [Environment]::ProcessorCount))

    $version = Get-WslVersion
    $modern  = ($null -ne $version -and $version.Major -ge 2)

    $lines = @(
        $WslConfigMarker,
        "[wsl2]",
        "memory=${memGb}GB",
        "processors=${cpus}",
        "swap=2GB",
        "# OFF on purpose. Every till reaches the stack through the netsh portproxy",
        "# forward (see -Boot), which listens on 0.0.0.0 and so also answers",
        "# 127.0.0.1 for a till on this same PC. WSL's own relay would bind",
        "# 127.0.0.1 on the same ports, and whichever of the two binds first can stop",
        "# the other from binding at all - on a fresh install that left the server's",
        "# own till working and every other device unable to find the server.",
        "localhostForwarding=false",
        "guiApplications=false",
        "nestedVirtualization=false"
    )
    if ($modern) {
        $lines += @(
            "# Never idle-stop the VM: it is a server, not a developer shell. This keeps",
            "# the empty VM; what keeps the DISTRO is the boot task's keep-alive client.",
            "vmIdleTimeout=-1",
            "[experimental]",
            "# Let the virtual disk hand free space back to Windows. Without this the",
            "# vhdx only ever grows - a year of image churn silently fills C:.",
            "sparseVhd=true",
            "autoMemoryReclaim=gradual"
        )
    }
    if ($null -ne $version -and $version -ge [version]"2.5.4") {
        $lines += @(
            "[general]",
            "# Belt and braces for the keep-alive client: never power the distro off for",
            "# being idle. Only WSL 2.5.4+ knows this key; older ones warn on every call.",
            "instanceIdleTimeout=-1"
        )
    }

    $path = Join-Path (Get-OwnerProfileDir) ".wslconfig"
    $content = ($lines -join "`n") + "`n"
    $previous = if (Test-Path $path) { [System.IO.File]::ReadAllText($path) } else { "" }
    # Whether anything changed: WSL reads this file only when its VM starts.
    if ($previous -eq $content) { return $false }
    # LF + no BOM: the WSL config parser rejects a BOM outright.
    [System.IO.File]::WriteAllText($path, $content, (New-Object System.Text.UTF8Encoding($false)))
    Write-Log "wrote ${path} (memory=${memGb}GB, processors=${cpus})"
    return $true
}

# On a re-run over a live install, a changed .wslconfig does nothing until the
# WSL VM restarts. Stop the stack cleanly first - `wsl --shutdown` on its own
# kills Postgres mid-write - then restart the VM here, while an operator is at
# the machine anyway. The rest of the install brings the stack back up.
function Restart-WslVm {
    Write-Log "restarting WSL so the new .wslconfig applies; the stack comes back up below"
    Invoke-Guest "cd '${GuestDir}' && test -f docker-compose.yml && docker compose --env-file .env -f docker-compose.yml stop" -TimeoutSec 600 | Out-Null
    $r = Invoke-Wsl @("--shutdown") -TimeoutSec 120
    if ($r.ExitCode -ne 0) {
        Write-Log "wsl --shutdown failed: $($r.Output.Trim()). Restart Windows once to apply .wslconfig." "WARN"
    }
}

# Shops installed by an older bootstrap have an older generated .wslconfig:
# localhostForwarding still on, keys in sections WSL ignores, no idle setting.
# Converge it - only if this script generated it, never an operator's own - so
# the fix reaches them at the next start of the WSL VM, i.e. the next Windows
# restart. Nothing is restarted from here: that would take the tills down in
# the middle of trading.
function Update-GeneratedWslConfig {
    try {
        $path = Join-Path (Get-OwnerProfileDir) ".wslconfig"
        if (-not (Test-Path $path)) { return }
        $text = [System.IO.File]::ReadAllText($path)
        if (-not $text.StartsWith($WslConfigMarker)) { return }
        if (Write-WslConfig) {
            Write-Log "updated the generated .wslconfig; it takes effect the next time Windows restarts"
        }
    } catch {
        Write-Log "could not update .wslconfig: $($_.Exception.Message)" "WARN"
    }
}

function Import-Distro {
    if (Test-DistroExists) {
        Write-Log "distro '${Distro}' is already registered; leaving it and its data alone"
        return
    }
    $rootfs = Get-ChildItem -Path $PSScriptRoot -Filter "pointy-wsl-rootfs*.tar*" -ErrorAction SilentlyContinue |
        Select-Object -First 1
    if (-not $rootfs) {
        Die ("no distro image found. Expected pointy-wsl-rootfs.tar.gz next to this script - " +
             "is this a complete bundle?")
    }
    $target = Join-Path $InstallRoot "distro"
    New-Item -ItemType Directory -Force -Path $target | Out-Null
    Write-Log "importing '${Distro}' from $($rootfs.Name) into ${target} (this takes a few minutes)..."
    $r = Invoke-Wsl @("--import", $Distro, $target, $rootfs.FullName, "--version", "2") -TimeoutSec 7200
    if ($r.ExitCode -ne 0) {
        $detail = ($r.Output -replace "`0", "").Trim()
        Die "wsl --import failed: ${detail}"
    }
    Write-Log "distro '${Distro}' imported"
}

function Set-GuestTimezone {
    # A freshly imported distro is UTC. Z-reports, day rollups, holiday tagging
    # and shift boundaries are all business-local, so an unset timezone silently
    # files the evening's sales on the wrong day.
    try {
        $winTz = (Get-TimeZone).Id
        $map = Join-Path $PSScriptRoot "timezone-map.txt"
        $ianaTz = $null
        if (Test-Path $map) {
            foreach ($line in (Get-Content $map)) {
                if ($line -match '^\s*#') { continue }
                $parts = $line -split '\|', 2
                if ($parts.Count -eq 2 -and $parts[0].Trim() -eq $winTz) { $ianaTz = $parts[1].Trim(); break }
            }
        }
        if (-not $ianaTz) {
            Write-Log "no IANA mapping for Windows time zone '${winTz}'; the distro stays on UTC." "WARN"
            Write-Log "  Set it by hand:  wsl -d ${Distro} -u root ln -sf /usr/share/zoneinfo/<Area/City> /etc/localtime" "WARN"
            return
        }
        Invoke-Guest "ln -sf /usr/share/zoneinfo/${ianaTz} /etc/localtime && echo ${ianaTz} > /etc/timezone" | Out-Null
        Write-Log "distro time zone set to ${ianaTz} (from Windows '${winTz}')"
    } catch {
        Write-Log "could not set the distro time zone: $($_.Exception.Message)" "WARN"
    }
}

function Copy-BundleIntoGuest {
    # Stream the bundle in as a tar over stdin. A Windows-side file copy would
    # go through DrvFs and can rewrite line endings; a single CRLF in a .sh makes
    # bash fail with "\r: command not found", and a CRLF in .env puts a trailing
    # \r inside the generated Postgres password - a failure that only shows up
    # later, as an unexplained authentication error.
    Write-Log "copying the bundle into ${GuestDir} inside the distro..."
    Invoke-Guest "mkdir -p ${GuestDir}" | Out-Null

    $tar = Join-Path $env:TEMP ("pointy-bundle-{0}.tar" -f ([guid]::NewGuid().ToString("N")))
    try {
        # bsdtar ships in Windows 10 17063+.
        #
        # wsl/ goes IN (minus its install-only inputs): update.sh adopts
        # wsl/bootstrap-wsl.ps1 out of each new bundle, and -Boot copies it back
        # out to Windows - that is the only way a fix to the LAN bridge ever
        # reaches an installed shop. The rootfs tarball and the MSI are excluded:
        # they are one-time install inputs and together are most of the bundle.
        $r = Invoke-Native -File "tar.exe" -Arguments @(
            "-cf", $tar, "-C", $BundleRoot,
            "--exclude", "./wsl/pointy-wsl-rootfs*",
            "--exclude", "./wsl/*.msi",
            ".")
        if ($r.ExitCode -ne 0) { Die "could not archive the bundle: $($r.Output.Trim())" }

        $guestTar = "/tmp/pointy-bundle.tar"
        $winTar   = $tar -replace '\\', '/'
        # Read it from the Windows filesystem in BINARY through /mnt - the copy
        # is byte-exact because tar content is opaque to DrvFs.
        $mnt = "/mnt/" + $winTar.Substring(0,1).ToLower() + $winTar.Substring(2)
        $x = Invoke-Guest "cp '${mnt}' ${guestTar} && tar -xf ${guestTar} -C ${GuestDir} && rm -f ${guestTar}" -TimeoutSec 3600
        if ($x.ExitCode -ne 0) { Die "could not unpack the bundle inside the distro: $($x.Output)" }

        Invoke-Guest "chmod +x ${GuestDir}/*.sh 2>/dev/null; true" | Out-Null
        # Belt and braces: strip any CR that survived, so bash never sees one.
        Invoke-Guest "sed -i 's/\r$//' ${GuestDir}/*.sh 2>/dev/null; true" | Out-Null
        Write-Log "bundle unpacked into ${GuestDir}"
    } finally {
        Remove-Item $tar -ErrorAction SilentlyContinue
    }
}

function Invoke-GuestInstall {
    Write-Log "running install.sh inside the distro - this is where the stack actually comes up..."
    # Stream it live: this step loads images and starts Postgres, and takes
    # minutes. A silent installer here reads as a hang.
    $code = 1
    $prev = $ErrorActionPreference
    $ErrorActionPreference = "Continue"
    try {
        # `cd` inside the command rather than wsl.exe's --cd, which only exists
        # in newer wsl.exe builds.
        & wsl.exe -d $Distro -u root -- bash -lc "cd '$GuestDir' && bash ./install.sh"
        $code = $LASTEXITCODE
    } finally { $ErrorActionPreference = $prev }
    if ($code -ne 0) { Die "install.sh failed inside the distro (exit ${code}). See the output above." }
    Write-Log "install.sh completed"
}

# The scheduled task must NOT point into the extracted bundle folder: an
# operator tidying up their Downloads directory would silently disable the LAN
# bridge, and the bundle is not where updates land anyway. Keep a copy at a
# stable path and run that.
function Install-BootstrapToStablePath {
    New-Item -ItemType Directory -Force -Path $InstallRoot | Out-Null
    foreach ($name in @("bootstrap-wsl.ps1", "collect-diagnostics.ps1", "timezone-map.txt")) {
        $src = Join-Path $PSScriptRoot $name
        if (Test-Path $src) { Copy-Item -Force $src (Join-Path $InstallRoot $name) }
    }
    Write-Log "installed the bootstrap to ${InstallRoot}"
}

# Promote a newer bootstrap that arrived inside the distro with a release
# bundle. This mirrors update-agent.sh's self-promote: the Windows half of the
# deployment has to be updatable from the Linux half, or every shop keeps the
# bridge it was installed with forever. Returns $true only when the installed
# copy verifiably changed - the supervisor then hands over to it.
function Update-BootstrapFromGuest {
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    if ($PSCommandPath -ne $stable) { return $false }   # only self-update the installed copy

    $guestPath = "${GuestDir}/wsl/bootstrap-wsl.ps1"
    $r = Invoke-Guest "test -f '${guestPath}' && sha256sum '${guestPath}' | cut -c1-64"
    if ($r.ExitCode -ne 0) { return $false }
    $guestHash = ($r.Output -replace "`0", "").Trim()
    if ($guestHash -notmatch '^[0-9a-f]{64}$') { return $false }

    $localHash = (Get-FileHash -Path $stable -Algorithm SHA256).Hash.ToLower()
    if ($guestHash -eq $localHash) { return $false }

    Write-Log "a newer bootstrap arrived with a release update; promoting it"
    foreach ($name in @("bootstrap-wsl.ps1", "collect-diagnostics.ps1", "timezone-map.txt")) {
        $win = (Join-Path $InstallRoot $name) -replace '\\', '/'
        $mnt = "/mnt/" + $win.Substring(0,1).ToLower() + $win.Substring(2)
        Invoke-Guest "test -f '${GuestDir}/wsl/${name}' && cp -f '${GuestDir}/wsl/${name}' '${mnt}'" | Out-Null
    }
    # Only a copy that verifiably landed is a promotion; anything else would
    # hand over to the very same file, forever.
    $localHash = (Get-FileHash -Path $stable -Algorithm SHA256).Hash.ToLower()
    if ($localHash -ne $guestHash) {
        Write-Log "the promoted bootstrap does not match the bundle's copy; keeping the running one" "WARN"
        return $false
    }
    return $true
}

# The install re-registers the task, which ends its running supervisor at a
# moment of Task Scheduler's choosing. End it here instead, at the start, so
# the installer's own anchor is what carries the distro through the install.
function Stop-BootTask {
    try {
        $task = Get-ScheduledTask -TaskName $TaskName -ErrorAction SilentlyContinue
        if (-not $task) { return }
        if ("$($task.State)" -eq "Running") {
            Stop-ScheduledTask -TaskName $TaskName -ErrorAction Stop
            Write-Log "stopped the running '${TaskName}' supervisor for the install; it is started again at the end"
        }
    } catch {
        Write-Log "could not stop the '${TaskName}' task: $($_.Exception.Message)" "WARN"
    }
}

function Register-BootTask {
    # ONE task. It runs the supervisor: boots the distro (systemd then runs the
    # watchdog, the update agent and the stack), holds it open, and re-points
    # the LAN bridge. Everything else that used to be a Windows scheduled task
    # is now a systemd unit inside Linux.
    $stable = Join-Path $InstallRoot "bootstrap-wsl.ps1"
    $action = New-ScheduledTaskAction -Execute "powershell.exe" -Argument (
        "-NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$stable`" " +
        "-Boot -Distro `"$Distro`" -InstallRoot `"$InstallRoot`" -ApiPort $ApiPort -WebPort $WebPort")

    $atStartup = New-ScheduledTaskTrigger -AtStartup
    $atStartup.Delay = "PT30S"
    # A clock trigger as well. Windows does not count a Fast Startup power-on
    # as a boot, so on such a machine an At-startup trigger alone never fires;
    # and should the supervisor ever exit (a handover to a newer bootstrap, a
    # crash), the repetition re-launches it within 5 minutes. While it runs,
    # IgnoreNew makes every repetition a no-op.
    $everyFiveMinutes = New-ScheduledTaskTrigger -Once -At (Get-Date).Date `
        -RepetitionInterval (New-TimeSpan -Minutes 5) `
        -RepetitionDuration (New-TimeSpan -Days 3650)

    # No execution time limit: the supervisor is meant to run until shutdown.
    $settings = New-ScheduledTaskSettingsSet `
        -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries `
        -StartWhenAvailable `
        -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) `
        -ExecutionTimeLimit ([TimeSpan]::Zero) `
        -MultipleInstances IgnoreNew

    # S4U runs as this user WITHOUT an interactive session and WITHOUT storing a
    # password. That is the whole point of the migration: Docker Desktop could
    # only run inside a logged-in session, which forced shops to enable Windows
    # auto-logon with the password in clear text under Winlogon. This does not.
    #
    # The distro is registered to THIS user's SID, so the task must run as this
    # user - not SYSTEM, which cannot see it.
    $userId = "$env:USERDOMAIN\$env:USERNAME"
    try {
        $principal = New-ScheduledTaskPrincipal -UserId $userId -LogonType S4U -RunLevel Highest
        Register-ScheduledTask -TaskName $TaskName -Action $action -Trigger @($atStartup, $everyFiveMinutes) `
            -Principal $principal -Settings $settings -Force -ErrorAction Stop | Out-Null
        Write-Log "registered scheduled task '${TaskName}' as ${userId} (LogonType=S4U): at startup, and every 5 minutes"
    } catch {
        # We deliberately do NOT prompt for the password and store it ourselves.
        # Task Scheduler asks for it in its own secure dialog and keeps it in the
        # protected credential store; routing it through this script would put
        # the shop's password in a PowerShell variable for no benefit.
        Write-Log "could not register '${TaskName}' automatically: $($_.Exception.Message)" "ERROR"
        Die ("Create the task by hand in Task Scheduler (taskschd.msc):`n" +
             "  Name    : ${TaskName}`n" +
             "  Run as  : ${userId}   <- must be THIS user; WSL distros are per-user`n" +
             "            tick 'Run whether user is logged on or not'`n" +
             "            tick 'Run with highest privileges'`n" +
             "  Triggers: At startup (delay 30s), AND daily at 00:00 repeating every 5 minutes`n" +
             "            for 3650 days; settings: no time limit, do not start a new instance`n" +
             "  Action  : powershell.exe`n" +
             "  Args    : -NoProfile -ExecutionPolicy Bypass -WindowStyle Hidden -File `"$stable`" -Boot")
    }
}


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

if ($Boot) {
    if (-not (Test-Admin)) {
        Write-Log "not elevated: the distro can be started from here, but the LAN bridge and firewall cannot be changed" "WARN"
    }
    Select-WslRunner
    if ($Once) {
        # One pass for an operator at the keyboard: start the distro if it is
        # down, re-point and prove the bridge, and make sure the supervisor
        # task is up so the distro outlives this window.
        $ok = Invoke-BootReconcile
        Start-SupervisorTask | Out-Null
        if ($ok) { exit 0 } else { exit 1 }
    }
    if (Enter-SupervisorLock) {
        Invoke-Supervise
        exit 0
    }
    Write-Log "a supervisor is already running (see ${SupervisorStateFile}); doing one reconcile pass instead"
    if (Invoke-BootReconcile) { exit 0 } else { exit 1 }
}

Write-Log "=== Pointy on-prem WSL bootstrap ==="
Assert-Preflight
Select-WslRunner
Set-ServerPowerSettings
Enable-WindowsFeatures
Install-Wsl
Stop-BootTask
$reinstall = Test-DistroExists
if ((Write-WslConfig) -and $reinstall) { Restart-WslVm }
Import-Distro
# From here to the end the distro must stay up: with no client attached, WSL
# would power it off 15 s after each step below returns, and the next step
# would boot it again. The supervisor started at the end adopts this anchor.
Start-AnchorIfMissing | Out-Null
Set-GuestTimezone
Copy-BundleIntoGuest
Invoke-GuestInstall
Install-BootstrapToStablePath
Register-BootTask
Invoke-BootReconcile | Out-Null
Start-SupervisorTask | Out-Null
Write-FirewallWarnings

$ip = Get-WslIp
$lan = @(Get-LanIPv4)
if ($lan.Count -eq 0) { $lan = @("<this-pc-lan-ip>") }

Write-Log ""
Write-Log "Done. The stack runs inside WSL distro '${Distro}' (VM address ${ip})."
Write-Log "The '${TaskName}' task holds the distro open from boot to shutdown, no logon needed,"
Write-Log "and starts it again within seconds if WSL is shut down or updated."
Write-Log ""
foreach ($address in $lan) {
    Write-Log "  Tills reach it at : http://${address}:${ApiPort}"
    Write-Log "  Browser app       : http://${address}:${WebPort}"
}
Write-Log "  Shell in          : wsl -d ${Distro} -u root --cd ${GuestDir}"
Write-Log "  Stack status      : wsl -d ${Distro} -u root --cd ${GuestDir} -- docker compose ps"
Write-Log "  Watchdog log      : wsl -d ${Distro} -u root -- journalctl -u pointy-watchdog -f"
Write-Log "  Supervisor        : Get-ScheduledTask ${TaskName}; $(Join-Path $InstallRoot 'supervisor-state.json')"
Write-Log "  If it misbehaves  : powershell -ExecutionPolicy Bypass -File `"$(Join-Path $InstallRoot 'collect-diagnostics.ps1')`""
Write-Log ""
Write-Log "Everything from here on is Linux. There is no second set of Windows scripts:"
Write-Log "updates, healing and the watchdog all run as systemd units inside the distro."
