# Generated by Django 5.2.14 on 2026-06-12 23:19

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_product_is_service_billofmaterials_bomline"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_prepared",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="unit",
            field=models.CharField(
                choices=[
                    ("piece", "Piece"),
                    ("kg", "Kilogram"),
                    ("g", "Gram"),
                    ("l", "Liter"),
                    ("ml", "Milliliter"),
                ],
                default="piece",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="bomline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
