# Generated by Django 5.2.14 on 2026-06-15 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0011_product_archived_at_product_archived_by"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="productcategory",
            options={
                "ordering": ["display_order", "name"],
                "verbose_name_plural": "product categories",
            },
        ),
        migrations.AddField(
            model_name="productcategory",
            name="display_order",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productcategory",
            name="is_quick_access",
            field=models.BooleanField(default=False),
        ),
    ]
