# Generated by Django 5.2.14 on 2026-06-16 19:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0012_alter_productcategory_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UnitOfMeasure",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.SlugField(max_length=32, unique=True)),
                ("name", models.CharField(max_length=64)),
                ("abbreviation", models.CharField(blank=True, max_length=16)),
                (
                    "dimension",
                    models.CharField(
                        choices=[
                            ("count", "Count"),
                            ("weight", "Weight"),
                            ("volume", "Volume"),
                            ("length", "Length"),
                        ],
                        default="count",
                        max_length=8,
                    ),
                ),
                (
                    "reference_factor",
                    models.DecimalField(
                        blank=True,
                        decimal_places=6,
                        max_digits=18,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("allows_fractional", models.BooleanField(default=False)),
                ("is_system", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["display_order", "name"],
            },
        ),
        migrations.AddField(
            model_name="product",
            name="default_purchase_unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="product",
            name="default_sale_unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AlterField(
            model_name="product",
            name="unit",
            field=models.CharField(default="piece", max_length=32),
        ),
        migrations.CreateModel(
            name="ProductUnit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "factor_to_base",
                    models.DecimalField(
                        decimal_places=6,
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("is_sellable", models.BooleanField(default=True)),
                ("is_purchasable", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="units",
                        to="catalog.product",
                    ),
                ),
                (
                    "unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="product_units",
                        to="catalog.unitofmeasure",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order", "id"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "unit"), name="unique_product_unit"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("factor_to_base__gt", 0)),
                        name="product_unit_factor_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("price__isnull", True), ("price__gte", 0), _connector="OR"
                        ),
                        name="product_unit_price_non_negative",
                    ),
                ],
            },
        ),
    ]
