# Generated by Django 6.0.2 on 2026-06-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0015_alter_billofmaterials_created_at_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("alias", models.CharField(max_length=255)),
                ("normalized", models.CharField(db_index=True, max_length=255)),
                (
                    "source",
                    models.CharField(
                        choices=[("invoice", "Invoice match"), ("manual", "Manual")],
                        default="manual",
                        max_length=16,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["alias"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("product", "normalized"), name="unique_product_alias"
                    )
                ],
            },
        ),
    ]
