# Generated by Django 5.2.14 on 2026-06-29 03:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_productalias"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                condition=models.Q(("archived_at__isnull", True)),
                fields=["name", "id"],
                name="product_name_live_idx",
            ),
        ),
    ]
