# Generated by Django 5.2.14 on 2026-07-05 18:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0017_product_product_name_live_idx"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductUnitBarcode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("barcode", models.CharField(max_length=64, unique=True)),
                (
                    "product_unit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="barcodes",
                        to="catalog.productunit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
