# Generated by Django 5.2.14 on 2026-07-07 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_product_unit_barcodes"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="popularity",
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
    ]
