# Generated by Django 5.2.14 on 2026-08-31 01:22

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_search_trigram_upper_indexes"),
        ("fx", "0002_seed_currencies"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="pricing_currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="priced_products",
                to="fx.currency",
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="price_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="productunit",
            name="price_rate_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="price_rate_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
