# Generated by Django 5.2.14 on 2026-09-02 00:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0022_product_pricing_currency_productunit_price_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productalias",
            name="source",
            field=models.CharField(
                choices=[
                    ("invoice", "Invoice match"),
                    ("manual", "Manual"),
                    ("ai_adjudicated", "AI adjudicated"),
                ],
                default="manual",
                max_length=16,
            ),
        ),
    ]
