# Generated by Django 5.2.14 on 2026-09-11 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_productalias_source"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScaleBarcodeRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("pattern", models.CharField(max_length=32)),
                (
                    "value_kind",
                    models.CharField(
                        choices=[
                            ("weight", "Weight"),
                            ("price", "Price"),
                            ("count", "Count"),
                        ],
                        default="weight",
                        max_length=8,
                    ),
                ),
                ("value_decimals", models.PositiveSmallIntegerField(default=3)),
                ("value_unit", models.CharField(default="kg", max_length=32)),
                ("require_check_digit", models.BooleanField(default=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sequence", models.PositiveIntegerField(default=0)),
            ],
            options={
                "ordering": ["sequence", "id"],
            },
        ),
    ]
