# Generated by Django 5.2.14 on 2026-09-11 16:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0025_seed_scale_barcode_rule"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScalePlu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("plu_number", models.PositiveIntegerField(unique=True)),
                ("label_name", models.CharField(blank=True, max_length=40)),
                ("tare_grams", models.PositiveIntegerField(default=0)),
                (
                    "shelf_life_days",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "variant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scale_plu",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "ordering": ["plu_number"],
            },
        ),
    ]
