# Generated by Django 5.2.14 on 2026-09-17 19:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0026_scaleplu"),
        ("customers", "0012_paymentcard_cardholder_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="asset_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="tracked_products",
                to="customers.assettype",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="auto_pick_strategy",
            field=models.CharField(
                choices=[
                    ("fefo", "First expiring, first out"),
                    ("fifo", "First in, first out"),
                    ("manual", "Manual select"),
                ],
                default="fefo",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="expiry_warning_days",
            field=models.PositiveIntegerField(default=30),
        ),
        migrations.AddField(
            model_name="product",
            name="prevent_selling_expired",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="shelf_life_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="product",
            name="tracking_mode",
            field=models.CharField(
                choices=[
                    ("quantity", "Quantity only"),
                    ("batch", "Batch / lot tracked"),
                    ("serial", "Individually tracked"),
                    ("serial_batch", "Serialised within a lot"),
                ],
                db_index=True,
                default="quantity",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="warranty_days",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="productvariant",
            name="gtin",
            field=models.CharField(blank=True, db_index=True, max_length=14),
        ),
    ]
