# Generated by Django 5.2.14 on 2026-09-19 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0027_identified_stock"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="expiry_required",
            field=models.BooleanField(default=False),
        ),
    ]
