# Generated by Django 5.2.14 on 2026-09-11 16:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("catalog", "0026_scaleplu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Scale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                (
                    "driver",
                    models.CharField(
                        choices=[
                            ("file_export", "ملف PLU (أي ميزان)"),
                            ("cas_cl5000", "CAS CL5000 / CL7200"),
                            ("aclas_ftp", "Aclas LS2 (FTP)"),
                        ],
                        default="file_export",
                        max_length=32,
                    ),
                ),
                ("host", models.CharField(blank=True, max_length=120)),
                ("port", models.PositiveIntegerField(default=0)),
                ("department", models.PositiveSmallIntegerField(default=1)),
                ("options", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_push_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "barcode_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scales",
                        to="catalog.scalebarcoderule",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "id"],
            },
        ),
        migrations.CreateModel(
            name="ScalePushJob",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("partial", "Partially sent"),
                            ("failed", "Failed"),
                            ("exported", "Exported to a file"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                ("plu_count", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("errors", models.JSONField(blank=True, default=dict)),
                ("message", models.TextField(blank=True)),
                ("filename", models.CharField(blank=True, max_length=120)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="scale_pushes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pushes",
                        to="scales.scale",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["scale", "-created_at"],
                        name="scales_scal_scale_i_b32d76_idx",
                    )
                ],
            },
        ),
    ]
