# Generated by Django 5.2.14 on 2026-09-11 16:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("scales", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scale",
            options={
                "ordering": ["name", "id"],
                "permissions": [("push_scale", "Can send prices to a scale")],
            },
        ),
    ]
