# Generated by Django 5.2.14 on 2026-09-29 22:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("expenses", "0006_expense_money_account_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("record_topups_as_expenses", models.BooleanField(default=True)),
                (
                    "expense_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="expenses.expensecategory",
                    ),
                ),
            ],
            options={
                "verbose_name": "wallet settings",
                "verbose_name_plural": "wallet settings",
            },
        ),
        migrations.CreateModel(
            name="WalletTopUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("relay_id", models.CharField(max_length=64, unique=True)),
                ("invoice_no", models.CharField(db_index=True, max_length=32)),
                ("method", models.CharField(max_length=40)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("paid", "Paid"),
                            ("canceled", "Canceled"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_transaction_id",
                    models.CharField(blank=True, max_length=128),
                ),
                ("test_mode", models.BooleanField(default=False)),
                ("error_code", models.CharField(blank=True, max_length=64)),
                ("record_as_expense", models.BooleanField(default=True)),
                ("relay_created_at", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("expense_booked_at", models.DateTimeField(blank=True, null=True)),
                ("expense_error", models.CharField(blank=True, max_length=255)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_topup",
                        to="expenses.expense",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-relay_created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "relay_created_at"],
                        name="wallet_topup_status_idx",
                    )
                ],
            },
        ),
    ]
