# Generated by Django 5.2.14 on 2026-10-01 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettopup",
            name="payer_hint",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=32
            ),
        ),
    ]
