# Generated by Django 5.2.14 on 2026-10-07 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("expenses", "0006_expense_money_account_and_more"),
        ("treasury", "0005_card_settlement"),
        ("wallet", "0002_topup_payer_hint"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="walletsettings",
            name="books_switched_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="walletsettings",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="walletsettings",
            name="prebooked_balance",
            field=models.DecimalField(
                blank=True, decimal_places=3, max_digits=14, null=True
            ),
        ),
        migrations.AddField(
            model_name="wallettopup",
            name="transfer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="wallet_topup",
                to="treasury.moneytransfer",
            ),
        ),
        migrations.AddField(
            model_name="wallettopup",
            name="transfer_booked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="WalletSpend",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("sms", "Moved into the SMS balance"),
                            ("plan", "A plan paid for"),
                            ("vouchers", "Moved into the voucher balance"),
                        ],
                        max_length=16,
                    ),
                ),
                ("relay_reference", models.CharField(max_length=128)),
                ("amount", models.DecimalField(decimal_places=3, max_digits=12)),
                ("description", models.CharField(max_length=255)),
                ("happened_on", models.DateField()),
                ("record_in_books", models.BooleanField(default=True)),
                (
                    "prebooked_amount",
                    models.DecimalField(decimal_places=3, default=0, max_digits=12),
                ),
                ("booked_at", models.DateTimeField(blank=True, null=True)),
                ("error", models.CharField(blank=True, max_length=255)),
                (
                    "expense",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_spend",
                        to="expenses.expense",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "transfer",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="wallet_spend",
                        to="treasury.moneytransfer",
                    ),
                ),
            ],
            options={
                "ordering": ["-happened_on", "-id"],
                "indexes": [
                    models.Index(
                        fields=["booked_at", "created_at"], name="wallet_spend_owed_idx"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("kind", "relay_reference"), name="wallet_unique_spend"
                    )
                ],
            },
        ),
    ]
