# Generated by Django 5.2.14 on 2026-10-09 01:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet", "0003_wallet_in_the_books"),
    ]

    operations = [
        migrations.AddField(
            model_name="wallettopup",
            name="decided_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="wallettopup",
            name="error_detail",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="wallettopup",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("canceled", "Canceled"),
                    ("failed", "Failed"),
                    ("expired", "Expired"),
                    ("review", "In review"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=16,
            ),
        ),
    ]
