# Generated by Django 6.0.2 on 2026-06-06 00:10

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("job_title", models.CharField(blank=True, max_length=120)),
                ("department", models.CharField(blank=True, max_length=120)),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("full_time", "Full time"),
                            ("part_time", "Part time"),
                            ("contractor", "Contractor"),
                            ("seasonal", "Seasonal"),
                            ("intern", "Intern"),
                            ("other", "Other"),
                        ],
                        default="full_time",
                        max_length=24,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("on_leave", "On leave"),
                            ("inactive", "Inactive"),
                            ("terminated", "Terminated"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=24,
                    ),
                ),
                (
                    "hire_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("termination_date", models.DateField(blank=True, null=True)),
                (
                    "emergency_contact_name",
                    models.CharField(blank=True, max_length=255),
                ),
                (
                    "emergency_contact_phone",
                    models.CharField(blank=True, max_length=64),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "user",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["full_name", "employee_number"],
            },
        ),
        migrations.CreateModel(
            name="CompensationPlan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "pay_type",
                    models.CharField(
                        choices=[
                            ("monthly_salary", "Monthly salary"),
                            ("weekly_salary", "Weekly salary"),
                            ("daily_rate", "Daily rate"),
                            ("hourly", "Hourly"),
                            ("per_shift", "Per shift"),
                            ("commission", "Commission"),
                            ("contract", "Contract"),
                            ("other", "Other"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("currency", models.CharField(default="LYD", max_length=8)),
                (
                    "expected_units_per_period",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "effective_from",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("effective_to", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="compensation_plans",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_from", "-id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "units",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("1.00"),
                        max_digits=8,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "gross_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "additions_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "compensation_plan",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_lines",
                        to="employees.compensationplan",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payroll_lines",
                        to="employees.employee",
                    ),
                ),
            ],
            options={
                "ordering": ["employee__full_name", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "direction",
                    models.CharField(
                        choices=[("addition", "Addition"), ("deduction", "Deduction")],
                        max_length=16,
                    ),
                ),
                (
                    "adjustment_type",
                    models.CharField(
                        choices=[
                            ("bonus", "Bonus"),
                            ("commission", "Commission"),
                            ("overtime", "Overtime"),
                            ("reimbursement", "Reimbursement"),
                            ("advance", "Advance"),
                            ("absence", "Absence"),
                            ("penalty", "Penalty"),
                            ("other", "Other"),
                        ],
                        max_length=24,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "payroll_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="employees.payrollline",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at", "id"],
            },
        ),
        migrations.CreateModel(
            name="PayrollRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "run_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("approved", "Approved"),
                            ("paid", "Paid"),
                            ("void", "Void"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=16,
                    ),
                ),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("payment_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "gross_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "additions_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "deductions_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "net_total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("voided_at", models.DateTimeField(blank=True, null=True)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "paid_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="paid_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voided_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voided_payroll_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-period_end", "-created_at"],
                "permissions": [
                    ("approve_payrollrun", "Can approve payroll run"),
                    ("mark_payrollrun_paid", "Can mark payroll run paid"),
                    ("void_payrollrun", "Can void payroll run"),
                ],
            },
        ),
        migrations.AddField(
            model_name="payrollline",
            name="payroll_run",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="employees.payrollrun",
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["status", "full_name"], name="employees_e_status_d5d37b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employee",
            index=models.Index(
                fields=["department", "job_title"],
                name="employees_e_departm_f8c4b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compensationplan",
            index=models.Index(
                fields=["employee", "is_active", "effective_from"],
                name="employees_c_employe_a115f0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="compensationplan",
            index=models.Index(
                fields=["pay_type", "effective_from"],
                name="employees_c_pay_typ_cff3e2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="compensationplan",
            constraint=models.UniqueConstraint(
                fields=("employee", "effective_from", "pay_type"),
                name="unique_employee_pay_type_start",
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["status", "period_end"], name="employees_p_status_5efb8e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="payrollrun",
            index=models.Index(
                fields=["period_start", "period_end"],
                name="employees_p_period__04bf40_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="payroll_run_period_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="payrollline",
            constraint=models.UniqueConstraint(
                fields=("payroll_run", "employee"),
                name="unique_employee_per_payroll_run",
            ),
        ),
    ]
