# Generated by Codex on 2026-06-07

from decimal import Decimal

from django.db import migrations, models


def infer_salary_types(apps, schema_editor):
    CompensationPlan = apps.get_model("employees", "CompensationPlan")
    CompensationPlan.objects.filter(
        pay_type="monthly_salary",
        commission_percent__gt=Decimal("0.00"),
    ).update(salary_type="monthly_fixed_plus_sales_commission")
    CompensationPlan.objects.filter(
        pay_type="monthly_salary",
        commission_percent=Decimal("0.00"),
    ).update(salary_type="monthly_fixed")
    CompensationPlan.objects.filter(
        pay_type="commission",
        amount=Decimal("0.00"),
        commission_percent__gt=Decimal("0.00"),
    ).update(salary_type="sales_commission_only")


def clear_salary_types(apps, schema_editor):
    CompensationPlan = apps.get_model("employees", "CompensationPlan")
    CompensationPlan.objects.update(salary_type="")


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_compensationplan_commission_percent_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationplan",
            name="salary_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly_fixed", "Monthly fixed"),
                    ("sales_commission_only", "Sales commission only"),
                    (
                        "monthly_fixed_plus_sales_commission",
                        "Monthly fixed plus sales commission",
                    ),
                ],
                db_index=True,
                default="",
                max_length=48,
            ),
        ),
        migrations.AddIndex(
            model_name="compensationplan",
            index=models.Index(
                fields=["salary_type", "effective_from"],
                name="employees_c_salary__a5007e_idx",
            ),
        ),
        migrations.RunPython(infer_salary_types, clear_salary_types),
    ]
