# Generated by Django 5.2.14 on 2026-06-07 17:03

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_payrollline_adjustment_fields"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrolladjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("bonus", "Bonus"),
                    ("commission", "Commission"),
                    ("overtime", "Overtime"),
                    ("reimbursement", "Reimbursement"),
                    ("advance", "Advance"),
                    ("loan", "Loan"),
                    ("absence", "Absence"),
                    ("penalty", "Penalty"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLoan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("requested", "Requested"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("cancelled", "Cancelled"),
                            ("paid", "Paid"),
                        ],
                        db_index=True,
                        default="requested",
                        max_length=16,
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "monthly_deduction",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                (
                    "outstanding_balance",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0.00"),
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                ("purpose", models.TextField(blank=True)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loans",
                        to="employees.employee",
                    ),
                ),
                (
                    "requested_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="requested_employee_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_employee_loans",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    ("approve_employeeloan", "Can approve employee loan"),
                    ("reject_employeeloan", "Can reject employee loan"),
                ],
            },
        ),
        migrations.AddField(
            model_name="payrolladjustment",
            name="loan",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_adjustments",
                to="employees.employeeloan",
            ),
        ),
        migrations.CreateModel(
            name="EmployeeLoanPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("paid_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "loan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="employees.employeeloan",
                    ),
                ),
                (
                    "payroll_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="loan_payments",
                        to="employees.payrollline",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
            },
        ),
        migrations.AddIndex(
            model_name="employeeloan",
            index=models.Index(
                fields=["employee", "status", "created_at"],
                name="employees_e_employe_42f807_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="employeeloan",
            index=models.Index(
                fields=["status", "created_at"], name="employees_e_status_717574_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeloanpayment",
            index=models.Index(
                fields=["loan", "paid_at"], name="employees_e_loan_id_70fe0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="employeeloanpayment",
            index=models.Index(
                fields=["payroll_line"], name="employees_e_payroll_2f9895_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="employeeloanpayment",
            constraint=models.UniqueConstraint(
                fields=("loan", "payroll_line"),
                name="unique_employee_loan_payment_per_payroll_line",
            ),
        ),
    ]
