# Generated by Django 5.2.14 on 2026-06-13 02:29

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "employees",
            "0005_alter_payrolladjustment_adjustment_type_employeeloan_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationplan",
            name="overtime_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.50"),
                help_text="Overtime pay rate as a multiple of the hourly wage (e.g. 1.50).",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("10.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="compensationplan",
            name="standard_daily_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("8.00"),
                help_text="Hours in a standard working day, used to derive the hourly wage.",
                max_digits=4,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                    django.core.validators.MaxValueValidator(Decimal("24.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="overtime_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=12,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="overtime_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=7,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="payrollline",
            name="overtime_multiplier",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("1.50"),
                max_digits=4,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
