# Generated by Django 5.2.14 on 2026-06-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0006_compensationplan_overtime_multiplier_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="compensationplan",
            name="salary_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("monthly_fixed", "Monthly fixed"),
                    ("weekly_fixed", "Weekly fixed"),
                    ("daily_rate", "Daily rate"),
                    ("hourly_rate", "Hourly rate"),
                    ("per_shift", "Per shift"),
                    ("sales_commission_only", "Sales commission only"),
                    (
                        "monthly_fixed_plus_sales_commission",
                        "Monthly fixed plus sales commission",
                    ),
                    ("operations_commission_only", "Operations commission only"),
                    (
                        "monthly_fixed_plus_operations_commission",
                        "Monthly fixed plus operations commission",
                    ),
                    ("contract_fixed", "Contract fixed"),
                    ("custom_fixed", "Custom fixed"),
                ],
                db_index=True,
                default="",
                max_length=48,
            ),
        ),
    ]
