# Generated by Django 5.2.14 on 2026-06-13 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0007_alter_compensationplan_salary_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="compensationplan",
            name="operations_commission_base",
            field=models.CharField(
                choices=[
                    ("approved_price", "Approved repair price"),
                    ("labor", "Labor only"),
                    ("order_total", "Invoiced order total"),
                ],
                default="approved_price",
                max_length=24,
            ),
        ),
    ]
