# Generated by Django 5.2.14 on 2026-08-28 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0009_alter_compensationplan_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payrollrun",
            name="payment_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
