# Generated by Django 5.2.14 on 2026-09-23 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_paymentcard_cardholder_name"),
        ("employees", "0012_backfill_payroll_run_lifecycle"),
        ("payments", "0013_payment_method_salary_deduction"),
        ("sales", "0037_order_extra_discount_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="customer",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_employee",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="payrolladjustment",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_adjustments",
                to="sales.order",
            ),
        ),
        migrations.AddField(
            model_name="payrolladjustment",
            name="settlement_payment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_adjustment",
                to="payments.payment",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("bonus", "Bonus"),
                    ("commission", "Commission"),
                    ("overtime", "Overtime"),
                    ("reimbursement", "Reimbursement"),
                    ("advance", "Advance"),
                    ("loan", "Loan"),
                    ("absence", "Absence"),
                    ("penalty", "Penalty"),
                    ("staff_purchase", "Staff purchase"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
    ]
