# Generated by Django 5.2.14 on 2026-09-25 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0002_employee_balance_entries"),
        ("employees", "0014_backfill_staff_customers"),
        ("sales", "0039_order_sale_type_account_entry"),
        ("treasury", "0004_moneyaccount_bank_slug_moneyaccount_iban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="employeeloan",
            name="cash_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_loan",
                to="sales.registercashmovement",
            ),
        ),
        migrations.AddField(
            model_name="employeeloan",
            name="disbursed_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="employeeloan",
            name="disbursed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="disbursed_employee_loans",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="employeeloan",
            name="disbursement_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Cash"), ("transfer", "Bank transfer")],
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="employeeloan",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="employee_loans",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddField(
            model_name="payrolladjustment",
            name="balance_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payroll_adjustments",
                to="balances.employeebalanceentry",
            ),
        ),
        migrations.AlterField(
            model_name="payrolladjustment",
            name="adjustment_type",
            field=models.CharField(
                choices=[
                    ("bonus", "Bonus"),
                    ("commission", "Commission"),
                    ("overtime", "Overtime"),
                    ("reimbursement", "Reimbursement"),
                    ("advance", "Advance"),
                    ("loan", "Loan"),
                    ("absence", "Absence"),
                    ("penalty", "Penalty"),
                    ("staff_purchase", "Staff purchase"),
                    ("account_balance", "Account balance"),
                    ("other", "Other"),
                ],
                max_length=24,
            ),
        ),
    ]
