# Generated by Django 5.2.14 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="supplier",
            name="address",
            field=models.TextField(blank=True),
        ),
    ]
