# Generated by Django 5.2.14 on 2026-05-20 08:07

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


def backfill_effective_unit_cost(apps, schema_editor):
    PurchaseLine = apps.get_model("purchasing", "PurchaseLine")
    PurchaseLine.objects.update(effective_unit_cost=models.F("unit_cost"))


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0006_supplier_invoice_control"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="allocated_landed_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="effective_unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="landed_unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="customs_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="handling_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="landed_cost_allocation_method",
            field=models.CharField(
                choices=[("line_value", "By line value"), ("quantity", "By quantity")],
                default="line_value",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="shipping_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.RunPython(
            backfill_effective_unit_cost,
            migrations.RunPython.noop,
        ),
    ]
