# Generated by Django 5.2.14 on 2026-05-20 08:25

from decimal import Decimal

import django.db.models.deletion
from django.db import migrations, models


def backfill_adjustment_amounts(apps, schema_editor):
    PurchaseOrderAdjustment = apps.get_model("purchasing", "PurchaseOrderAdjustment")
    for adjustment in PurchaseOrderAdjustment.objects.only("pk", "amount"):
        amount = adjustment.amount or Decimal("0.00")
        adjustment.outbound_amount = amount
        adjustment.replacement_amount = Decimal("0.00")
        adjustment.net_amount = -amount
        adjustment.save(
            update_fields=[
                "outbound_amount",
                "replacement_amount",
                "net_amount",
            ],
        )


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_remove_product_tax_rate"),
        ("purchasing", "0007_purchaseline_allocated_landed_cost_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorderadjustment",
            name="net_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchaseorderadjustment",
            name="outbound_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="purchaseorderadjustment",
            name="replacement_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(
            backfill_adjustment_amounts,
            migrations.RunPython.noop,
        ),
        migrations.CreateModel(
            name="PurchaseOrderAdjustmentReplacementLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("quantity", models.PositiveIntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "adjustment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replacement_lines",
                        to="purchasing.purchaseorderadjustment",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
