# Generated by Codex on 2026-05-20

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


MONEY_PLACES = Decimal("0.01")


def backfill_purchase_discount_amounts(apps, schema_editor):
    PurchaseLine = apps.get_model("purchasing", "PurchaseLine")
    PurchaseOrderAdjustmentLine = apps.get_model(
        "purchasing",
        "PurchaseOrderAdjustmentLine",
    )

    for line in PurchaseLine.objects.only(
        "pk",
        "quantity",
        "unit_cost",
        "discount_amount",
        "net_line_total",
        "net_unit_cost",
    ):
        line.discount_amount = Decimal("0.00")
        line.net_line_total = (line.unit_cost * line.quantity).quantize(MONEY_PLACES)
        line.net_unit_cost = line.unit_cost
        line.save(
            update_fields=[
                "discount_amount",
                "net_line_total",
                "net_unit_cost",
            ],
        )

    for line in PurchaseOrderAdjustmentLine.objects.only(
        "pk",
        "quantity",
        "unit_cost",
        "line_amount",
    ):
        line.line_amount = (line.unit_cost * line.quantity).quantize(MONEY_PLACES)
        line.save(update_fields=["line_amount"])


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0009_purchase_order_workflow_audit_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="discount_codes",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="discount_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="net_line_total",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="net_unit_cost",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=10,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.00")),
                ],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorderadjustmentline",
            name="line_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.RunPython(
            backfill_purchase_discount_amounts,
            migrations.RunPython.noop,
        ),
    ]
