# Generated by Codex on 2026-06-03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0013_purchase_order_landed_cost_entries"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchaseorder",
            name="shipping_amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="customs_amount",
        ),
        migrations.RemoveField(
            model_name="purchaseorder",
            name="handling_amount",
        ),
    ]
