# Generated by Codex on 2026-06-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchasing", "0015_alter_purchaseorder_landed_cost_allocation_method"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name="purchasereceiptline",
            name="expiry_date",
            field=models.DateField(blank=True, db_index=True, null=True),
        ),
    ]
