# Generated by Django 5.2.14 on 2026-06-16 20:08

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0016_purchase_line_expiry_dates"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="unit",
            field=models.CharField(blank=True, default="", max_length=32),
        ),
        migrations.AddField(
            model_name="purchaseline",
            name="unit_factor",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("1"),
                max_digits=18,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.000001"))
                ],
            ),
        ),
    ]
