# Generated by Django 5.2.14 on 2026-06-29 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0019_purchaseorder_special_day_keys"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="purchaseorder",
            index=models.Index(
                fields=["status", "-created_at"], name="po_status_created_idx"
            ),
        ),
    ]
