# Generated by Django 5.2.14 on 2026-07-05 23:41

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0021_decimal_quantities"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="extra_discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
