# Generated by Django 5.2.14 on 2026-07-22 01:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0022_extra_discount_amount"),
        ("sales", "0025_alter_order_options_orderexchange"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="purchaseorder",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("edit_draft_purchaseorder", "Can edit draft purchase order"),
                    ("receive_purchaseorder", "Can receive purchase order"),
                    (
                        "adjust_received_purchaseorder",
                        "Can adjust received purchase order",
                    ),
                    ("cancel_purchaseorder", "Can cancel purchase order"),
                    ("add_pos_cash_purchase", "Can create POS cash purchase"),
                ],
            },
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="cash_movement",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payment",
                to="sales.registercashmovement",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="register_session",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="sales.registersession",
            ),
        ),
    ]
