# Generated by Django 5.2.14 on 2026-08-31 03:00

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fx", "0002_seed_currencies"),
        ("purchasing", "0025_supplierpayment_supplier_payment_method_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseline",
            name="unit_cost_in_currency",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="fx.currency",
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="exchange_rate",
            field=models.DecimalField(
                blank=True,
                decimal_places=8,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="rate_effective_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="purchaseorder",
            name="rate_source",
            field=models.CharField(blank=True, default="", max_length=16),
        ),
    ]
