# Generated by Django 6.0.2 on 2026-09-02 04:58

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0023_alter_productalias_source"),
        ("purchasing", "0026_purchaseline_unit_cost_in_currency_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierPurchaseProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("weighted_orders", models.FloatField(default=0.0)),
                ("rebuilt_at", models.DateTimeField(blank=True, null=True)),
                ("version", models.PositiveIntegerField(default=0)),
                (
                    "supplier",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_profile",
                        to="purchasing.supplier",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="SupplierPurchaseAffinity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("together_count", models.PositiveIntegerField(default=0)),
                ("confidence", models.FloatField(default=0.0)),
                (
                    "anchor_variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_affinities",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="+",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supplier", "anchor_variant", "-confidence"],
                        name="purch_affinity_anchor_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "anchor_variant", "variant"),
                        name="purchasing_affinity_pair_uniq",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="SupplierPurchaseHabit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("order_count", models.PositiveIntegerField(default=0)),
                ("weighted_count", models.FloatField(default=0.0)),
                ("last_ordered_at", models.DateTimeField(blank=True, null=True)),
                (
                    "typical_quantity",
                    models.DecimalField(
                        blank=True,
                        decimal_places=3,
                        max_digits=12,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0"))
                        ],
                    ),
                ),
                (
                    "typical_unit",
                    models.CharField(blank=True, default="", max_length=32),
                ),
                (
                    "typical_unit_factor",
                    models.DecimalField(
                        decimal_places=6,
                        default=Decimal("1"),
                        max_digits=18,
                        validators=[
                            django.core.validators.MinValueValidator(
                                Decimal("0.000001")
                            )
                        ],
                    ),
                ),
                ("quantity_confidence", models.FloatField(default=0.0)),
                ("avg_interval_days", models.FloatField(blank=True, null=True)),
                ("interval_cv", models.FloatField(blank=True, null=True)),
                ("next_due_at", models.DateTimeField(blank=True, null=True)),
                ("presence_ratio", models.FloatField(default=0.0)),
                ("avg_position", models.FloatField(default=0.0)),
                (
                    "last_base_unit_cost",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.00"))
                        ],
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_habits",
                        to="purchasing.supplier",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="purchase_habits",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["supplier", "-weighted_count"],
                        name="purch_habit_rank_idx",
                    ),
                    models.Index(
                        fields=["supplier", "next_due_at"],
                        name="purch_habit_due_idx",
                    ),
                    models.Index(
                        fields=["supplier", "-presence_ratio"],
                        name="purch_habit_basket_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("supplier", "variant"),
                        name="purchasing_habit_supplier_variant_uniq",
                    )
                ],
            },
        ),
    ]
