# Generated by Django 5.2.14 on 2026-09-07 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_stock_transfers"),
        ("purchasing", "0031_backfill_purchase_receipt_lifecycle"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="purchase_orders",
                to="inventory.warehouse",
            ),
        ),
    ]
