# Generated by Django 6.0.2 on 2026-09-22 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0034_seed_order_number_series"),
        ("sales", "0037_order_extra_discount_amount"),
        ("treasury", "0004_moneyaccount_bank_slug_moneyaccount_iban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="supplierpayment",
            name="money_account",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_payments",
                to="treasury.moneyaccount",
            ),
        ),
        migrations.AddIndex(
            model_name="supplierpayment",
            index=models.Index(
                fields=["money_account", "method", "-paid_at"],
                name="supplier_payment_account_idx",
            ),
        ),
    ]
