# Generated by Django 5.2.14 on 2026-09-25 20:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balances", "0001_party_balance_entries"),
        ("purchasing", "0035_supplierpayment_money_account_and_more"),
        ("sales", "0039_order_sale_type_account_entry"),
        ("treasury", "0004_moneyaccount_bank_slug_moneyaccount_iban"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="suppliercredit",
            name="balance_entry",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_credit",
                to="balances.supplierbalanceentry",
            ),
        ),
        migrations.AddField(
            model_name="supplierpayment",
            name="balance_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="balances.supplierbalanceentry",
            ),
        ),
        migrations.AlterField(
            model_name="suppliercredit",
            name="adjustment",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_credit",
                to="purchasing.purchaseorderadjustment",
            ),
        ),
        migrations.AlterField(
            model_name="suppliercredit",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="supplier_credits",
                to="purchasing.purchaseorder",
            ),
        ),
        migrations.AddConstraint(
            model_name="supplierpayment",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("purchase_order__isnull", True),
                    ("balance_entry__isnull", True),
                    _connector="OR",
                ),
                name="supplier_payment_settles_one_thing",
            ),
        ),
    ]
