# Generated by Django 5.2.14 on 2026-09-26 23:38
"""Purchase-line unit costs keep six places, the money beside them two.

Widening only — every stored value is still exactly representable, and code
from before this release reads and writes the column unchanged, so it is safe
under a rolling update. What it enables: a line keyed as a total ("15 for
58.00") is saved as 3.866667 each and adds back up to 58.00, where two places
made it 3.87 and 58.05. See ``apps.purchasing.unit_costs``.
"""

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("purchasing", "0036_supplier_balance_entries"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseline",
            name="effective_unit_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="landed_unit_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="net_unit_cost",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=6,
                max_digits=18,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
        migrations.AlterField(
            model_name="purchaseline",
            name="unit_cost_in_currency",
            field=models.DecimalField(
                blank=True,
                decimal_places=6,
                max_digits=18,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
