import 'package:flutter_test/flutter_test.dart';
import 'package:pdf/pdf.dart';
import 'package:pointy_frontend/src/features/reports/pdf/report_pdf.dart';

void main() {
  const testLabels = ReportPdfLabels(
    generatedAt: 'Generated at',
    generatedBy: 'Generated by',
    reference: 'Reference',
    period: 'Period',
    fromDate: 'From',
    toDate: 'To',
    summary: 'Summary',
    auditTrail: 'Audit trail',
    auditTime: 'Time',
    auditAction: 'Action',
    auditActor: 'Actor',
    auditNote: 'Note',
    page: 'Page',
    ofPages: 'of',
    emptyValue: '-',
    typeLabels: {
      BusinessReportType.salesSummary: 'Sales summary',
      BusinessReportType.paymentSummary: 'Payment summary',
      BusinessReportType.registerSessionArchive: 'Register session archive',
      BusinessReportType.inventorySnapshot: 'Inventory snapshot',
      BusinessReportType.stockMovementArchive: 'Stock movement archive',
      BusinessReportType.purchasingSummary: 'Purchasing summary',
      BusinessReportType.customerStatement: 'Customer statement',
      BusinessReportType.supplierStatement: 'Supplier statement',
      BusinessReportType.discountAudit: 'Discount audit',
      BusinessReportType.auditTrail: 'Audit trail',
    },
  );

  final generatedAt = DateTime(2026, 5, 21, 10, 30);

  BusinessReportPdfDocument buildReport() {
    return BusinessReportPdfDocument(
      type: BusinessReportType.salesSummary,
      title: 'Sales Summary',
      businessName: 'Pointy Store',
      generatedAt: generatedAt,
      generatedBy: 'Manager',
      reference: 'RPT-1',
      period: ReportPdfPeriod(
        start: DateTime(2026, 5),
        end: DateTime(2026, 5, 21),
      ),
      metrics: const [
        ReportPdfMetric(label: 'Net sales', value: '150.00 LYD'),
        ReportPdfMetric(label: 'Orders', value: '12'),
      ],
      summaryFields: const [ReportPdfField(label: 'Cashier', value: 'Amina')],
      tables: const [
        ReportPdfTable(
          title: 'Top products',
          columns: ['Product', 'Qty', 'Total'],
          rows: [
            ['Notebook', '4', '40.00'],
            ['Pen', '10', '10.00'],
          ],
        ),
      ],
      auditTrail: [
        ReportPdfAuditEntry(
          occurredAt: generatedAt,
          action: 'Generated',
          actor: 'Manager',
          note: 'Initial archive copy',
        ),
      ],
    );
  }

  test('generates non-empty PDF bytes for an A4 report', () async {
    const generator = ReportPdfGenerator(labels: testLabels);
    final bytes = await generator.generate(
      buildReport(),
      fonts: ReportPdfFonts.type1ForTests(),
    );

    expect(bytes, isNotEmpty);
    expect(String.fromCharCodes(bytes.take(5)), '%PDF-');
  });

  test('uses A4 by default for printer layout callbacks', () async {
    final service = ReportPrintingService(
      generator: const ReportPdfGenerator(labels: testLabels),
      fonts: ReportPdfFonts.type1ForTests(),
    );
    final callback = service.layoutCallback(buildReport());
    final bytes = await callback(PdfPageFormat.roll80);

    expect(bytes, isNotEmpty);
    expect(String.fromCharCodes(bytes.take(5)), '%PDF-');
  });

  test('suggests stable report file names', () {
    final report = buildReport();

    expect(report.suggestedFileName, 'Sales_Summary_20260521.pdf');
  });
}
