# Generated by Django 6.0.2 on 2026-09-19 18:11

import apps.core.secret_box
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="IntegrationAccount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hdbox", "hdbox"),
                            ("lnet", "lnet"),
                            ("qareeb", "qareeb"),
                        ],
                        max_length=32,
                        unique=True,
                    ),
                ),
                ("base_url", models.CharField(blank=True, max_length=255)),
                ("username", models.CharField(blank=True, max_length=120)),
                ("secrets_encrypted", models.TextField(blank=True, editable=False)),
                ("config", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("last_checked_at", models.DateTimeField(blank=True, null=True)),
                ("last_connected_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                ("last_error_code", models.CharField(blank=True, max_length=40)),
                ("last_error_at", models.DateTimeField(blank=True, null=True)),
                (
                    "balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("balance_at", models.DateTimeField(blank=True, null=True)),
                ("account_label", models.CharField(blank=True, max_length=120)),
            ],
            options={
                "ordering": ["provider"],
                "permissions": [
                    ("manage_integrations", "Can configure resale provider accounts"),
                    (
                        "use_integrations",
                        "Can look up and recharge on a provider account",
                    ),
                ],
            },
            bases=(apps.core.secret_box.SecretStorageMixin, models.Model),
        ),
    ]
