# Generated by Django 6.0.2 on 2026-09-19 19:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
        ("sales", "0035_reservation_stock_unit"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationFulfillment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hdbox", "hdbox"),
                            ("lnet", "lnet"),
                            ("qareeb", "qareeb"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subscriber_ref", models.CharField(db_index=True, max_length=64)),
                ("option_code", models.CharField(max_length=64)),
                ("option_label", models.CharField(blank=True, max_length=160)),
                ("months", models.PositiveIntegerField(default=0)),
                ("package_id", models.CharField(blank=True, max_length=32)),
                ("package_name", models.CharField(blank=True, max_length=160)),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Sold, not yet sent to the provider"),
                            ("submitted", "Sent, awaiting confirmation"),
                            ("confirmed", "Seen in the provider's own log"),
                            ("failed", "The provider refused it"),
                            ("cancelled", "The sale was voided"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_reference",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("provider_receipt", models.JSONField(blank=True, default=dict)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                ("confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("last_error", models.TextField(blank=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="fulfillments",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "order_line",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_fulfillment",
                        to="sales.orderline",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "subscriber_ref"],
                        name="integration_provide_4dbbc6_idx",
                    ),
                    models.Index(
                        fields=["status", "created_at"],
                        name="integration_status_026e3a_idx",
                    ),
                ],
            },
        ),
    ]
