# Generated by Django 6.0.2 on 2026-09-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0002_integrationfulfillment"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationaccount",
            name="markup_kind",
            field=models.CharField(
                choices=[
                    ("none", "Sell at cost"),
                    ("percent", "Percentage on top"),
                    ("amount", "Fixed amount on top"),
                ],
                default="none",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="integrationaccount",
            name="markup_value",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
    ]
