# Generated by Django 6.0.2 on 2026-09-19 20:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_integrationaccount_markup_kind_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationOptionPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("option_code", models.CharField(max_length=64)),
                ("label", models.CharField(blank=True, max_length=160)),
                ("kind", models.CharField(blank=True, max_length=16)),
                ("months", models.PositiveIntegerField(default=0)),
                ("package_name", models.CharField(blank=True, max_length=160)),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "last_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("last_seen_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="option_prices",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["kind", "months", "option_code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "option_code"),
                        name="integrations_unique_option_price",
                    )
                ],
            },
        ),
    ]
