# Generated by Django 6.0.2 on 2026-09-19 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_integrationoptionprice"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationoptionprice",
            name="suggested_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
    ]
