# Generated by Django 6.0.2 on 2026-09-19 22:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0005_integrationoptionprice_suggested_price"),
        ("treasury", "0003_alter_moneyaccount_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationaccount",
            name="money_account",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="integration_account",
                to="treasury.moneyaccount",
            ),
        ),
    ]
