# Generated by Django 6.0.2 on 2026-09-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0012_paymentcard_cardholder_name"),
        ("integrations", "0006_integrationaccount_money_account"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hdbox", "hdbox"),
                            ("lnet", "lnet"),
                            ("qareeb", "qareeb"),
                        ],
                        max_length=32,
                    ),
                ),
                ("subscriber_ref", models.CharField(db_index=True, max_length=64)),
                ("display_name", models.CharField(blank=True, max_length=160)),
                ("note", models.CharField(blank=True, max_length=255)),
                ("package_name", models.CharField(blank=True, max_length=160)),
                ("device_model", models.CharField(blank=True, max_length=120)),
                ("provider_status", models.CharField(blank=True, max_length=64)),
                (
                    "price_per_month",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "expire_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "card_balance",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("purchase_count", models.PositiveIntegerField(default=0)),
                (
                    "lifetime_spend",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("last_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subscribers",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="integration_subscribers",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["provider", "subscriber_ref"],
                        name="integration_provide_5396a1_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "subscriber_ref"),
                        name="integrations_unique_subscriber",
                    )
                ],
            },
        ),
    ]
