# Generated by Django 6.0.2 on 2026-09-19 22:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0007_integrationsubscriber"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationfulfillment",
            name="subscriber",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="fulfillments",
                to="integrations.integrationsubscriber",
            ),
        ),
    ]
