# Generated by Django 6.0.2 on 2026-09-20 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0008_integrationfulfillment_subscriber"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integrationaccount",
            options={
                "ordering": ["provider"],
                "permissions": [
                    ("manage_integrations", "Can configure resale provider accounts"),
                    (
                        "use_integrations",
                        "Can look up and recharge on a provider account",
                    ),
                    (
                        "record_integration_topup",
                        "Can record money paid into a provider float",
                    ),
                ],
            },
        ),
    ]
