# Generated by Django 5.2.14 on 2026-09-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0009_alter_integrationaccount_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationfulfillment",
            name="attempt_count",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="integrationfulfillment",
            name="last_error_code",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
