# Generated by Django 5.2.14 on 2026-09-23 00:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0010_integrationfulfillment_attempt_count_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationSearch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("term", models.CharField(max_length=64)),
                ("search_by", models.CharField(blank=True, max_length=32)),
                ("match_count", models.PositiveIntegerField(default=1)),
                ("card_no", models.CharField(blank=True, max_length=64)),
                ("holder_name", models.CharField(blank=True, max_length=160)),
                ("package_name", models.CharField(blank=True, max_length=160)),
                ("search_count", models.PositiveIntegerField(default=1)),
                ("last_searched_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "subscriber",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="searches",
                        to="integrations.integrationsubscriber",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_searched_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "-last_searched_at", "-id"],
                        name="integ_search_recent_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "search_by", "term"),
                        name="integrations_unique_search",
                    )
                ],
            },
        ),
    ]
