# Generated by Django 5.2.14 on 2026-09-23 13:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0032_product_system_kind"),
        ("integrations", "0011_integrationsearch"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationVoucherBrand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=32)),
                ("name", models.CharField(max_length=160)),
                ("name_en", models.CharField(blank=True, max_length=160)),
                ("category", models.CharField(blank=True, max_length=160)),
                ("currency", models.CharField(default="LYD", max_length=8)),
                ("logo_path", models.CharField(blank=True, max_length=255)),
                ("is_listed", models.BooleanField(default=True)),
                ("items_inline", models.BooleanField(default=False)),
                ("items_synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_brands",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "product",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher_brand",
                        to="catalog.product",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="IntegrationVoucher",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=64)),
                ("label", models.CharField(max_length=160)),
                (
                    "face_amount",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=12, null=True
                    ),
                ),
                ("cost", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "suggested_price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("is_available", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "variant",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="voucher",
                        to="catalog.productvariant",
                    ),
                ),
                (
                    "brand",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="vouchers",
                        to="integrations.integrationvoucherbrand",
                    ),
                ),
            ],
            options={
                "ordering": ["brand__name", "face_amount", "label"],
            },
        ),
        migrations.AddConstraint(
            model_name="integrationvoucherbrand",
            constraint=models.UniqueConstraint(
                fields=("account", "code"), name="integrations_unique_voucher_brand"
            ),
        ),
        migrations.AddConstraint(
            model_name="integrationvoucher",
            constraint=models.UniqueConstraint(
                fields=("account", "code"), name="integrations_unique_voucher"
            ),
        ),
    ]
