# Generated by Django 5.2.14 on 2026-09-25 15:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0012_voucher_shelf"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="integrationaccount",
            options={
                "ordering": ["provider"],
                "permissions": [
                    ("manage_integrations", "Can configure resale provider accounts"),
                    (
                        "use_integrations",
                        "Can look up and recharge on a provider account",
                    ),
                    (
                        "record_integration_topup",
                        "Can record money paid into a provider float",
                    ),
                    (
                        "record_portal_payment",
                        "Can record a payment made on the provider's website as a sale",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="integrationaccount",
            name="payments_covered_since",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationaccount",
            name="payments_synced_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationfulfillment",
            name="performed_outside",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.CreateModel(
            name="ProviderPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "provider",
                    models.CharField(
                        choices=[
                            ("hdbox", "hdbox"),
                            ("lnet", "lnet"),
                            ("qareeb", "qareeb"),
                        ],
                        max_length=32,
                    ),
                ),
                ("reference", models.CharField(max_length=64)),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                (
                    "amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "cost",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                (
                    "balance_after",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=12, null=True
                    ),
                ),
                ("subscriber_ref", models.CharField(blank=True, max_length=64)),
                ("subscriber_key", models.CharField(blank=True, max_length=64)),
                ("operator_name", models.CharField(blank=True, max_length=120)),
                ("status", models.CharField(blank=True, max_length=32)),
                ("status_label", models.CharField(blank=True, max_length=64)),
                ("payment_type", models.CharField(blank=True, max_length=32)),
                ("extra", models.CharField(blank=True, max_length=32)),
                ("comment", models.CharField(blank=True, max_length=255)),
                ("last_seen_at", models.DateTimeField()),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-paid_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["account", "-paid_at"], name="integ_payment_recent_idx"
                    ),
                    models.Index(
                        fields=["account", "subscriber_key", "-paid_at"],
                        name="integ_payment_line_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "reference"),
                        name="integrations_unique_provider_payment",
                    )
                ],
            },
        ),
    ]
