# Generated by Django 5.2.14 on 2026-10-07 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0016_top_ups_leave_the_cash_box"),
    ]

    operations = [
        migrations.AddField(
            model_name="integrationvoucher",
            name="badge",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="country",
            field=models.CharField(blank=True, db_default="", default="", max_length=8),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="face_currency",
            field=models.CharField(blank=True, db_default="", default="", max_length=8),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="is_listed",
            field=models.BooleanField(db_default=True, default=True),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="promo_ends_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="rank",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="integrationvoucher",
            name="regular_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="aliases",
            field=models.JSONField(blank=True, db_default=[], default=list),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="badge",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="category_key",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=64
            ),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="category_name",
            field=models.CharField(
                blank=True, db_default="", default="", max_length=160
            ),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="category_rank",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="featured",
            field=models.BooleanField(db_default=False, default=False),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="rank",
            field=models.IntegerField(db_default=0, default=0),
        ),
        migrations.AddField(
            model_name="integrationvoucherbrand",
            name="redeem_hint",
            field=models.TextField(blank=True, db_default="", default=""),
        ),
        migrations.AlterField(
            model_name="integrationaccount",
            name="provider",
            field=models.CharField(
                choices=[
                    ("hdbox", "hdbox"),
                    ("lnet", "lnet"),
                    ("qareeb", "qareeb"),
                    ("pointy", "pointy"),
                ],
                max_length=32,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="integrationfulfillment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("hdbox", "hdbox"),
                    ("lnet", "lnet"),
                    ("qareeb", "qareeb"),
                    ("pointy", "pointy"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="integrationsubscriber",
            name="provider",
            field=models.CharField(
                choices=[
                    ("hdbox", "hdbox"),
                    ("lnet", "lnet"),
                    ("qareeb", "qareeb"),
                    ("pointy", "pointy"),
                ],
                max_length=32,
            ),
        ),
        migrations.AlterField(
            model_name="providerpayment",
            name="provider",
            field=models.CharField(
                choices=[
                    ("hdbox", "hdbox"),
                    ("lnet", "lnet"),
                    ("qareeb", "qareeb"),
                    ("pointy", "pointy"),
                ],
                max_length=32,
            ),
        ),
        migrations.CreateModel(
            name="IntegrationVoucherCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=120)),
                ("rank", models.IntegerField(default=0)),
                ("flag_path", models.CharField(blank=True, max_length=80)),
                ("flag", models.BinaryField(blank=True, null=True)),
                ("flag_source", models.CharField(blank=True, max_length=80)),
                ("flag_checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="voucher_countries",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "code"),
                        name="integrations_unique_voucher_country",
                    )
                ],
            },
        ),
    ]
