# Generated by Django 5.2.14 on 2026-10-08 01:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    """The mirror of the company's direct top-up and bill-payment directory.

    A new table and nothing else: expand-only, so the previous release (which
    knows nothing of it) keeps serving through a live update.
    """

    dependencies = [
        ("integrations", "0017_voucher_shop"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationServiceCountry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("code", models.CharField(max_length=8)),
                ("name", models.CharField(max_length=120)),
                ("name_en", models.CharField(blank=True, default="", max_length=120)),
                ("dial", models.JSONField(blank=True, default=list)),
                ("currency", models.CharField(blank=True, default="", max_length=8)),
                (
                    "currency_name",
                    models.CharField(blank=True, default="", max_length=120),
                ),
                ("popular", models.IntegerField(default=0)),
                ("rank", models.IntegerField(default=0)),
                ("flag_path", models.CharField(blank=True, max_length=80)),
                ("flag", models.BinaryField(blank=True, null=True)),
                ("flag_source", models.CharField(blank=True, max_length=80)),
                ("flag_checked_at", models.DateTimeField(blank=True, null=True)),
                ("airtime_count", models.PositiveIntegerField(default=0)),
                ("bills_count", models.PositiveIntegerField(default=0)),
                ("bill_types", models.JSONField(blank=True, default=dict)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("version", models.CharField(blank=True, max_length=32)),
                ("synced_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_countries",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["rank", "code"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "code"),
                        name="integrations_unique_service_country",
                    )
                ],
            },
        ),
    ]
