# Generated by Django 5.2.14 on 2026-10-08 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0038_product_tracking_mode_since"),
        ("integrations", "0018_service_countries"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationPriceRule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("default", "default"),
                            ("service", "service"),
                            ("variant", "variant"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "service_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("country", models.CharField(blank=True, default="", max_length=8)),
                (
                    "mode",
                    models.CharField(
                        choices=[("company", "company"), ("custom", "custom")],
                        default="company",
                        max_length=16,
                    ),
                ),
                (
                    "markup_percent",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True),
                ),
                (
                    "price",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
                ),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="price_rules",
                        to="integrations.integrationaccount",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="integration_price_rules",
                        to="catalog.productvariant",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", False)),
                        fields=("account", "variant"),
                        name="integrations_unique_variant_price_rule",
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("variant__isnull", True)),
                        fields=("account", "scope", "service_key", "country"),
                        name="integrations_unique_service_price_rule",
                    ),
                ],
            },
        ),
    ]
