# Generated by Django 5.2.14 on 2026-10-08 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0019_price_rules"),
    ]

    operations = [
        migrations.CreateModel(
            name="IntegrationServiceLogo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("path", models.CharField(max_length=80)),
                ("picture", models.BinaryField(blank=True, null=True)),
                ("checked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_logos",
                        to="integrations.integrationaccount",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("account", "path"),
                        name="integrations_unique_service_logo",
                    )
                ],
            },
        ),
    ]
