# Generated by Django 5.2.14 on 2026-09-05 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("document_type", models.CharField(db_index=True, max_length=32)),
                ("object_id", models.PositiveBigIntegerField(db_index=True)),
                ("document_number", models.CharField(blank=True, max_length=64)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("created", "Created"),
                            ("submitted", "Submitted"),
                            ("edited", "Edited after submit"),
                            ("corrected", "Corrected in place"),
                            ("cancelled", "Cancelled"),
                            ("amended", "Amended"),
                            ("superseded", "Superseded"),
                        ],
                        max_length=16,
                    ),
                ),
                ("reason", models.TextField(blank=True)),
                ("details", models.JSONField(blank=True, default=dict)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="document_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["document_type", "object_id", "-created_at"],
                        name="document_event_doc_idx",
                    )
                ],
            },
        ),
    ]
