# Generated by Django 5.2.14 on 2026-09-16 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("documents", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="DocumentNumberSeries",
            fields=[
                (
                    "key",
                    models.CharField(max_length=64, primary_key=True, serialize=False),
                ),
                ("last_value", models.PositiveBigIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "document number series",
            },
        ),
    ]
