# Generated by Django 5.2.14 on 2026-07-01 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0001_initial"),
        ("customers", "0006_customer_do_not_contact_and_more"),
        ("messaging", "0002_deliveryreceipt_inboundmessage"),
    ]

    operations = [
        migrations.CreateModel(
            name="ConsentEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("opt_out", "Opted out of marketing"),
                            ("opt_in", "Opted in to marketing"),
                            ("do_not_contact", "Do not contact"),
                            ("allow_contact", "Contact allowed"),
                        ],
                        max_length=20,
                    ),
                ),
                ("channel", models.CharField(blank=True, default="sms", max_length=16)),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("sms_command", "SMS command"),
                            ("staff", "Staff"),
                            ("admin_ui", "Admin UI"),
                            ("import", "Import"),
                        ],
                        max_length=16,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="consent_events",
                        to="customers.customer",
                    ),
                ),
                (
                    "inbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="messaging.inboundmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_consent", "Can manage customer contact consent")
                ],
            },
        ),
    ]
