# Generated by Django 5.2.14 on 2026-07-01 03:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0002_consentevent"),
        ("customers", "0006_customer_do_not_contact_and_more"),
        ("discounts", "0008_discount_quantity_promotions"),
        ("messaging", "0002_deliveryreceipt_inboundmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=120)),
                ("body_template", models.TextField()),
                ("channel", models.CharField(default="sms", max_length=16)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending_approval", "Pending approval"),
                            ("approved", "Approved"),
                            ("sending", "Sending"),
                            ("sent", "Sent"),
                            ("cancelled", "Cancelled"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("rfm_segments", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_via",
                    models.CharField(
                        choices=[("human", "Human"), ("ai", "AI")],
                        default="human",
                        max_length=8,
                    ),
                ),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("total_recipients", models.PositiveIntegerField(default=0)),
                ("sent_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("skipped_optout_count", models.PositiveIntegerField(default=0)),
                (
                    "approved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="approved_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customers",
                    models.ManyToManyField(
                        blank=True, related_name="campaigns", to="customers.customer"
                    ),
                ),
                (
                    "discount_rule",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaigns",
                        to="discounts.discountrule",
                    ),
                ),
                (
                    "gateway",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="messaging.messaginggateway",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    ("manage_campaigns", "Can create and edit draft campaigns"),
                    ("send_campaigns", "Can approve and send campaigns"),
                ],
            },
        ),
        migrations.CreateModel(
            name="CampaignRecipient",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(blank=True, max_length=32)),
                ("rendered_body", models.TextField(blank=True)),
                ("segments", models.PositiveSmallIntegerField(default=1)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("skipped_optout", "Skipped (opted out)"),
                            ("queued", "Queued"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="recipients",
                        to="crm.campaign",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="campaign_recipients",
                        to="customers.customer",
                    ),
                ),
                (
                    "outbound",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="campaign_recipients",
                        to="messaging.outboundmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
                "indexes": [
                    models.Index(
                        fields=["campaign", "status"],
                        name="crm_campaig_campaig_213252_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "customer"),
                        name="unique_recipient_per_campaign",
                    )
                ],
            },
        ),
    ]
