# Generated by Django 5.2.14 on 2026-07-01 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("crm", "0003_campaign_campaignrecipient"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffCommandNumber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("phone", models.CharField(max_length=32, unique=True)),
                ("label", models.CharField(blank=True, max_length=120)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["label", "phone"],
            },
        ),
    ]
