# Generated by Django 5.2.14 on 2026-05-19 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer_number",
                    models.CharField(blank=True, max_length=32, unique=True),
                ),
                ("full_name", models.CharField(max_length=255)),
                ("phone", models.CharField(blank=True, max_length=64)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "gender",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("", "Unspecified"),
                            ("female", "Female"),
                            ("male", "Male"),
                            ("non_binary", "Non-binary"),
                            ("prefer_not_to_say", "Prefer not to say"),
                        ],
                        default="",
                        max_length=32,
                    ),
                ),
                ("birthday", models.DateField(blank=True, null=True)),
                ("marketing_consent", models.BooleanField(default=False)),
                ("notes", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "ordering": ["full_name", "customer_number"],
            },
        ),
    ]
