# Generated by Django 6.0.2 on 2026-06-21 15:12

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_alter_asset_created_at_alter_customer_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="is_auto_created",
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name="PaymentCard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=64, unique=True)),
                ("masked_pan", models.CharField(blank=True, max_length=64)),
                ("card_scheme", models.CharField(blank=True, max_length=64)),
                ("aid", models.CharField(blank=True, max_length=64)),
                ("label", models.CharField(blank=True, max_length=120)),
                (
                    "first_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_seen_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("last_receipt_data", models.JSONField(blank=True, default=dict)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="cards",
                        to="customers.customer",
                    ),
                ),
            ],
            options={
                "ordering": ["-last_seen_at", "-id"],
            },
        ),
    ]
