# Generated by Django 5.2.14 on 2026-06-27 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_is_auto_created_paymentcard"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="rfm_calculated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_frequency",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_frequency_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_last_purchase_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_monetary",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_monetary_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_recency_days",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_recency_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_score",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="customer",
            name="rfm_segment",
            field=models.CharField(
                choices=[
                    ("champion", "Champion"),
                    ("loyal", "Loyal"),
                    ("potential_loyalist", "Potential loyalist"),
                    ("new_customer", "New customer"),
                    ("promising", "Promising"),
                    ("needs_attention", "Needs attention"),
                    ("at_risk", "At risk"),
                    ("cant_lose", "Can't lose them"),
                    ("hibernating", "Hibernating"),
                    ("lost", "Lost"),
                    ("inactive", "No purchases"),
                ],
                db_index=True,
                default="inactive",
                max_length=32,
            ),
        ),
    ]
