# Generated by Django 5.2.14 on 2026-07-01 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "customers",
            "0005_customer_rfm_calculated_at_customer_rfm_frequency_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="do_not_contact",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="customer",
            name="marketing_opted_out_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
