# Generated by Django 6.0.2 on 2026-08-29 00:55

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


def open_ownership_for_existing_assets(apps, schema_editor):
    """Give every asset already on file an ownership row.

    Without this the history view would start blank for existing devices and the
    "current owner" row would only appear on an asset's first transfer, making
    the chain look like it began mid-life.
    """
    Asset = apps.get_model("customers", "Asset")
    AssetOwnership = apps.get_model("customers", "AssetOwnership")
    AssetOwnership.objects.bulk_create(
        [
            AssetOwnership(
                asset_id=asset.pk,
                customer_id=asset.customer_id,
                acquired_at=asset.created_at,
            )
            for asset in Asset.objects.all().only("id", "customer_id", "created_at")
        ],
        batch_size=500,
    )


def drop_ownership_rows(apps, schema_editor):
    apps.get_model("customers", "AssetOwnership").objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0006_customer_do_not_contact_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AssetOwnership",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "acquired_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("released_at", models.DateTimeField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200)),
            ],
            options={
                "ordering": ["-acquired_at", "-id"],
            },
        ),
        migrations.AddField(
            model_name="asset",
            name="engine_number",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AddField(
            model_name="asset",
            name="model_year",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="odometer",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="asset",
            name="plate_number",
            field=models.CharField(blank=True, max_length=32),
        ),
        migrations.AddField(
            model_name="asset",
            name="vin",
            field=models.CharField(blank=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="asset",
            name="asset_type",
            field=models.CharField(
                choices=[
                    ("phone", "Phone"),
                    ("tablet", "Tablet"),
                    ("laptop", "Laptop"),
                    ("console", "Game console"),
                    ("appliance", "Appliance"),
                    ("vehicle", "Vehicle"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=24,
            ),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["imei"], name="asset_imei_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["vin"], name="asset_vin_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["plate_number"], name="asset_plate_idx"),
        ),
        migrations.AddIndex(
            model_name="asset",
            index=models.Index(fields=["serial_number"], name="asset_serial_idx"),
        ),
        migrations.AddField(
            model_name="assetownership",
            name="asset",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="ownerships",
                to="customers.asset",
            ),
        ),
        migrations.AddField(
            model_name="assetownership",
            name="customer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="asset_ownerships",
                to="customers.customer",
            ),
        ),
        migrations.AddConstraint(
            model_name="assetownership",
            constraint=models.UniqueConstraint(
                condition=models.Q(("released_at__isnull", True)),
                fields=("asset",),
                name="one_current_owner_per_asset",
            ),
        ),
            migrations.RunPython(
            open_ownership_for_existing_assets,
            drop_ownership_rows,
        ),
    ]
