# Generated by Django 5.2.14 on 2026-09-05 00:22

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0008_asset_type_model"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="credit_limit",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=12,
                null=True,
                validators=[django.core.validators.MinValueValidator(0)],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="credit_limit_policy",
            field=models.CharField(
                choices=[
                    ("shop_default", "Shop default"),
                    ("unlimited", "No limit"),
                    ("custom", "Custom limit"),
                ],
                default="shop_default",
                max_length=16,
            ),
        ),
    ]
