# Generated by Django 6.0.2 on 2026-09-10 03:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0010_alter_customer_credit_limit_policy"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="payment_terms_basis",
            field=models.CharField(
                blank=True,
                choices=[
                    ("net_days", "Days after the invoice"),
                    ("end_of_month", "Days after the end of the invoice month"),
                ],
                db_default="",
                default="",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms_days",
            field=models.PositiveIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MaxValueValidator(730)],
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="payment_terms_policy",
            field=models.CharField(
                choices=[
                    ("shop_default", "Shop default"),
                    ("immediate", "Due immediately"),
                    ("custom", "Custom terms"),
                ],
                db_default="shop_default",
                default="shop_default",
                max_length=16,
            ),
        ),
    ]
