# Generated by Django 5.2.14 on 2026-09-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0011_customer_payment_terms_basis_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="paymentcard",
            name="cardholder_name",
            field=models.CharField(blank=True, max_length=120),
        ),
    ]
