# Generated by Django 5.2.14 on 2026-05-23 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_report__c47a07_idx",
            old_name="reports_rep_report__2f705b_idx",
        ),
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_request_aad8b2_idx",
            old_name="reports_rep_request_5c3b96_idx",
        ),
        migrations.RenameIndex(
            model_name="reportrun",
            new_name="reports_rep_status_eaf0aa_idx",
            old_name="reports_rep_status_52b871_idx",
        ),
    ]
