# Generated by Django 5.2.14 on 2026-06-12 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "reports",
            "0002_rename_reports_rep_report__2f705b_idx_reports_rep_report__c47a07_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="reportrun",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("sales_summary", "Sales summary"),
                    ("payment_methods", "Payment methods"),
                    ("register_closure", "Register closure"),
                    ("inventory_status", "Inventory status"),
                    ("stock_movements", "Stock movements"),
                    ("purchasing_summary", "Purchasing summary"),
                    ("reorder_items", "Reorder items"),
                    ("payroll_summary", "Payroll summary"),
                    ("profit_costs", "Profit and costs"),
                ],
                max_length=48,
            ),
        ),
    ]
