# Generated by Django 6.0.2 on 2026-09-01 17:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0004_alter_reportrun_created_at"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reportrun",
            options={
                "ordering": ["-created_at", "-id"],
                "permissions": [
                    (
                        "manage_period_lock",
                        "Can close and re-open an accounting period",
                    ),
                    (
                        "override_period_lock",
                        "Can post into a closed accounting period",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="reportrun",
            name="figures_checksum",
            field=models.CharField(blank=True, db_index=True, max_length=64),
        ),
        migrations.AlterField(
            model_name="reportrun",
            name="report_type",
            field=models.CharField(
                choices=[
                    ("sales_summary", "Sales summary"),
                    ("payment_methods", "Payment methods"),
                    ("register_closure", "Register closure"),
                    ("inventory_status", "Inventory status"),
                    ("stock_movements", "Stock movements"),
                    ("purchasing_summary", "Purchasing summary"),
                    ("reorder_items", "Reorder items"),
                    ("payroll_summary", "Payroll summary"),
                    ("profit_costs", "Profit and costs"),
                    ("receivables_aging", "Receivables aging"),
                    ("payables_aging", "Payables aging"),
                    ("customer_statement", "Customer statement"),
                    ("supplier_statement", "Supplier statement"),
                    ("cash_position", "Cash and bank position"),
                    ("expense_breakdown", "Expenses by category"),
                    ("product_margin", "Gross margin by product"),
                    ("discount_audit", "Discounts, voids and returns"),
                    ("sales_by_staff", "Sales by staff and hour"),
                    ("month_end_pack", "Month-end pack"),
                ],
                max_length=48,
            ),
        ),
        migrations.AddIndex(
            model_name="reportrun",
            index=models.Index(
                fields=["report_type", "figures_checksum"],
                name="reports_type_figures_idx",
            ),
        ),
    ]
