# Generated by Django 6.0.2 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0003_payment_card_receipt_data"),
        ("sales", "0020_alter_order_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AddIndex(
            model_name="payment",
            index=models.Index(
                fields=["method", "-created_at"], name="payments_method_created_idx"
            ),
        ),
    ]
