# Generated by Django 6.0.2 on 2026-06-21 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customer_is_auto_created_paymentcard"),
        ("payments", "0004_alter_payment_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="card",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="payments",
                to="customers.paymentcard",
            ),
        ),
    ]
