# Generated by Django 5.2.14 on 2026-09-23 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0012_seed_card_terminals"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="method",
            field=models.CharField(
                choices=[
                    ("cash", "Cash"),
                    ("card", "Card"),
                    ("transfer", "Transfer"),
                    ("salary_deduction", "Salary deduction"),
                ],
                max_length=16,
            ),
        ),
    ]
