# Generated by Django 5.2.14 on 2026-09-25 22:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0013_payment_method_salary_deduction"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="reverses",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reversals",
                to="payments.payment",
            ),
        ),
    ]
