# collect-diagnostics.ps1: the tool a technician carries to a shop whose
# server will not stay up. It gets one chance on site, so what can be proven
# away from Windows is proven here: it parses, the two scripts it writes out
# parse, the probe always writes its row, and no credential survives the mask.
$ErrorActionPreference = "Stop"
$pass = 0; $fail = 0
function check([string]$what, [scriptblock]$body) {
    try { $r = & $body; if ($r) { $script:pass++; Write-Host "ok   $what" -ForegroundColor Green }
          else { $script:fail++; Write-Host "FAIL $what" -ForegroundColor Red } }
    catch { $script:fail++; Write-Host "FAIL $what -- $($_.Exception.Message)" -ForegroundColor Red }
}

Write-Host "# collect-diagnostics.ps1"

$collector = (Resolve-Path (Join-Path $PSScriptRoot ".." "collect-diagnostics.ps1")).Path
$errs = $null; $toks = $null
$ast = [System.Management.Automation.Language.Parser]::ParseFile($collector, [ref]$toks, [ref]$errs)
check "the collector parses" { $errs.Count -eq 0 }

# The two here-strings it writes to disk, exactly as it will write them.
function Get-Assigned([string]$Name) {
    $node = $ast.Find({ param($n) $n -is [System.Management.Automation.Language.AssignmentStatementAst] -and
        "$($n.Left)" -eq "`$$Name" }, $false)
    return $node.Right.Expression.Value
}
$guestSource = Get-Assigned "GuestSource"
$probeSource = Get-Assigned "ProbeSource"
$tmp = Join-Path ([IO.Path]::GetTempPath()) ("pointy-diag-test-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null
$guestFile = Join-Path $tmp "linux-collect.sh"
$probeFile = Join-Path $tmp "pointy-probe.ps1"
[IO.File]::WriteAllText($guestFile, ($guestSource -replace "`r`n", "`n"))
[IO.File]::WriteAllText($probeFile, $probeSource)

check "the probe it installs parses" {
    $perrs = $null; $ptoks = $null
    [System.Management.Automation.Language.Parser]::ParseFile($probeFile, [ref]$ptoks, [ref]$perrs) | Out-Null
    $perrs.Count -eq 0
}
check "the Linux half is valid bash" {
    & bash -n $guestFile 2>&1 | Out-Null
    $LASTEXITCODE -eq 0
}

# Nothing Windows-only works here, which is the point: every lookup fails, and
# the probe must still write a complete row. A probe that dies on the one
# minute something is odd records nothing about that minute.
check "the probe writes a full row even when every lookup fails" {
    $csv = Join-Path $tmp "probe.csv"
    & (Get-Process -Id $PID).Path -NoProfile -File $probeFile -LogFile $csv *> $null
    $rows = @(Import-Csv $csv)
    ($rows.Count -eq 1) -and (@($rows[0].PSObject.Properties).Count -eq 16) -and
        ($rows[0].distro -eq "unknown") -and ([datetime]::Parse($rows[0].time) -gt (Get-Date).AddMinutes(-5))
}

# The functions, lifted without running the collector (see lib.ps1).
foreach ($fn in $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false)) {
    Invoke-Expression $fn.Extent.Text
}
check "task results name what happened" {
    ((Format-TaskResult ([uint32]0x41301)) -like "*running right now*") -and
    ((Format-TaskResult ([uint32]2147946720)) -like "0x800710E0 (refused*") -and
    ((Format-TaskResult ([uint32]0xABC)) -eq "0xABC")
}
check "the distro owner matches with or without the machine name" {
    (Test-SameAccount "SHOP-PC\POS" "POS") -and (Test-SameAccount "shop-pc\pos" "SHOP-PC\POS") -and
        -not (Test-SameAccount "SHOP-PC\POS" "SHOP-PC\Admin") -and -not (Test-SameAccount "" "POS")
}
# WSL powers a distro off ~15 s after its last Windows-side client exits; the
# supervisor's keep-alive client is what prevents that, and on WSL 2.5.4+
# [general] instanceIdleTimeout=-1 is the fallback. Reading the key from the
# wrong section would report a shop as covered when it is not.
check "reads a .wslconfig key only from its own section" {
    $generated = "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem.`n[wsl2]`nmemory=4GB`nvmIdleTimeout=-1`nsparseVhd=true`n"
    ($null -eq (Get-WslConfigValue $generated "general" "instanceIdleTimeout")) -and
    ((Get-WslConfigValue ($generated + "[general]`ninstanceIdleTimeout=-1`n") "general" "instanceIdleTimeout") -eq "-1") -and
    ($null -eq (Get-WslConfigValue "[wsl2]`ninstanceIdleTimeout=-1`n" "general" "instanceIdleTimeout")) -and
    ((Get-WslConfigValue $generated "wsl2" "sparseVhd") -eq "true") -and
    ((Get-WslConfigValue "[General]`r`nInstanceIdleTimeout = -1  # a server`r`n" "general" "instanceIdleTimeout") -eq "-1")
}
check "the keep-alive client is told apart from every other wsl.exe" {
    (Test-AnchorCommandLine 'wsl.exe -d Pointy -u root --exec /bin/sleep infinity' "Pointy") -and
    (Test-AnchorCommandLine '"C:\Program Files\WSL\wsl.exe" -d Pointy -u root --exec /bin/sleep infinity' "Pointy") -and
    -not (Test-AnchorCommandLine 'wsl.exe -d Pointy -u root -- bash -lc true' "Pointy") -and
    -not (Test-AnchorCommandLine 'wsl.exe -d Pointy2 -u root --exec /bin/sleep infinity' "Pointy") -and
    -not (Test-AnchorCommandLine 'wsl.exe -d Ubuntu --exec /bin/sleep infinity' "Pointy") -and
    -not (Test-AnchorCommandLine '' "Pointy")
}
check "Windows paths map to their /mnt form" {
    (ConvertTo-WslPath "C:\ProgramData\Pointy\diagnostics\x\linux") -eq "/mnt/c/ProgramData/Pointy/diagnostics/x/linux"
}

# The zip leaves the shop, often over WhatsApp. Its masking is sed with GNU
# extensions, which is what the distro runs; macOS's BSD sed cannot run it.
& bash -c "sed --version" *> $null
if ($LASTEXITCODE -ne 0) {
    Write-Host "skip credential masking (needs GNU sed; CI has it)" -ForegroundColor Yellow
} else {
    $envFile = Join-Path $tmp "env"
    $logFile = Join-Path $tmp "log"
    [IO.File]::WriteAllText($envFile, (@(
        "# a comment",
        "POINTY_BACKEND_PORT=8000",
        "POINTY_POSTGRES_PASSWORD=pw-one-4f9a",
        "POINTY_DATABASE_URL=postgres://pointy:pw-one-4f9a@pgbouncer:5432/pointy",
        "POINTY_RELAY_URL=https://relay.example/v1?api_key=key-two-77b1&region=ly",
        "DJANGO_SECRET_KEY=secret-three-0c2d",
        "POINTY_RELAY_ENROLLMENT_TOKEN=token-four-e81f",
        "POINTY_RELAY_SERPER_API_KEY=key-five-19aa",
        "POINTY_BACKEND_MEM_LIMIT=2g"
    ) -join "`n") + "`n")
    [IO.File]::WriteAllText($logFile, (@(
        "connecting to postgres://pointy:pw-one-4f9a@pgbouncer:5432/pointy",
        '{"password": "pw-six-5d5d", "user": "pos"}',
        "X-Pointy-Connector-Token: token-seven-3b3b",
        "Authorization: Bearer token-eight-a1a1a1a1",
        "token refresh failed after 3 retries"
    ) -join "`n") + "`n")
    $driver = Join-Path $tmp "driver.sh"
    [IO.File]::WriteAllText($driver, (@(
        'eval "$(sed -n ''/^redact() {/,/^}/p; /^redact_env() {/,/^}/p'' "$1")"',
        'redact_env < "$2"',
        'redact < "$3"'
    ) -join "`n") + "`n")
    $masked = (& bash $driver $guestFile $envFile $logFile) -join "`n"
    $secrets = @("pw-one-4f9a", "key-two-77b1", "secret-three-0c2d", "token-four-e81f", "key-five-19aa",
                 "pw-six-5d5d", "token-seven-3b3b", "token-eight-a1a1a1a1")
    check "no credential survives the mask" {
        @($secrets | Where-Object { $masked -like "*$_*" }).Count -eq 0
    }
    check "what a diagnosis needs does survive it" {
        ($masked -like "*@pgbouncer:5432/pointy*") -and ($masked -like "*POINTY_BACKEND_MEM_LIMIT=2g*") -and
            ($masked -like "*region=ly*") -and ($masked -like "*token refresh failed after 3 retries*")
    }
}
Remove-Item -Recurse -Force $tmp -ErrorAction SilentlyContinue

Write-Host ""
if ($fail -gt 0) { Write-Host "# diagnostics: $pass passed, $fail failed" -ForegroundColor Red; exit 1 }
Write-Host "# diagnostics: $pass passed, 0 failed" -ForegroundColor Green
