# Tests for keep-pointy-running.ps1, the signed-in-session keeper for shops
# still on WSL: its .wslconfig edits, the quoting wsl.exe --exec relies on, and
# that its keep-alive client is never mistaken for (or killed as) the PointyWSL
# supervisor's. Also refuses syntax Windows PowerShell 5.1 cannot run.
#
#   pwsh deploy/onprem/wsl/tests/keeper.ps1   (run-tests.ps1 includes it)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
# Keeper functions lifted out by AST, like lib.ps1 does for bootstrap-wsl.ps1: dot-sourcing
# would run the entry point, which on a Mac means trying to drive WSL.
$path = (Resolve-Path (Join-Path $PSScriptRoot ".." "keep-pointy-running.ps1")).Path
$src  = Get-Content -Raw $path
$errs = $null; $toks = $null
$ast  = [System.Management.Automation.Language.Parser]::ParseInput($src, [ref]$toks, [ref]$errs)
if ($errs -and $errs.Count) { $errs | ForEach-Object { Write-Host "PARSE ERROR line $($_.Extent.StartLineNumber): $($_.Message)" }; exit 1 }
Write-Host "# keep-pointy-running.ps1"

# PowerShell 5.1-incompatible syntax: ternary, ??, &&/|| pipeline chains, ?. operators
$bad = @()
foreach ($t in $toks) {
    if ($t.Kind -in @('QuestionQuestion','QuestionQuestionEquals','QuestionDot','QuestionLBracket','AndAnd','OrOr')) { $bad += "line $($t.Extent.StartLineNumber): $($t.Kind)" }
    if ($t.Kind -eq 'QuestionMark') { $bad += "line $($t.Extent.StartLineNumber): ternary?" }
}
if ($bad.Count) { $bad | ForEach-Object { Write-Host "PS7-ONLY: $_" }; exit 1 }


foreach ($fn in $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false)) {
    Invoke-Expression $fn.Extent.Text
}
$Distro = "Pointy"; $AnchorSleep = "2147483647"; $InstallRoot = "/tmp/x"; $LogDir = "/tmp/x/logs"; $LogFile = "/tmp/x/logs/k.log"
function Write-Log { param([string]$Message, [string]$Level = "INFO") }

$pass = 0; $fail = 0
function Check { param([string]$Name, $Actual, $Expected)
    if ("$Actual" -ceq "$Expected") { $script:pass++ } else { $script:fail++; Write-Host "FAIL $Name`n  expected: [$Expected]`n  actual:   [$Actual]" } }

$tmp = Join-Path ([IO.Path]::GetTempPath()) ("kp-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null
$cfg = Join-Path $tmp ".wslconfig"

# 1. v0.6.9's generated file: keys moved, forwarding kept false, nothing else touched.
$gen = "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem.`n[wsl2]`nmemory=8GB`nprocessors=4`nswap=2GB`n# comment`nlocalhostForwarding=false`nguiApplications=false`nnestedVirtualization=false`nvmIdleTimeout=-1`n[experimental]`nsparseVhd=true`nautoMemoryReclaim=gradual`n"
[IO.File]::WriteAllText($cfg, $gen)
Check "v069 changed" (Update-WslConfig -Path $cfg) $true
Check "v069 content" ([IO.File]::ReadAllText($cfg)) "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem.`n[wsl2]`nmemory=8GB`nprocessors=4`nswap=2GB`n# comment`nlocalhostForwarding=false`nguiApplications=false`nnestedVirtualization=false`nvmIdleTimeout=-1`n[experimental]`n"
Check "v069 idempotent" (Update-WslConfig -Path $cfg) $false

# 2. an older generated file: keys under [wsl2], forwarding on, CRLF.
[IO.File]::WriteAllText($cfg, "[wsl2]`r`nmemory=4GB`r`nlocalhostForwarding = true`r`nsparseVhd=true`r`nautoMemoryReclaim=gradual`r`n")
Check "old changed" (Update-WslConfig -Path $cfg) $true
Check "old content" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nmemory=4GB`nlocalhostForwarding=false`n"

# 3. no [wsl2] section at all, another section present.
[IO.File]::WriteAllText($cfg, "[general]`ninstanceIdleTimeout=-1`n")
Check "nowsl2 changed" (Update-WslConfig -Path $cfg) $true
Check "nowsl2 content" ([IO.File]::ReadAllText($cfg)) "[general]`ninstanceIdleTimeout=-1`n[wsl2]`nlocalhostForwarding=false`n"

# 4. [wsl2] present without the key, followed by another section: key lands inside [wsl2].
[IO.File]::WriteAllText($cfg, "[wsl2]`nmemory=6GB`n[general]`ninstanceIdleTimeout=-1`n")
Update-WslConfig -Path $cfg | Out-Null
Check "insert-before-next" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nmemory=6GB`nlocalhostForwarding=false`n[general]`ninstanceIdleTimeout=-1`n"

# 5. no file at all.
Remove-Item -Force $cfg
Check "nofile changed" (Update-WslConfig -Path $cfg) $true
Check "nofile content" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nlocalhostForwarding=false`n"
$bytes = [IO.File]::ReadAllBytes($cfg)
Check "no BOM" ($bytes[0] -ne 0xEF) $true

# 6. duplicate forwarding keys collapse to one.
[IO.File]::WriteAllText($cfg, "[wsl2]`nlocalhostForwarding=true`nlocalhostForwarding=true`n")
Update-WslConfig -Path $cfg | Out-Null
Check "dupe" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nlocalhostForwarding=false`n"

# ConvertTo-WslPath (Windows-only semantics of GetFullPath; test the string math on already-full paths)
function ConvertTo-WslPathPure { param([string]$full) $full = $full.TrimEnd('\'); return "/mnt/" + $full.Substring(0, 1).ToLowerInvariant() + ($full.Substring(2) -replace '\\', '/') }
Check "wslpath root" (ConvertTo-WslPathPure "D:\") "/mnt/d"
Check "wslpath dir" (ConvertTo-WslPathPure "E:\Pointy Move\x") "/mnt/e/Pointy Move/x"

# Quoting as CommandLineToArgvW expects
Check "arg plain" (ConvertTo-NativeArgument "abc") "abc"
Check "arg space" (ConvertTo-NativeArgument "/mnt/d/Pointy Move") '"/mnt/d/Pointy Move"'
Check "arg bash" (ConvertTo-NativeArgument "cd '/opt/pointy' && x") '"cd ''/opt/pointy'' && x"'
Check "arg quote" (ConvertTo-NativeArgument 'a"b') '"a\"b"'
Check "arg trailing backslash" (ConvertTo-NativeArgument 'C:\a b\') '"C:\a b\\"'

# Anchor command line matches Find-Anchor's pattern and NOT the old supervisor's
$line = "`"C:\Program Files\WSL\wsl.exe`" " + ((Get-AnchorArguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
Check "anchor -d" ($line -match "(^|\s)-d\s+$([regex]::Escape($Distro))(\s|$)") $true
Check "anchor ours" ($line -like "*--exec /bin/sleep ${AnchorSleep}*") $true
Check "anchor not v069" ($line -like "*--exec /bin/sleep infinity*") $false

# Arabic title
Check "arabic" (ConvertFrom-CodePoint @(0x62F,0x641,0x62A,0x631)) ([string]::new([char[]]@([char]0x62F,[char]0x641,[char]0x62A,[char]0x631)))

Remove-Item -Recurse -Force $tmp
Write-Host ("# keeper: {0} passed, {1} failed" -f $pass, $fail)
if ($fail) { exit 1 }
