# Tests for keep-pointy-running.ps1, the signed-in-session keeper for shops
# still on WSL: its .wslconfig edits, the quoting wsl.exe --exec relies on, and
# that its keep-alive client is never mistaken for (or killed as) the PointyWSL
# supervisor's. Also refuses syntax Windows PowerShell 5.1 cannot run.
#
#   pwsh deploy/onprem/wsl/tests/keeper.ps1   (run-tests.ps1 includes it)
$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest
# Keeper functions lifted out by AST, like lib.ps1 does for bootstrap-wsl.ps1: dot-sourcing
# would run the entry point, which on a Mac means trying to drive WSL.
$path = (Resolve-Path (Join-Path $PSScriptRoot ".." "keep-pointy-running.ps1")).Path
$src  = Get-Content -Raw $path
$errs = $null; $toks = $null
$ast  = [System.Management.Automation.Language.Parser]::ParseInput($src, [ref]$toks, [ref]$errs)
if ($errs -and $errs.Count) { $errs | ForEach-Object { Write-Host "PARSE ERROR line $($_.Extent.StartLineNumber): $($_.Message)" }; exit 1 }
Write-Host "# keep-pointy-running.ps1"

# PowerShell 5.1-incompatible syntax: ternary, ??, &&/|| pipeline chains, ?. operators
$bad = @()
foreach ($t in $toks) {
    if ($t.Kind -in @('QuestionQuestion','QuestionQuestionEquals','QuestionDot','QuestionLBracket','AndAnd','OrOr')) { $bad += "line $($t.Extent.StartLineNumber): $($t.Kind)" }
    if ($t.Kind -eq 'QuestionMark') { $bad += "line $($t.Extent.StartLineNumber): ternary?" }
}
if ($bad.Count) { $bad | ForEach-Object { Write-Host "PS7-ONLY: $_" }; exit 1 }


foreach ($fn in $ast.FindAll({ param($n) $n -is [System.Management.Automation.Language.FunctionDefinitionAst] }, $false)) {
    Invoke-Expression $fn.Extent.Text
}
$Distro = "Pointy"; $AnchorSleep = "2147483647"; $InstallRoot = "/tmp/x"; $LogDir = "/tmp/x/logs"; $LogFile = "/tmp/x/logs/k.log"
function Write-Log { param([string]$Message, [string]$Level = "INFO") }

$pass = 0; $fail = 0
function Check { param([string]$Name, $Actual, $Expected)
    if ("$Actual" -ceq "$Expected") { $script:pass++ } else { $script:fail++; Write-Host "FAIL $Name`n  expected: [$Expected]`n  actual:   [$Actual]" } }

$tmp = Join-Path ([IO.Path]::GetTempPath()) ("kp-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tmp | Out-Null
$cfg = Join-Path $tmp ".wslconfig"

# 1. v0.6.9's generated file: keys moved, forwarding kept false, nothing else touched.
$gen = "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem.`n[wsl2]`nmemory=8GB`nprocessors=4`nswap=2GB`n# comment`nlocalhostForwarding=false`nguiApplications=false`nnestedVirtualization=false`nvmIdleTimeout=-1`n[experimental]`nsparseVhd=true`nautoMemoryReclaim=gradual`n"
[IO.File]::WriteAllText($cfg, $gen)
Check "v069 changed" (Update-WslConfig -Path $cfg) $true
Check "v069 content" ([IO.File]::ReadAllText($cfg)) "# GENERATED by bootstrap-wsl.ps1 - Pointy on-prem.`n[wsl2]`nmemory=8GB`nprocessors=4`nswap=2GB`n# comment`nlocalhostForwarding=false`nguiApplications=false`nnestedVirtualization=false`nvmIdleTimeout=-1`n[experimental]`n"
Check "v069 idempotent" (Update-WslConfig -Path $cfg) $false

# 2. an older generated file: keys under [wsl2], forwarding on, CRLF.
[IO.File]::WriteAllText($cfg, "[wsl2]`r`nmemory=4GB`r`nlocalhostForwarding = true`r`nsparseVhd=true`r`nautoMemoryReclaim=gradual`r`n")
Check "old changed" (Update-WslConfig -Path $cfg) $true
Check "old content" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nmemory=4GB`nlocalhostForwarding=false`n"

# 3. no [wsl2] section at all, another section present.
[IO.File]::WriteAllText($cfg, "[general]`ninstanceIdleTimeout=-1`n")
Check "nowsl2 changed" (Update-WslConfig -Path $cfg) $true
Check "nowsl2 content" ([IO.File]::ReadAllText($cfg)) "[general]`ninstanceIdleTimeout=-1`n[wsl2]`nlocalhostForwarding=false`n"

# 4. [wsl2] present without the key, followed by another section: key lands inside [wsl2].
[IO.File]::WriteAllText($cfg, "[wsl2]`nmemory=6GB`n[general]`ninstanceIdleTimeout=-1`n")
Update-WslConfig -Path $cfg | Out-Null
Check "insert-before-next" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nmemory=6GB`nlocalhostForwarding=false`n[general]`ninstanceIdleTimeout=-1`n"

# 5. no file at all.
Remove-Item -Force $cfg
Check "nofile changed" (Update-WslConfig -Path $cfg) $true
Check "nofile content" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nlocalhostForwarding=false`n"
$bytes = [IO.File]::ReadAllBytes($cfg)
Check "no BOM" ($bytes[0] -ne 0xEF) $true

# 6. duplicate forwarding keys collapse to one.
[IO.File]::WriteAllText($cfg, "[wsl2]`nlocalhostForwarding=true`nlocalhostForwarding=true`n")
Update-WslConfig -Path $cfg | Out-Null
Check "dupe" ([IO.File]::ReadAllText($cfg)) "[wsl2]`nlocalhostForwarding=false`n"

# ConvertTo-WslPath (Windows-only semantics of GetFullPath; test the string math on already-full paths)
function ConvertTo-WslPathPure { param([string]$full) $full = $full.TrimEnd('\'); return "/mnt/" + $full.Substring(0, 1).ToLowerInvariant() + ($full.Substring(2) -replace '\\', '/') }
Check "wslpath root" (ConvertTo-WslPathPure "D:\") "/mnt/d"
Check "wslpath dir" (ConvertTo-WslPathPure "E:\Pointy Move\x") "/mnt/e/Pointy Move/x"

# Quoting as CommandLineToArgvW expects
Check "arg plain" (ConvertTo-NativeArgument "abc") "abc"
Check "arg space" (ConvertTo-NativeArgument "/mnt/d/Pointy Move") '"/mnt/d/Pointy Move"'
Check "arg bash" (ConvertTo-NativeArgument "cd '/opt/pointy' && x") '"cd ''/opt/pointy'' && x"'
Check "arg quote" (ConvertTo-NativeArgument 'a"b') '"a\"b"'
Check "arg trailing backslash" (ConvertTo-NativeArgument 'C:\a b\') '"C:\a b\\"'

# Anchor command line matches Find-Anchor's pattern and NOT the old supervisor's
$line = "`"C:\Program Files\WSL\wsl.exe`" " + ((Get-AnchorArguments | ForEach-Object { ConvertTo-NativeArgument $_ }) -join " ")
Check "anchor -d" ($line -match "(^|\s)-d\s+$([regex]::Escape($Distro))(\s|$)") $true
Check "anchor ours" ($line -like "*--exec /bin/sleep ${AnchorSleep}*") $true
Check "anchor not v069" ($line -like "*--exec /bin/sleep infinity*") $false

# Arabic title
Check "arabic" (ConvertFrom-CodePoint @(0x62F,0x641,0x62A,0x631)) ([string]::new([char[]]@([char]0x62F,[char]0x641,[char]0x62A,[char]0x631)))

# FTP upload setups: the keeper forwards the DVRs' ports with the tills', read
# from the stack's .env the same way bootstrap-wsl.ps1 does (bridge.ps1 tests
# that reading in depth).
$GuestDir = "/opt/pointy"; $ApiPort = 8000; $WebPort = 80
$ftp = ConvertFrom-FtpEnv -Text ""
Check "ftp default port" $ftp.Port 21
Check "ftp default data ports" ("{0} {1} {2} {3}" -f $ftp.Passive[0], $ftp.Passive[-1], @($ftp.Passive).Count, $ftp.Range) "30000 30019 20 30000-30019"
$ftp = ConvertFrom-FtpEnv -Text "POINTY_FTP_PUBLIC_PORT=2121`r`nPOINTY_FTP_PASSIVE_PORTS=`"31000-31004`" # off IIS`r`n"
Check "ftp moved" ("{0} {1}" -f $ftp.Port, $ftp.Range) "2121 31000-31004"
Check "ftp too wide" ($null -eq (ConvertFrom-FtpEnv -Text "POINTY_FTP_PASSIVE_PORTS=30000-40000")) $true

$script:Forwarded = [System.Collections.ArrayList]::new()
$script:Rules = [System.Collections.ArrayList]::new()
$script:GuestCommand = ""
function Enable-IpHelper { }
function Set-PortProxy { param([int]$Port, [string]$Target, [switch]$Force) [void]$script:Forwarded.Add("${Port}>${Target}") }
function Add-FirewallRule { param([string]$Name, [string]$Port, [string[]]$RemoteAddress = @())
    [void]$script:Rules.Add("${Name}|${Port}|$($RemoteAddress -join ',')") }
function Invoke-Guest { param([string]$Command, [int]$TimeoutSec = 120)
    $script:GuestCommand = $Command
    return [pscustomobject]@{ ExitCode = 1; Output = "" } }
Update-LanBridge -WslIp "172.28.150.9"
$expected = @("8000>172.28.150.9", "80>172.28.150.9", "21>172.28.150.9") + @(30000..30019 | ForEach-Object { "${_}>172.28.150.9" })
Check "keeper forwards the tills' and the DVRs' ports" ($script:Forwarded -join ",") ($expected -join ",")
Check "keeper reads the .env with one plain grep" $script:GuestCommand "grep '^POINTY_FTP_' '/opt/pointy/.env'"
Check "keeper opens FTP to private addresses only" (@($script:Rules | Where-Object {
    $_ -like "Pointy FTP (TCP 21)|21|*192.168.0.0/16*" -or $_ -like "Pointy FTP data (TCP 30000-30019)|30000-30019|*10.0.0.0/8*" }).Count) 2
Check "keeper leaves the tills' rules open to all" (@($script:Rules | Where-Object { $_ -eq "Pointy API (TCP 8000)|8000|" }).Count) 1

# --- updates: the release's Windows-side files, copied out of the distro -----
# The real list, lifted from the script, so what is tested is what ships.
Invoke-Expression ($ast.Find({ param($n) $n -is [System.Management.Automation.Language.AssignmentStatementAst] -and
    "$($n.Left)" -eq '$PromotedFiles' }, $false)).Extent.Text
Check "promotes the keeper itself" ($PromotedFiles["wsl/keep-pointy-running.ps1"]) "keep-pointy-running.ps1"
Check "promotes the bootstrap, the collector and the mover" (@($PromotedFiles.Values) -join ",") `
    "keep-pointy-running.ps1,bootstrap-wsl.ps1,collect-diagnostics.ps1,timezone-map.txt,move-server.sh"

$InstallRoot = Join-Path $tmp "ProgramData-Pointy"
New-Item -ItemType Directory -Path $InstallRoot | Out-Null
$script:RefusedHashes = @{}
$script:Logged = [System.Collections.ArrayList]::new()
function Write-Log { param([string]$Message, [string]$Level = "INFO") [void]$script:Logged.Add("${Level}: ${Message}") }
function logged([string]$needle) { return [bool]($script:Logged | Where-Object { $_ -like "*$needle*" }) }
function sha256([byte[]]$Bytes) {
    $sha = [System.Security.Cryptography.SHA256]::Create()
    try { return (-join ($sha.ComputeHash($Bytes) | ForEach-Object { $_.ToString("x2") })) } finally { $sha.Dispose() } }
function bytes([string]$Text) { return ,([Text.Encoding]::UTF8.GetBytes($Text)) }

# The distro as the fake wsl.exe sees it: files under /opt/pointy, a path whose
# read fails, and a path sha256sum reports the wrong hash for.
$script:GuestFiles = @{}
$script:BrokenReads = @{}
$script:LyingHashes = @{}
function Invoke-Guest { param([string]$Command, [int]$TimeoutSec = 120)
    if ($Command -like "cd '/opt/pointy' && sha256sum *") {
        $lines = @(foreach ($p in $script:GuestFiles.Keys) {
            $h = $script:LyingHashes[$p]
            if (-not $h) { $h = sha256 $script:GuestFiles[$p] }
            "$h  $p" })
        # sha256sum exits 1 when any listed file is missing; the lines still count.
        return [pscustomobject]@{ ExitCode = 1; Output = ($lines -join "`n") } }
    if ($Command -match "^base64 -w0 '/opt/pointy/(.+)'$") {
        $p = $Matches[1]
        if ($script:BrokenReads.ContainsKey($p) -or -not $script:GuestFiles.ContainsKey($p)) {
            return [pscustomobject]@{ ExitCode = 1; Output = "" } }
        return [pscustomobject]@{ ExitCode = 0; Output = [Convert]::ToBase64String($script:GuestFiles[$p]) } }
    return [pscustomobject]@{ ExitCode = 1; Output = "" } }

$keeperV2 = bytes "# keeper v2`r`nWrite-Host 'v2'`r`n"
$script:GuestFiles["wsl/keep-pointy-running.ps1"] = $keeperV2
$script:GuestFiles["wsl/timezone-map.txt"] = bytes "Libya Standard Time=Africa/Tripoli`n"
$script:GuestFiles["move-server.sh"] = bytes "#!/usr/bin/env bash`necho move`n"
Update-FromGuest
$local = Join-Path $InstallRoot "keep-pointy-running.ps1"
Check "copies out the release's keeper, byte for byte (CRLF kept)" (sha256 ([IO.File]::ReadAllBytes($local))) (sha256 $keeperV2)
Check "copies out the other files the release carries" ((Test-Path (Join-Path $InstallRoot "timezone-map.txt")) -and
    (Test-Path (Join-Path $InstallRoot "move-server.sh"))) $true
Check "leaves what the release lacks alone" (Test-Path (Join-Path $InstallRoot "bootstrap-wsl.ps1")) $false
Check "leaves no staged copies behind" (@(Get-ChildItem $InstallRoot -Filter "*.new").Count) 0

$script:Logged.Clear()
Update-FromGuest
Check "an identical file is not copied again" (logged "updated") $false

# A keeper that does not parse would leave nothing to start WSL: refused, once.
$script:GuestFiles["wsl/keep-pointy-running.ps1"] = bytes "function Broken {`n"
$script:Logged.Clear()
Update-FromGuest
Check "a keeper that does not parse is refused" (logged "refused (it does not parse)") $true
Check "and the running one is kept" (sha256 ([IO.File]::ReadAllBytes($local))) (sha256 $keeperV2)
$script:Logged.Clear()
Update-FromGuest
Check "a refused copy is logged once, not every round" (logged "refused") $false

# A copy that does not match what sha256sum said is refused too.
$script:LyingHashes["wsl/timezone-map.txt"] = ("0" * 64)
$script:GuestFiles["wsl/timezone-map.txt"] = bytes "changed`n"
$script:Logged.Clear()
Update-FromGuest
Check "a copy that does not match the distro's hash is refused" (logged "does not match the distro's") $true

# WSL being busy is not a verdict on the file: the next round tries again.
$script:GuestFiles["wsl/collect-diagnostics.ps1"] = bytes "Write-Host 'collector'`n"
$script:BrokenReads["wsl/collect-diagnostics.ps1"] = $true
Update-FromGuest
$collector = Join-Path $InstallRoot "collect-diagnostics.ps1"
$firstTry = Test-Path $collector
$script:BrokenReads.Clear()
Update-FromGuest
Check "a failed read is retried next round" ("{0} {1}" -f $firstTry, (Test-Path $collector)) "False True"

Check "sha256sum lines parse in text and binary mode" (& {
    function Invoke-Guest { param([string]$Command, [int]$TimeoutSec = 120)
        return [pscustomobject]@{ ExitCode = 0; Output = ("{0}  wsl/bootstrap-wsl.ps1`r`n{1} *move-server.sh`nsha256sum: x: No such file" -f ("a" * 64), ("b" * 64)) } }
    $h = Get-GuestFileHashes
    "{0} {1} {2}" -f $h["wsl/bootstrap-wsl.ps1"].Substring(0, 3), $h["move-server.sh"].Substring(0, 3), $h.Count
}) "aaa bbb 2"

# Handing over: only to a different keeper that parses, and only by the
# installed copy (a run from elsewhere started with no hash).
$StableScript = $local
[IO.File]::WriteAllText($StableScript, "Write-Host 'one'`n")
$startedHash = Get-FileSha256 $StableScript
Check "no handover while the file is unchanged" (Test-KeeperReplaced -StartedHash $startedHash) $false
Check "no handover by a copy run from elsewhere" (Test-KeeperReplaced -StartedHash "") $false
[IO.File]::WriteAllText($StableScript, "Write-Host 'two'`n")
Check "a newer keeper at its path takes over" (Test-KeeperReplaced -StartedHash $startedHash) $true
[IO.File]::WriteAllText($StableScript, "function Broken {`n")
Check "never to one that does not parse" (Test-KeeperReplaced -StartedHash $startedHash) $false
Remove-Item $StableScript
Check "nor to a missing one" (Test-KeeperReplaced -StartedHash $startedHash) $false

Remove-Item -Recurse -Force $tmp
Write-Host ("# keeper: {0} passed, {1} failed" -f $pass, $fail)
if ($fail) { exit 1 }
