# Generated by Django 5.2.14 on 2026-06-04 15:22

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FraudFinding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("fingerprint", models.CharField(max_length=180, unique=True)),
                ("rule_code", models.CharField(db_index=True, max_length=96)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("resolved", "Resolved"),
                            ("reviewed", "Reviewed"),
                            ("dismissed", "Dismissed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("info", "Info"),
                            ("warning", "Warning"),
                            ("critical", "Critical"),
                        ],
                        db_index=True,
                        default="warning",
                        max_length=16,
                    ),
                ),
                ("target_user_label", models.CharField(blank=True, max_length=160)),
                (
                    "entity_type",
                    models.CharField(blank=True, db_index=True, max_length=80),
                ),
                (
                    "entity_id",
                    models.CharField(blank=True, db_index=True, max_length=96),
                ),
                (
                    "risk_score",
                    models.PositiveSmallIntegerField(
                        db_index=True,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("window_start", models.DateTimeField(db_index=True)),
                ("window_end", models.DateTimeField(db_index=True)),
                ("summary", models.JSONField(blank=True, default=dict)),
                ("evidence", models.JSONField(blank=True, default=dict)),
                ("metrics", models.JSONField(blank=True, default=dict)),
                ("peer_metrics", models.JSONField(blank=True, default=dict)),
                ("pattern_count", models.PositiveSmallIntegerField(default=1)),
                (
                    "first_detected_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_detected_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("occurrence_count", models.PositiveIntegerField(default=1)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "target_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="fraud_findings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-risk_score", "-last_detected_at", "-id"],
                "indexes": [
                    models.Index(
                        fields=["status", "severity", "last_detected_at"],
                        name="fraud_fraud_status_ac6800_idx",
                    ),
                    models.Index(
                        fields=["target_user", "status", "risk_score"],
                        name="fraud_fraud_target__9c5f4c_idx",
                    ),
                    models.Index(
                        fields=["rule_code", "status"],
                        name="fraud_fraud_rule_co_e9b5ea_idx",
                    ),
                    models.Index(
                        fields=["window_start", "window_end"],
                        name="fraud_fraud_window__22344d_idx",
                    ),
                ],
            },
        ),
    ]
