# Generated by Django 6.0.2 on 2026-06-18 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fraud", "0002_fraudfinding_resolution_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fraudfinding",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
    ]
