# Generated by Codex on 2026-05-19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0008_order_customer"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="unit_cost",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
