# Generated by Codex on 2026-05-21

import django.db.models.deletion
from django.db import migrations, models


def default_variant_for(product_variant_model, product_id):
    return (
        product_variant_model.objects.filter(product_id=product_id)
        .order_by("-is_default", "id")
        .first()
    )


def backfill_order_line_variants(apps, schema_editor):
    ProductVariant = apps.get_model("catalog", "ProductVariant")
    OrderLine = apps.get_model("sales", "OrderLine")
    OrderAdjustmentLine = apps.get_model("sales", "OrderAdjustmentLine")

    for line in OrderLine.objects.all().order_by("id"):
        variant = default_variant_for(ProductVariant, line.product_id)
        if variant is not None:
            line.variant_id = variant.pk
            line.save(update_fields=["variant"])

    for line in OrderAdjustmentLine.objects.all().order_by("id"):
        variant = default_variant_for(ProductVariant, line.product_id)
        if variant is not None:
            line.variant_id = variant.pk
            line.save(update_fields=["variant"])


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0004_product_variants"),
        ("sales", "0010_sales_discount_totals"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="catalog.productvariant",
            ),
        ),
        migrations.AddField(
            model_name="orderadjustmentline",
            name="variant",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_adjustment_lines",
                to="catalog.productvariant",
            ),
        ),
        migrations.RunPython(backfill_order_line_variants, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="orderline",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_lines",
                to="catalog.productvariant",
            ),
        ),
        migrations.AlterField(
            model_name="orderadjustmentline",
            name="variant",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="order_adjustment_lines",
                to="catalog.productvariant",
            ),
        ),
    ]
