# Generated by Codex on 2026-05-21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0011_orderline_variants"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderline",
            name="product",
        ),
        migrations.RemoveField(
            model_name="orderadjustmentline",
            name="product",
        ),
    ]
