# Generated by Django 5.2.14 on 2026-06-12 17:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0001_initial"),
        ("sales", "0013_order_public_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="sales_channel",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="orders",
                to="channels.saleschannel",
            ),
        ),
    ]
