# Generated by Django 5.2.14 on 2026-06-13 00:20

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0015_backfill_order_sales_channel"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderadjustmentline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
        migrations.AlterField(
            model_name="orderline",
            name="quantity",
            field=models.DecimalField(
                decimal_places=3,
                default=1,
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.001"))],
            ),
        ),
    ]
