# Generated by Django 5.2.14 on 2026-06-13 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0016_alter_orderadjustmentline_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderline",
            name="notes",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
