# Generated by Django 5.2.14 on 2026-06-13 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0010_modifiergroup_modifieroption_productmodifiergroup_and_more"),
        ("sales", "0017_orderline_notes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrderLineModifier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("group_name", models.CharField(blank=True, max_length=160)),
                ("option_name", models.CharField(blank=True, max_length=160)),
                (
                    "unit_price_delta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("quantity", models.PositiveIntegerField(default=1)),
                (
                    "modifier_option",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_line_modifiers",
                        to="catalog.modifieroption",
                    ),
                ),
                (
                    "order_line",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modifiers",
                        to="sales.orderline",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
