# Generated by Django 5.2.14 on 2026-06-23 16:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_alter_saleschannel_created_at"),
        ("customers", "0004_customer_is_auto_created_paymentcard"),
        ("sales", "0021_orderadjustment_cash_amount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="converted_to",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="converted_from",
                to="sales.order",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="reserves_stock",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("quotation", "Quotation"),
                    ("credit", "Credit"),
                ],
                default="standard",
                max_length=16,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="valid_until",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["sale_type", "status", "-created_at"],
                name="sales_order_type_status_idx",
            ),
        ),
    ]
