# Generated by Django 5.2.14 on 2026-06-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0023_stockreservation"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="special_day_keys",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
