# Generated by Django 5.2.14 on 2026-06-26 19:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0024_order_special_day_keys"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "process_return_lookup",
                        "Look up and return/exchange any invoice by receipt number",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OrderExchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "outbound_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                (
                    "replacement_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("net_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("settlement_method", models.CharField(default="cash", max_length=16)),
                ("reason", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="order_exchanges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "original_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchanges",
                        to="sales.order",
                    ),
                ),
                (
                    "register_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="order_exchanges",
                        to="sales.registersession",
                    ),
                ),
                (
                    "replacement_order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange_source",
                        to="sales.order",
                    ),
                ),
                (
                    "return_adjustment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="exchange",
                        to="sales.orderadjustment",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
