# Generated by Django 5.2.14 on 2026-09-07 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_stock_transfers"),
        ("sales", "0027_backfill_order_lifecycle"),
    ]

    operations = [
        migrations.CreateModel(
            name="RegisterProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("device_id", models.CharField(max_length=120, unique=True)),
                ("name", models.CharField(blank=True, max_length=120)),
                ("last_seen_at", models.DateTimeField(blank=True, null=True)),
                (
                    "warehouse",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="register_profiles",
                        to="inventory.warehouse",
                    ),
                ),
            ],
            options={
                "ordering": ["name", "device_id"],
            },
        ),
    ]
