# Generated by Django 5.2.14 on 2026-09-07 03:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0022_stock_transfers"),
        ("sales", "0028_register_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreservation",
            name="warehouse",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="stock_reservations",
                to="inventory.warehouse",
            ),
        ),
    ]
