# Generated by Django 6.0.2 on 2026-09-10 03:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("channels", "0003_alter_saleschannel_created_at"),
        ("customers", "0011_customer_payment_terms_basis_and_more"),
        ("sales", "0030_reservation_warehouse_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="due_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="order",
            index=models.Index(
                fields=["sale_type", "status", "due_date"],
                name="sales_order_credit_due_idx",
            ),
        ),
    ]
