# Generated by Django 5.2.14 on 2026-09-18 20:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0033_stock_unit_recent_index"),
        ("sales", "0034_trade_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockreservation",
            name="stock_unit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="reservations",
                to="inventory.stockunit",
            ),
        ),
    ]
