# Generated by Django 6.0.2 on 2026-09-22 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0035_reservation_stock_unit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ["-created_at"],
                "permissions": [
                    (
                        "process_return_lookup",
                        "Look up and return/exchange any invoice by receipt number",
                    ),
                    ("view_till_cost", "See what a product cost while selling it"),
                    (
                        "override_line_price",
                        "Change a line's selling price at the till",
                    ),
                ],
            },
        ),
        migrations.AddField(
            model_name="orderline",
            name="original_unit_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
