# Generated by Django 5.2.14 on 2026-09-22 16:04

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0036_alter_order_options_orderline_original_unit_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="extra_discount_amount",
            field=models.DecimalField(
                db_default=Decimal("0.00"),
                decimal_places=2,
                default=Decimal("0.00"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
