# Generated by Django 5.2.14 on 2026-09-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0038_job_parts_already_returned_are_put_back"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="sale_type",
            field=models.CharField(
                choices=[
                    ("standard", "Standard"),
                    ("quotation", "Quotation"),
                    ("credit", "Credit"),
                    ("account_entry", "Account entry"),
                ],
                default="standard",
                max_length=16,
            ),
        ),
    ]
