# Generated by Django 5.2.14 on 2026-08-31 01:10

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Currency",
            fields=[
                (
                    "code",
                    models.CharField(max_length=8, primary_key=True, serialize=False),
                ),
                ("name_en", models.CharField(max_length=64)),
                ("name_ar", models.CharField(max_length=64)),
                ("symbol_en", models.CharField(blank=True, default="", max_length=8)),
                ("symbol_ar", models.CharField(blank=True, default="", max_length=8)),
                ("decimals", models.PositiveSmallIntegerField(default=2)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("is_enabled", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "currencies",
                "ordering": ["display_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "instrument",
                    models.CharField(
                        choices=[("cash", "Cash"), ("bank", "Bank transfer")],
                        default="cash",
                        max_length=8,
                    ),
                ),
                ("bank_code", models.CharField(blank=True, default="", max_length=32)),
                ("effective_at", models.DateTimeField(db_index=True)),
                (
                    "rate",
                    models.DecimalField(
                        decimal_places=8,
                        max_digits=18,
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("builtin", "builtin"),
                            ("relay", "relay"),
                            ("manual", "manual"),
                        ],
                        default="relay",
                        max_length=16,
                    ),
                ),
                ("relay_id", models.CharField(blank=True, default="", max_length=80)),
                ("note", models.CharField(blank=True, default="", max_length=240)),
                (
                    "entered_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="entered_exchange_rates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_from",
                        to="fx.currency",
                    ),
                ),
                (
                    "to_currency",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="rates_to",
                        to="fx.currency",
                    ),
                ),
            ],
            options={
                "ordering": ["-effective_at", "from_currency_id"],
                "indexes": [
                    models.Index(
                        fields=[
                            "from_currency",
                            "to_currency",
                            "instrument",
                            "bank_code",
                            "-effective_at",
                        ],
                        name="fx_rate_lookup_idx",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "from_currency",
                            "to_currency",
                            "instrument",
                            "bank_code",
                            "effective_at",
                        ),
                        name="fx_rate_unique_per_instant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("rate__gt", 0)), name="fx_rate_positive"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("instrument", "bank"), ("bank_code", ""), _connector="OR"
                        ),
                        name="fx_rate_bank_code_only_for_bank",
                    ),
                ],
            },
        ),
    ]
